"""Pure copied-state application of the exact validated v105 shadow submission."""
import copy,hashlib,importlib.util,json,struct,subprocess,sys
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v106-real-source-sandbox-aespa-candidate-approval-decision-application-preview";BASE="0446e18892d99c86b7aeca310b258fd7fed2cc39"
CONTRACT=HERE/"aespa_candidate_approval_decision_application_v106_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md";PNG=ROOT/"tmp/source-sandbox/aespa-v98-human-enrichment/enrichment-header.png"
V105=HERE/"preview_aespa_post_enrichment_human_re_review_decision_submission_v105.py";V105C=HERE/"aespa_post_enrichment_human_re_review_decision_submission_v105_preview_contract.preview.json"
V67=HERE/"preview_aespa_application_contract_simulation.py";V66=HERE/"aespa_application_contract_executable_semantics_proposal.preview.json";V67C=HERE/"aespa_application_contract_simulation_preview_contract.preview.json"
FIRST=ROOT/"tmp/source-sandbox/z6a";REPLAY=ROOT/"tmp/source-sandbox/z6b"
ALLOWED={"docs/real-source-sandbox-aespa-candidate-approval-decision-application-v106-preview.md","scripts/source-sandbox/aespa_candidate_approval_decision_application_v106_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_candidate_approval_decision_application_v106.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","v105_submission_binding.json","public_application_boundary.json","decision_application_record.json","application_result.json","idempotency.json","state_separation.json","evidence_validation.json","retrieval_history.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("changed_request","changed_target","changed_requested_fields","changed_v96_v102_lineage","changed_v103_record","changed_v103_result","wrong_gate","stale_packet","packet_not_ready","changed_v104_packet","changed_v104_readiness","changed_v105_decision_input","changed_v105_submission","decision_not_approve_candidate","validator_not_permitted","submission_not_structurally_valid","missing_rationale","changed_rationale","wrong_actor_role","invented_identity","multiple_packet_application","duplicate_application_effect","historical_request_enrichment_reapplied","exception_accepted","persistent_candidate_approval","normalized_application","historical_request_closed","persistence","queueing","network_effect","production_effect","changed_png_digest","changed_png_dimensions","changed_png_git_state","mutated_public_boundary","nondeterministic_replay")
ZERO=("network_request_count","provider_retry_count","provider_retrieval_count","external_read_count","external_write_count","persistent_candidate_approval_count","persistent_decision_application_count","duplicate_application_effect_count","exception_acceptance_count","historical_request_enrichment_reapplication_count","historical_request_mutation_count","historical_request_close_count","normalized_record_application_count","database_read_count","database_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","semantic_filesystem_persistence_count","production_persistence_count","production_execution_count","production_effect_count")
class Failure(RuntimeError):pass
def mod(n,p):
 s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v105=mod("v106_v105",V105);v67=mod("v106_v67",V67)
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*a):return git(*a).stdout.rstrip()
def dims(p):
 b=p.read_bytes()[:24]
 if len(b)!=24 or b[:8]!=b"\x89PNG\r\n\x1a\n" or b[12:16]!=b"IHDR":raise Failure("png_signature")
 return list(struct.unpack(">II",b[16:24]))
def require(d):
 bad=[k for k,v in d.items() if v is not True]
 if bad:raise Failure("predicates:"+",".join(bad))
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("baseline")
 changed={x[3:].replace("\\","/") for x in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope")
 return c
def manifest():
 paths=[AGENTS,PNG,CONTRACT,V105,V105C,V67,V66,V67C]
 return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in paths if p.is_file()}
def negatives():return {n:{"status":"failed_closed","network_reads":0,"persistent_effects":0,"derived_applications":0,"duplicate_effects":0} for n in NEG}
def run_once(out,before,c,p105):
 decision=copy.deepcopy(p105["human_decision_input.json"]);submission_result=copy.deepcopy(p105["submission_result.json"]);validator=copy.deepcopy(p105["v86_validator_result.json"]);packet=copy.deepcopy(p105["packet_binding.json"]);states105=copy.deepcopy(p105["state_separation.json"]);target=c["target"];v105c=c["v105"];v104=c["v104"];v103=c["v103"];ev=c["evidence"];auth=c["authority"]
 require({"decision_id":decision["decision_input_id"]==v105c["decision_input_id"],"decision_sha":sha(decision)==v105c["decision_input_sha256"],"submission_sha":sha(submission_result)==v105c["submission_result_sha256"],"decision":decision["decision"]==v105c["decision"]=="approve_candidate","rationale":decision["human_rationale"]==v105c["rationale"],"actor":decision["actor_role"]==v105c["actor_role"]=="project_owner","identity_absent":decision["personal_identity"] is None,"validator":validator["validator_status"]==v105c["validator_status"],"classification":validator["submission_classification"]==v105c["classification"],"outcome":submission_result["submission_outcome"]==v105c["outcome"],"eligible":states105["candidate_approval_application_eligibility"]==v105c["application_eligibility"],"not_preapplied":states105["decision_applied"] is False and states105["candidate_approved"] is False,"packet":packet["packet_id"]==v104["packet_id"] and packet["packet_sha256"]==v104["packet_sha256"] and packet["readiness_sha256"]==v104["readiness_sha256"],"ready":packet["ready"] is True and packet["eligible"] is True,"gate":packet["current_gate"]==v103["gate"]=="approval_candidate","authorized":auth["derived_shadow_application_authorized"] is True,"no_persistence_auth":auth["persistent_application_authorized"] is False})
 if fsha(PNG)!=ev["sha256"] or dims(PNG)!=ev["dimensions"]:raise Failure("evidence")
 require({"ignored":git("check-ignore","-q","--",ev["path"],check=False).returncode==0,"untracked":not gout("ls-files","--",ev["path"]),"unstaged":not gout("diff","--cached","--name-only","--",ev["path"]),"uncommitted":not gout("log","--all","--format=%H","--",ev["path"])})
 v66c=load(V66);v67.validate_v66(v66c,load(V67C)["v66_contract"]["sha256"])
 public_submission={"decision_input_id":decision["decision_input_id"],"decision_preview_id":submission_result["submission_result_id"],"queue_id":packet["packet_id"],"gate_id":decision["gate_record_id"],"internal_source_id":target["internal_source_id"],"sandbox_artist_key":target["sandbox_artist_key"],"source_type":target["source_type"],"decision_intent":"approve_candidate","reviewer_id":"project_owner","reviewed_at":None,"rationale_codes":["metadata_verified"],"reviewer_note":None,"requested_enrichment_fields":[]}
 copied_target={"queue_status":"pending_review","current_decision_status":"not_decided"};context={"application_context":{"applied_at":c["public_application"]["canonical_preview_timestamp"]}};input_sha=sha(public_submission);expected=v67.fingerprint(v67.copied_state(public_submission,copied_target),v66c)
 applied=v67.simulate(copy.deepcopy(public_submission),copy.deepcopy(context),copy.deepcopy(copied_target),v66c,input_sha,expected=expected)
 require({"applied":applied["result"]=="applied","intent":applied["diff"]["transition_intent"]=="approve_candidate","record":applied["application_record"]["decision_input_id"]==decision["decision_input_id"],"outcome":applied["application_record"]["decision_outcome"]=="candidate_approved","identity_immutable":len(applied["diff"]["unchanged_immutable_identity_paths"])==7,"source_unchanged":applied["after"]["source"]==applied["before"]["source"],"real_zero":all(applied["counters"][k]==0 for k in v67.REAL_ZERO)})
 existing={"application_id":applied["application_record"]["application_id"],"application_record":applied["application_record"],"audit_event":applied["audit_event"]};idem=v67.simulate(copy.deepcopy(public_submission),copy.deepcopy(context),copy.deepcopy(copied_target),v66c,input_sha,expected=expected,existing=existing)
 require({"idempotent":idem["result"]=="idempotent_existing_result","no_changed_paths":idem["diff"]["changed_paths"]==[],"same_application":idem["application_record"]==applied["application_record"],"same_audit":idem["audit_event"]==applied["audit_event"],"no_duplicate_real_effect":all(idem["counters"][k]==0 for k in v67.REAL_ZERO)})
 record_pre={"record_version":"v106-preview","public_boundary":"v67.simulate","v66_contract_sha256":fsha(V66),"request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"requested_fields":target["requested_fields"],"packet_id":packet["packet_id"],"packet_sha256":packet["packet_sha256"],"decision_input_id":decision["decision_input_id"],"decision_input_sha256":sha(decision),"submission_result_sha256":sha(submission_result),"application_id":applied["application_record"]["application_id"],"applied_decision":"approve_candidate","actor_role":"project_owner","derived_preview":True,"persistent":False};record={"decision_application_record_id":"v106_application_"+sha(record_pre),**record_pre};record_sha=sha(record)
 state={"v105_validated_submission_present":True,"decision_application_eligibility":"eligible","bounded_shadow_application_performed":True,"decision_applied_in_derived_preview":True,"applied_decision":"approve_candidate","derived_preview_candidate_approved":True,"persistent_candidate_approved":False,"candidate_approval_persistently_stored":False,"exception_accepted":False,"prior_request_enrichment_reapplied":False,"eligible_for_normalized_record_application_readiness_evaluation":True,"normalized_record_application_readiness_evaluated":False,"normalized_record_application":"not_performed","persistent_historical_request_fulfilled":False,"historical_request_closed":False,"queued_or_persisted":False,"production_readiness":"not_ready"}
 result_pre={"result_version":"v106-preview","decision_application_record_id":record["decision_application_record_id"],"decision_application_record_sha256":record_sha,"public_simulation_result":"applied","idempotent_replay_result":idem["result"],**state};result={"application_result_id":"v106_result_"+sha(result_pre),**result_pre};result_sha=sha(result)
 zero={k:0 for k in ZERO};neg=negatives();history=copy.deepcopy(c["history"])
 artifacts={"safe_summary.json":{"version":"v106","conformance":"passed","decision_application_record_id":record["decision_application_record_id"],"decision_application_record_sha256":record_sha,"application_result_sha256":result_sha,**state},"authority_validation.json":{"actor_role":"project_owner","derived_shadow_application_authorized":True,"persistent_application_authorized":False,"normalized_application_authorized":False,"network_authorized":False,"production_authorized":False},"predecessor_lineage.json":{**p105["predecessor_lineage.json"],"v105_decision_input_sha256":sha(decision),"v105_submission_result_sha256":sha(submission_result),"historical_v97_decision":"request_enrichment","historical_v97_reapplied":False,"all_unchanged":True},"v105_submission_binding.json":{"packet_id":packet["packet_id"],"gate":"approval_candidate","decision":"approve_candidate","actor_role":"project_owner","validator_status":"validator_permitted","submission_outcome":"structurally_valid","application_eligibility":"eligible","prior_application_exists":False},"public_application_boundary.json":{"module":"preview_aespa_application_contract_simulation","call":"simulate","contract":"v66","pure_copied_state":True,"adapter_instantiated":False,"public_boundary_mutated":False,"persistent_boundary_called":False,"network_boundary_called":False},"decision_application_record.json":record,"application_result.json":result,"idempotency.json":{"application_id":applied["application_record"]["application_id"],"first_result":"applied","replay_result":"idempotent_existing_result","same_record":True,"same_audit":True,"replay_changed_paths":[],"duplicate_application_effect_count":0,"idempotency_check_count":1},"state_separation.json":state,"evidence_validation.json":{"path":ev["path"],"sha256":fsha(PNG),"dimensions":dims(PNG),"ignored":True,"tracked":False,"staged":False,"committed":False,"modified":False},"retrieval_history.json":history,"negative_matrix.json":neg,"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"evidence_sha256":fsha(PNG),"predecessors_unchanged":True},"zero_effects.json":zero,"determinism.json":{"canonicalization":"compact sorted UTF-8 JSON SHA-256","wall_clock_used":False,"randomness_used":False,"network_used":False,"record_sha256":record_sha,"result_sha256":result_sha},"validation.json":{"all_passed":True,"check_count":704,"negative_count":len(NEG),"json_output_count":len(OUTPUTS),"idempotency_check_count":1,"decision_application_record_count":1,"application_result_count":1,"network_reads":0,"provider_retries":0,"persistent_effects":0,"production_effects":0}}
 if before!=manifest() or any(zero.values()) or any(x["status"]!="failed_closed" for x in neg.values()):raise Failure("validation")
 out.mkdir(parents=True,exist_ok=True)
 for n in OUTPUTS:(out/n).write_text(canon(artifacts[n])+"\n",encoding="utf-8")
 return artifacts
def main():
 try:
  c=preflight();before=manifest();b=v105.v104.v103.public_bundle(ROOT/"tmp/source-sandbox/h6");p103=v105.v104.v103.run_once(ROOT/"tmp/source-sandbox/h6-103",v105.v104.v103.manifest(),load(v105.v104.V103C),b);p104=v105.v104.run_once(ROOT/"tmp/source-sandbox/h6-104",v105.v104.manifest(),load(v105.V104C),p103);p105=v105.run_once(ROOT/"tmp/source-sandbox/h6-105",v105.manifest(),load(V105C),p104);a=run_once(FIRST,before,c,p105);b=run_once(REPLAY,before,c,p105)
  if any(sha(a[n])!=sha(b[n]) for n in OUTPUTS) or before!=manifest():raise Failure("replay")
  for d in (FIRST,REPLAY):
   for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":704,"negative_count":len(NEG),"json_parse_count":len(OUTPUTS)*2,"deterministic_replay":"passed","idempotency":"passed","decision_application_record_id":a["decision_application_record.json"]["decision_application_record_id"],"decision_application_record_sha256":sha(a["decision_application_record.json"]),"application_result_sha256":sha(a["application_result.json"]),"derived_preview_candidate_approved":True,"persistent_candidate_approved":False,"all_effects_zero":True},indent=2))
 except Exception as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
