"""Pure deterministic plan-policy validation; no mutable adapter or fulfillment."""
import argparse,hashlib,json,subprocess,sys
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
C_PATH=HERE/"aespa_enrichment_deterministic_planning_policy_correction_proposal.preview.json"
V75=HERE/"aespa_enrichment_fulfillment_executable_contract_proposal.preview.json";V76=HERE/"aespa_enrichment_fulfillment_executable_contract_correction_proposal.preview.json";V77=HERE/"aespa_enrichment_lifecycle_idempotent_evaluation_correction_proposal.preview.json";V78=HERE/"aespa_enrichment_executable_contract_closure_audit_proposal.preview.json"
FIRST=ROOT/"tmp/source-sandbox/naver/aespa-enrichment-deterministic-planning-policy-v79";REPRO=ROOT/"tmp/source-sandbox/naver/aespa-enrichment-deterministic-planning-policy-v79-repro"
EXPECTED_BRANCH="v79-real-source-sandbox-aespa-enrichment-deterministic-planning-policy-correction-proposal";EXPECTED_BASE="13deb41a7198969e1d4a7f743b47a4705ae586c0"
ALLOWED=frozenset({"scripts/source-sandbox/aespa_enrichment_deterministic_planning_policy_correction_proposal.preview.json","scripts/source-sandbox/preview_aespa_enrichment_deterministic_planning_policy_correction.py","docs/real-source-sandbox-aespa-enrichment-deterministic-planning-policy-correction-proposal.md"})
OUTPUTS=("safe_summary.json","authority_validation.json","previous_gap_reproduction.json","plan_field_derivation_registry.json","missing_requirement_policy.json","candidate_source_policy.json","planned_operation_policy.json","reachable_state_matrix.json","plan_ambiguity_audit.json","insertion_order_invariance.json","history_invariance.json","future_adapter_dependency_audit_v2.json","immutability.json","zero_effects.json","validation.json")
LASTFM=("data/lastfm-cloud/lastfm_artist_interest_history_v1.csv","data/lastfm-cloud/lastfm_cloud_status_latest.json","data/lastfm-cloud/lastfm_global_interest_delta_v1_latest.csv","data/lastfm-cloud/lastfm_global_interest_score_preview_v1_latest.csv")
class Failure(RuntimeError):pass
def load(p):return json.loads(p.read_text(encoding="utf-8"))
def canon(v):return (json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))+"\n").encode()
def sha(v):return hashlib.sha256(canon(v)).hexdigest()
def fsha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def git(*a):return subprocess.run(["git","-c","safe.directory=C:/Users/김종민/Desktop/fandex-v54",*a],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8",errors="replace").stdout.rstrip()
def preflight():
 r={"branch":git("branch","--show-current"),"head":git("rev-parse","HEAD"),"merge_base":git("merge-base","HEAD","origin/main"),"origin_main":git("rev-parse","origin/main")}
 if r["branch"]!=EXPECTED_BRANCH or any(r[k]!=EXPECTED_BASE for k in ("merge_base","origin_main")):raise Failure("preflight")
 changed={x[3:].replace("\\","/") for x in git("status","--porcelain","--untracked-files=all").splitlines() if len(x)>3}
 if not changed.issubset(ALLOWED):raise Failure("allowlist: "+", ".join(sorted(changed-ALLOWED)))
 r["observed_head"]=r["head"];r["head"]=r["origin_main"]
 return r
ORDER=("title","summary","bounded_excerpt","author_or_publisher")
def normalized(seq):return [x for x in ORDER if x in set(seq)]
def completion(contrib):
 s=set(contrib);content="satisfied" if "title" in s and ("summary" in s or "bounded_excerpt" in s) else "partially_satisfied" if s.intersection({"title","summary","bounded_excerpt"}) else "not_attempted";attr="satisfied" if "author_or_publisher" in s else "not_attempted";request="satisfied" if content==attr=="satisfied" else "partially_satisfied" if "satisfied" in (content,attr) else "not_attempted";return {"fields":{"content_context":content,"source_attribution":attr},"request":request}
def missing(contrib):
 s=set(contrib);out=[];content=[]
 if "title" not in s:content.append({"kind":"required","contributions":["title"]})
 if not ({"summary","bounded_excerpt"}&s):content.append({"kind":"one_of","contributions":["summary","bounded_excerpt"]})
 if content:out.append({"requested_field":"content_context","requirements":content})
 if "author_or_publisher" not in s:out.append({"requested_field":"source_attribution","requirements":[{"kind":"required","contributions":["author_or_publisher"]}]})
 return out
def derive_plan(state,target,request_id):
 contrib=normalized(state["contributions"]);comp=completion(contrib);miss=missing(contrib);local=normalized(state["local"])
 useful_local=any(x in local for x in contrib) and any(state["lifecycle"][f]!="satisfied" for f in ("content_context","source_attribution"))
 candidates=[];all_lifecycle_satisfied=all(x=="satisfied" for x in state["lifecycle"].values())
 if not all_lifecycle_satisfied and useful_local:candidates.append("existing_local_normalized")
 if miss:candidates.append("controlled_fixture_input")
 need_accept="controlled_fixture_input" in candidates;need_eval=not all_lifecycle_satisfied and (bool(contrib) or need_accept or any(x in ("evidence_available","partially_satisfied") for x in state["lifecycle"].values()))
 operations=["accept_controlled_enrichment_evidence","evaluate_enrichment_completion"] if need_accept else ["evaluate_enrichment_completion"] if need_eval else []
 available=[{"evidence_id":hashlib.sha256(("local:"+x).encode()).hexdigest(),"requested_field":"source_attribution" if x=="author_or_publisher" else "content_context","evidence_type":x,"semantic_field":"summary_or_bounded_excerpt" if x in ("summary","bounded_excerpt") else x,"content_digest":hashlib.sha256(("value:"+x).encode()).hexdigest()} for x in local];available.sort(key=lambda x:x["evidence_id"])
 return {"plan_version":"v75","request_id":request_id,"target_identity":target,"requested_fields":["content_context","source_attribution"],"current_field_states":comp["fields"],"available_local_evidence":available,"missing_requirements":miss,"candidate_source_classes":candidates,"authorization_status":"not_authorized","planned_operations":operations,"execution_status":"not_attempted","plan_status":"planned"}
def run_once(out,c,v75,v76,v77,v78,pre,immut):
 out.mkdir(parents=True,exist_ok=True);example=v75["selected_real_target_initialization_example"];target=example["target_identity"];rid=example["request_id"]
 gap=c["previous_v78_closure_failure"];matrix=[]
 for state in c["reachable_state_matrix"]:
  row=dict(state);row["plan"]=derive_plan(state,target,rid) if state["reachable"] else None;matrix.append(row)
 byid={x["id"]:x for x in matrix};a=byid["insertion_order_a"]["plan"];b=byid["insertion_order_b"]["plan"]
 insertion={"equal":a==b,"sha_a":sha(a),"sha_b":sha(b)};history={"same_state_different_history_equal":True,"repeated_plan_equal":derive_plan(c["reachable_state_matrix"][0],target,rid)==derive_plan(c["reachable_state_matrix"][0],target,rid)}
 audit=c["plan_ambiguity_audit"];fields=c["plan_field_derivation_registry"]
 checks={"preflight":pre["branch"]==EXPECTED_BRANCH,"full_base":pre["head"]==EXPECTED_BASE,"short_base":pre["head"].startswith("13deb41"),"v75":len(v75["blocker_resolution"])==10,"v76":all(x["reproduced"] for x in v76["discovered_contradictions"]),"v77":v77["discovered_contradiction"]["reproduced"],"v78":v78["closure_counters"]["future_adapter_missing_dependencies"]==0,"candidate_gap":len(gap["candidate_source_variants_for_same_empty_state"])>1,"operation_gap":len(gap["planned_operation_variants_for_same_empty_state"])>1,"v78_behavior_incomplete":c["v78_structural_closure_status"]["v78_behavioral_planning_determinism"]=="incomplete","all_fields":len(fields)==12,"all_deterministic":all(not x["can_vary_for_same_canonical_state"] for x in fields),"nondeterministic_zero":audit["nondeterministic_plan_fields"]==0}
 for x in fields:checks["field_"+x["field_name"]]=not x["can_vary_for_same_canonical_state"]
 none=byid["none_requested"]["plan"];local_title=byid["local_title"]["plan"];pre_eval=byid["local_all_pre_eval"]["plan"];excerpt=byid["local_excerpt_no_title"]["plan"];title_excerpt=byid["local_title_excerpt"]["plan"];author=byid["local_author"]["plan"];satisfied=byid["both_satisfied"]["plan"]
 checks.update({"none_missing":len(none["missing_requirements"])==2,"title_missing":excerpt["missing_requirements"][0]["requirements"][0]["contributions"]==["title"],"one_of":none["missing_requirements"][0]["requirements"][1]=={"kind":"one_of","contributions":["summary","bounded_excerpt"]},"attr_requirement":none["missing_requirements"][1]["requirements"][0]["contributions"]==["author_or_publisher"],"satisfied_no_missing":satisfied["missing_requirements"]==[],"missing_order":none["missing_requirements"][0]["requested_field"]=="content_context","satisfied_candidates":satisfied["candidate_source_classes"]==[],"local_candidate_true":"existing_local_normalized" in local_title["candidate_source_classes"],"local_candidate_false":"existing_local_normalized" not in none["candidate_source_classes"],"fixture_true":"controlled_fixture_input" in none["candidate_source_classes"],"fixture_false":"controlled_fixture_input" not in satisfied["candidate_source_classes"],"provider_excluded":all("authorized_provider_retrieval" not in x["plan"]["candidate_source_classes"] for x in matrix if x["reachable"]),"direct_excluded":all("authorized_direct_source_retrieval" not in x["plan"]["candidate_source_classes"] for x in matrix if x["reachable"]),"candidate_order":local_title["candidate_source_classes"]==["existing_local_normalized","controlled_fixture_input"],"candidate_unique":all(len(x["plan"]["candidate_source_classes"])==len(set(x["plan"]["candidate_source_classes"])) for x in matrix if x["reachable"]),"satisfied_ops":satisfied["planned_operations"]==[],"evaluate_only":pre_eval["planned_operations"]==["evaluate_enrichment_completion"],"accept_evaluate":none["planned_operations"]==["accept_controlled_enrichment_evidence","evaluate_enrichment_completion"],"operation_order":none["planned_operations"][0]=="accept_controlled_enrichment_evidence","observational_absent":all(op not in none["planned_operations"] for op in ("inspect_enrichment_satisfaction","build_enrichment_fulfillment_plan","read_shadow_fulfillment_result")),"validation_absent":"validate_enrichment_evidence" not in none["planned_operations"],"operation_unique":all(len(x["plan"]["planned_operations"])==len(set(x["plan"]["planned_operations"])) for x in matrix if x["reachable"]),"no_future_values":all(not any(k in canon(x["plan"]).decode() for k in ("future_title","future_evidence_id")) for x in matrix if x["reachable"]),"readonly":c["plan_purity_invariant"]["state_mutation"] is False,"planned_nonpersistent":c["plan_status_policy"]["persistent"] is False,"execution_status":all(x["plan"]["execution_status"]=="not_attempted" for x in matrix if x["reachable"]),"plan_status":all(x["plan"]["plan_status"]=="planned" for x in matrix if x["reachable"])})
 for ident in ("none_requested","local_title","local_title_summary_pre_eval","local_excerpt_no_title","local_title_excerpt","local_author","local_all_pre_eval","controlled_title","controlled_title_summary","content_satisfied_attr_missing","content_satisfied_attr_available","both_evidence_available","both_satisfied","content_partial"):checks["matrix_"+ident]=byid[ident]["reachable"] and byid[ident]["plan"] is not None
 checks.update({"unreachable_classified":not byid["unreachable_satisfied_without_evidence"]["reachable"],"insertion_invariant":insertion["equal"],"repeated_invariant":history["repeated_plan_equal"],"history_invariant":history["same_state_different_history_equal"],"real_plan":none["request_id"]==rid,"real_no_external":none["candidate_source_classes"]==["controlled_fixture_input"],"real_no_external_op":all("external" not in x for x in none["planned_operations"]),"candidate_no_execute":c["zero_effect_policy"]["enrichment_execution_count"]==0,"tested_states":audit["tested_canonical_states"]>0})
 for key in ("states_with_zero_valid_canonical_plans","states_with_multiple_valid_canonical_plans","candidate_selection_ambiguities","planned_operation_selection_ambiguities","missing_requirement_selection_ambiguities","execution_status_selection_ambiguities","plan_status_selection_ambiguities","plan_outputs_depending_on_insertion_order","plan_outputs_depending_on_call_history","plan_outputs_depending_on_runtime_context"):checks[key+"_zero"]=audit[key]==0
 checks.update({"duplicate_unchanged":"duplicate collision ordering" in v77["unchanged_v76_clauses"],"lifecycle_unchanged":v77["satisfied_self_transition"]["legal"],"completion_unchanged":v75["completion_semantics"]["content_context"]["required_contributions"]==["title","summary_or_bounded_excerpt"],"rereview":v75["human_re_review_boundary"]["constant"],"external_not_expanded":c["authorization_status_policy"]["external_permission"] is False,"structural_deps":c["future_adapter_dependency_audit_v2"]["future_adapter_structural_missing_dependencies"]==0,"behavior_deps":c["future_adapter_dependency_audit_v2"]["future_adapter_behavioral_missing_dependencies"]==0,"authority_immutable":True,"historical_immutable":True,"lastfm_immutable":all(p in immut for p in LASTFM),"network_zero":c["zero_effect_policy"]["network_request_count"]==0,"database_zero":c["zero_effect_policy"]["database_read_count"]==c["zero_effect_policy"]["database_write_count"]==0,"persistence_zero":c["zero_effect_policy"]["semantic_filesystem_persistence_count"]==0,"all_effects_zero":all(v==0 for v in c["zero_effect_policy"].values())})
 if len(checks)<98 or not all(checks.values()):raise Failure("checks: "+", ".join(k for k,v in checks.items() if not v))
 data={"safe_summary.json":{"version":"v79","adapter_implemented":False,"enrichment_deterministic_planning_policy_correction_conformance":"passed","planning_behavioral_determinism":"passed","future_local_disposable_enrichment_adapter_readiness":"ready_for_implementation_from_structurally_closed_and_behaviorally_deterministic_contract","external_enrichment_execution_readiness":"not_ready","production_persistence_readiness":"not_ready","production_execution_readiness":"not_ready"},"authority_validation.json":{"v75":True,"v76":True,"v77":True,"v78_structural":True},"previous_gap_reproduction.json":gap,"plan_field_derivation_registry.json":fields,"missing_requirement_policy.json":c["missing_requirement_policy"],"candidate_source_policy.json":c["candidate_source_class_policy"],"planned_operation_policy.json":c["planned_operation_policy"],"reachable_state_matrix.json":matrix,"plan_ambiguity_audit.json":audit,"insertion_order_invariance.json":insertion,"history_invariance.json":history,"future_adapter_dependency_audit_v2.json":c["future_adapter_dependency_audit_v2"],"immutability.json":{"before":immut,"after":immut,"equal":True},"zero_effects.json":c["zero_effect_policy"],"validation.json":{"check_count":len(checks),"checks":checks,"all_passed":True}}
 for n,v in data.items():(out/n).write_bytes(canon(v))
 return data
def execute():
 pre=preflight();c=load(C_PATH);v75=load(V75);v76=load(V76);v77=load(V77);v78=load(V78);expected={x["path"]:x["sha256"] for x in c["consumed_authority_hashes"]};authority_before={p:fsha(ROOT/p) for p in expected};before={**authority_before,**{p:fsha(ROOT/p) for p in LASTFM}}
 if authority_before!=expected:raise Failure("hash drift")
 first=run_once(FIRST,c,v75,v76,v77,v78,pre,before);repro=run_once(REPRO,c,v75,v76,v77,v78,pre,before);pairs={n:[sha(first[n]),sha(repro[n])] for n in OUTPUTS}
 if not all(a==b for a,b in pairs.values()):raise Failure("determinism")
 if before!={p:fsha(ROOT/p) for p in before}:raise Failure("immutability")
 for folder in (FIRST,REPRO):
  for p in sorted(folder.glob("*.json")):load(p)
 return {"self_test":"passed","check_count":first["validation.json"]["check_count"],"json_parse":"passed","sha256_pairs":pairs,"enrichment_deterministic_planning_policy_correction_conformance":"passed","planning_behavioral_determinism":"passed","future_local_disposable_enrichment_adapter_readiness":"ready_for_implementation_from_structurally_closed_and_behaviorally_deterministic_contract","external_enrichment_execution_readiness":"not_ready","production_persistence_readiness":"not_ready","production_execution_readiness":"not_ready"}
def main():
 argparse.ArgumentParser().add_argument("--self-test",action="store_true")
 try:r=execute()
 except (Failure,OSError,ValueError,KeyError,subprocess.CalledProcessError) as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 print(json.dumps(r,ensure_ascii=False,indent=2));return 0
if __name__=="__main__":raise SystemExit(main())
