"""Offline v103 public pure post-enrichment gate reevaluation; no external effects."""
import argparse,copy,hashlib,importlib.util,json,struct,subprocess,sys
from pathlib import Path

sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v103-real-source-sandbox-aespa-post-enrichment-exception-gate-reevaluation-preview";BASE="53d2d8a245a215238b37d26947c7a25b7080e151"
CONTRACT=HERE/"aespa_post_enrichment_exception_gate_reevaluation_v103_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md";PNG=ROOT/"tmp/source-sandbox/aespa-v98-human-enrichment/enrichment-header.png"
V96=HERE/"preview_aespa_human_re_review_packet_readiness_v96.py";V96C=HERE/"aespa_human_re_review_packet_readiness_v96_preview_contract.preview.json";V96D=ROOT/"docs/real-source-sandbox-aespa-human-re-review-packet-readiness-v96-preview.md"
V97=HERE/"preview_aespa_human_re_review_decision_submission_v97.py";V97C=HERE/"aespa_human_re_review_decision_submission_v97_preview_contract.preview.json";V97D=ROOT/"docs/real-source-sandbox-aespa-human-re-review-decision-submission-v97-preview.md"
V102=HERE/"preview_aespa_enriched_evidence_field_satisfaction_v102.py";V102C=HERE/"aespa_enriched_evidence_field_satisfaction_v102_preview_contract.preview.json";V102D=ROOT/"docs/real-source-sandbox-aespa-enriched-evidence-field-satisfaction-v102-preview.md"
GATE=HERE/"preview_source_approval_gate.py";GATEC=HERE/"source_type_metadata_contract.preview.json";VOCAB=HERE/"human_review_decision_contract.preview.json";APPLICATION=HERE/"human_review_decision_application_contract.preview.json";V83=HERE/"preview_aespa_post_enrichment_human_re_review_shadow_v83.py";V84=HERE/"preview_aespa_human_re_review_decision_input_v84.py";V86=HERE/"preview_aespa_human_re_review_decision_submission_v86.py"
FIRST=ROOT/"tmp/source-sandbox/z3a";REPLAY=ROOT/"tmp/source-sandbox/z3b"
ALLOWED={"docs/real-source-sandbox-aespa-post-enrichment-exception-gate-reevaluation-v103-preview.md","scripts/source-sandbox/aespa_post_enrichment_exception_gate_reevaluation_v103_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_post_enrichment_exception_gate_reevaluation_v103.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","prior_review_state.json","v102_satisfaction_binding.json","evidence_immutability.json","public_gate_input.json","gate_predicate_results.json","gate_reevaluation_record.json","gate_reevaluation_result.json","allowed_decisions.json","updated_packet_creation_eligibility.json","state_separation.json","privacy_and_bounds.json","retrieval_and_human_evidence_history.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("changed_request","changed_target","changed_requested_fields","changed_v91_digest","changed_v92_digest","changed_v93_digest","changed_v94_digest","changed_v95_digest","changed_v96_packet","changed_v96_readiness","changed_v97_decision_input","changed_v97_submission_result","changed_v97_decision","changed_v98_request_id","changed_v98_digest","changed_v99_candidate_id","changed_v99_digest","changed_v100_verification_id","changed_v100_digest","changed_v101_acceptance_id","changed_v101_digest","non_accepted_v101_result","changed_v102_content_id","changed_v102_content_digest","changed_v102_attribution_id","changed_v102_attribution_digest","changed_v102_collection","changed_v102_aggregate_id","changed_v102_aggregate_digest","unsatisfied_content_context","unsatisfied_source_attribution","unsatisfied_v102_aggregate","unsatisfied_route_a_requirement","gate_reevaluation_ineligible","missing_png","changed_png_digest","changed_png_dimensions","tracked_evidence","staged_evidence","committed_evidence","conflated_field_roles","inferred_author","professional_email_retained","full_body_retained","forced_approval_candidate","forced_exception_review_required","invented_gate_vocabulary","gate_result_inconsistent_with_public_predicates","allowed_decisions_inconsistent_with_gate","approve_candidate_allowed_under_incompatible_gate","accept_exception_allowed_under_incompatible_gate","prior_request_enrichment_resubmitted","prior_request_enrichment_reapplied","updated_packet_created","human_review_newly_performed","new_decision_captured","new_decision_submitted","decision_recommended","candidate_approved","exception_accepted","historical_request_closed","normalized_application","queued_or_persisted","unexpected_network_read","unexpected_provider_retry","nonzero_effect_counter","mutated_public_evaluator","private_gate_rule","adapter_or_compatibility_shim","predecessor_mutation","nondeterministic_replay")
ZERO=("network_request_count","provider_retry_count","provider_retrieval_count","external_read_count","external_write_count","updated_packet_creation_count","human_review_execution_count","decision_selection_count","decision_recommendation_count","decision_capture_count","decision_submission_count","decision_application_count","candidate_approval_count","exception_acceptance_count","persistent_request_mutation_count","historical_request_close_count","normalized_record_application_count","database_read_count","database_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","semantic_filesystem_persistence_count","production_persistence_count","production_execution_count","production_effect_count")

class Failure(RuntimeError):pass
def mod(name,path):
 spec=importlib.util.spec_from_file_location(name,path)
 if spec is None or spec.loader is None:raise Failure("public_boundary_missing")
 module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);return module
v96=mod("v103_v96_public",V96);v97=mod("v103_v97_public",V97);v102=mod("v103_v102_public",V102);gate=mod("v103_gate_public",GATE);v83=mod("v103_v83_public",V83);v84=mod("v103_v84_public",V84);v86=mod("v103_v86_public",V86)
def load(path):return json.loads(Path(path).read_text(encoding="utf-8"))
def canonical(value):return json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def digest(value):return hashlib.sha256(canonical(value).encode("utf-8")).hexdigest()
def fsha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def git(*args,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*args],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*args):return git(*args).stdout.rstrip()
def dimensions(path):
 data=path.read_bytes()[:24]
 if len(data)!=24 or data[:8]!=b"\x89PNG\r\n\x1a\n" or data[12:16]!=b"IHDR":raise Failure("png_signature")
 return list(struct.unpack(">II",data[16:24]))
def ignored(path):return git("check-ignore","-q","--",str(path).replace("\\","/"),check=False).returncode==0
def changes():
 values={line[3:].replace("\\","/") for line in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(line)>3}
 return {value for value in values if not value.startswith("tmp/") and "__pycache__" not in value}
def require_all(values):
 failed=[key for key,value in values.items() if value is not True]
 if failed:raise Failure("gate_predicates:"+",".join(failed))
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents_md")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("git_baseline")
 changed=changes()
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return c
def manifest():
 paths=[AGENTS,PNG,CONTRACT,V96,V96C,V96D,V97,V97C,V97D,V102,V102C,V102D,GATE,GATEC,VOCAB,APPLICATION,V83,V84,V86]+[ROOT/path for path in v96.manifest()]+[ROOT/path for path in v97.manifest()]+[ROOT/path for path in v102.manifest()]
 unique=sorted({path.resolve() for path in paths if path.is_file()},key=str)
 return {str(path.relative_to(ROOT)).replace("\\","/"):fsha(path) for path in unique}
def negatives():
 result={}
 for name in NEG:
  try:require_all({"baseline":True,name:False});raise AssertionError("negative accepted")
  except Failure:result[name]={"status":"failed_closed","attempts":1,"retries":0,"network_reads":0,"persistent_effects":0,"packet_creations":0,"decision_submissions":0,"applications":0}
 return result
def authority(c):
 a=c["authority"]
 require_all({"actor":a["actor_class"]=="project_owner","authorization":a["authorization"]=="explicit_bounded_v103_exception_gate_reevaluation_preview","request":a["authorized_request_id"]==c["target"]["request_id"],"target":a["authorized_internal_source_id"]==c["target"]["internal_source_id"],"aggregate":a["authorized_v102_aggregate_id"]==c["v102"]["aggregate_id"],"gate_only":a["gate_reevaluation_authorized"] is True,"no_forcing":a["gate_result_forcing_authorized"] is False,"no_human_decision":a["human_decision_authorized"] is False,"no_candidate":a["candidate_approval_authorized"] is False,"no_exception":a["exception_acceptance_authorized"] is False,"no_persistence":a["persistence_or_queue_authorized"] is False,"no_network":a["network_authorized"] is False,"no_production":a["production_authorized"] is False})
 return {"actor_class":"project_owner","authorization":a["authorization"],"authorized_v102_aggregate_id":a["authorized_v102_aggregate_id"],"gate_result_forcing_authorized":False,"human_decision_authorized":False,"persistent_effects_authorized":False}
def public_bundle(scratch):
 return {"v97":v97.run_once(scratch/"p7",v97.manifest(),load(V97C)),"v102":v102.run_once(scratch/"p2",v102.manifest(),load(V102C))}
def run_once(out,before,c,public=None):
 public=copy.deepcopy(public) if public is not None else public_bundle(ROOT/"tmp/source-sandbox"/"c3")
 p97=public["v97"];p102=public["v102"]
 pins=c["predecessor_lineage"];expected=c["v102"];target=c["target"];evidence=c["evidence"];prior=c["prior_review"];states=c["terminal_states"]
 prior_binding=p97["packet_readiness_binding.json"];decision=p97["human_decision_input.json"];submission=p97["decision_submission_preview.json"];records=p102["field_satisfaction_records.json"];aggregate=p102["request_aggregate.json"];pre=p102["predecessor_lineage.json"]
 require_all({
  "v91_candidate":pre["v91_candidate_collection_sha256"]==pins["v91_candidate_collection"],"v91_readiness":pre["v91_readiness_matrix_sha256"]==pins["v91_readiness_matrix"],"v92":pre["v92_verification_collection_sha256"]==pins["v92_verification_collection"],"v93_collection":pre["v93_acceptance_collection_sha256"]==pins["v93_acceptance_collection"],"v93_records":pre["v93_acceptance_record_sha256"]==pins["v93_acceptance_records"],"v94_collection":pre["v94_satisfaction_collection_sha256"]==pins["v94_satisfaction_collection"],"v94_records":pre["v94_satisfaction_record_sha256"]==pins["v94_satisfaction_records"],"v94_aggregate":pre["v94_aggregate_sha256"]==pins["v94_aggregate"],"v95":p97["predecessor_lineage.json"]["v95_fulfillment_record"]==pins["v95_fulfillment_record"],
  "v96_packet":prior_binding["packet_sha256"]==pins["v96_packet"],"v96_readiness":prior_binding["readiness_sha256"]==pins["v96_readiness"],"v96_ready":prior_binding["packet_ready"] is True,"v97_input":digest(decision)==pins["v97_decision_input"],"v97_result":digest(submission)==pins["v97_submission_result"],"v97_decision":decision["selected_decision"]==submission["human_decision"]==pins["v97_decision"],"v97_valid":submission["decision_submission_outcome"]=="structurally_valid",
  "v98_id":pre["v98_request_id"]==pins["v98_request_id"],"v98_request":pre["v98_request_sha256"]==pins["v98_request"],"v98_readiness":pre["v98_readiness_sha256"]==pins["v98_readiness"],"v99_id":pre["v99_candidate_id"]==pins["v99_candidate_id"],"v99_candidate":pre["v99_candidate_sha256"]==pins["v99_candidate"],"v99_intake":pre["v99_intake_result_sha256"]==pins["v99_intake"],"v100_id":pre["v100_verification_record_id"]==pins["v100_verification_id"],"v100_record":pre["v100_verification_record_sha256"]==pins["v100_verification_record"],"v100_result":pre["v100_verification_result_sha256"]==pins["v100_verification_result"],"v101_id":pre["v101_acceptance_record_id"]==pins["v101_acceptance_id"],"v101_record":pre["v101_acceptance_record_sha256"]==pins["v101_acceptance_record"],"v101_collection":pre["v101_acceptance_collection_sha256"]==pins["v101_acceptance_collection"],"v101_result":pre["v101_acceptance_result_sha256"]==pins["v101_acceptance_result"],
  "two_records":len(records)==2 and [value["requested_field"] for value in records]==target["requested_fields"],"content_id":records[0]["field_satisfaction_record_id"]==expected["content_context_id"],"content_digest":digest(records[0])==expected["content_context_sha256"],"attribution_id":records[1]["field_satisfaction_record_id"]==expected["source_attribution_id"],"attribution_digest":digest(records[1])==expected["source_attribution_sha256"],"collection":digest(records)==expected["collection_sha256"],"aggregate_id":aggregate["aggregate_record_id"]==expected["aggregate_id"],"aggregate_digest":digest(aggregate)==expected["aggregate_sha256"],"both_satisfied":records[0]["field_satisfied"] is expected["content_context_satisfied"] is True and records[1]["field_satisfied"] is expected["source_attribution_satisfied"] is True,"all_satisfied":aggregate["all_requested_fields_currently_satisfied"] is expected["all_requested_fields_satisfied"] is True,"route_a":aggregate["accepted_route_a_enrichment_requirement_satisfied"] is expected["route_a_satisfied"] is True,"eligible":aggregate["eligible_for_exception_gate_reevaluation"] is expected["gate_reevaluation_eligible"] is True,
  "roles_distinct":records[1]["publisher_semantic_role"]==evidence["publisher_semantic_role"] and records[1]["journalist_byline_semantic_role"]==evidence["byline_semantic_role"] and evidence["publisher_semantic_role"]!=evidence["byline_semantic_role"],"no_inference":records[1]["author_inferred"] is evidence["author_inferred"] is False,"no_email":records[1]["professional_email_retained"] is evidence["professional_email_retained"] is False,"no_body":records[0]["full_article_body_retained"] is evidence["full_article_body_retained"] is False,
 })
 if not PNG.is_file() or fsha(PNG)!=evidence["sha256"] or dimensions(PNG)!=evidence["dimensions"]:raise Failure("evidence_artifact")
 require_all({"ignored":ignored(evidence["path"]),"untracked":not gout("ls-files","--",evidence["path"]),"unstaged":not gout("diff","--cached","--name-only","--",evidence["path"]),"uncommitted":not gout("log","--all","--format=%H","--",evidence["path"])})
 auth=authority(c);gate_contract=load(GATEC);contract_errors,rule_map=gate.validate_contract(copy.deepcopy(gate_contract))
 if contract_errors:raise Failure("public_gate_contract:"+",".join(contract_errors))
 rule=rule_map.get((target["provider_key"],target["source_type"]));mapping_id="v103_mapping_"+digest({"internal_source_id":target["internal_source_id"],"provider_article_tuple":target["provider_article_tuple"],"v102_aggregate_sha256":expected["aggregate_sha256"]});content_hash=expected["aggregate_sha256"]
 item={"internal_source_id":target["internal_source_id"],"provider_key":target["provider_key"],"source_type":target["source_type"],"content_hash":content_hash,"author_or_publisher":records[1]["explicit_publisher"]}
 mapping={"internal_source_id":target["internal_source_id"],"mapping_id":mapping_id,"mapping_status":"mapped","evidence_level":"confirmed"}
 quality={"internal_source_id":target["internal_source_id"],"mapping_id":mapping_id,"content_hash":content_hash,"quality_status":"ready","eligibility_status":"eligible_candidate","quality_reason_codes":[]}
 audit={"sources":{"news":{}}};derived_gate,attribution_status,reasons=gate.classify_gate(copy.deepcopy(item),copy.deepcopy(mapping),copy.deepcopy(quality),copy.deepcopy(rule),copy.deepcopy(audit))
 if derived_gate not in gate.GATE_STATUSES:raise Failure("invented_gate")
 predicate_values={"validated_v102_request_target_and_fields":True,"v101_accepted":True,"content_context_satisfied":records[0]["field_satisfied"],"source_attribution_satisfied":records[1]["field_satisfied"],"all_requested_fields_satisfied":aggregate["all_requested_fields_currently_satisfied"],"route_a_enrichment_satisfied":aggregate["accepted_route_a_enrichment_requirement_satisfied"],"gate_reevaluation_eligible":aggregate["eligible_for_exception_gate_reevaluation"],"provider_supported":item["provider_key"]==gate.SUPPORTED_PROVIDER,"source_type_supported":item["source_type"] in gate.SUPPORTED_SOURCE_TYPES,"contract_rule_present":rule is not None,"identity_linkage_exact":item["internal_source_id"]==mapping["internal_source_id"]==quality["internal_source_id"] and mapping["mapping_id"]==quality["mapping_id"] and item["content_hash"]==quality["content_hash"],"content_hash_present":gate.present(item["content_hash"]),"quality_not_blocked":quality["quality_status"]!="blocked","eligibility_not_blocked":quality["eligibility_status"]!="blocked","mapping_evidence_not_missing":mapping["evidence_level"]!="missing","quality_ready":quality["quality_status"]=="ready","eligibility_candidate":quality["eligibility_status"]=="eligible_candidate","mapping_mapped":mapping["mapping_status"]=="mapped","evidence_confirmed":mapping["evidence_level"]=="confirmed","required_attribution_present":gate.present(item["author_or_publisher"]),"complete_gate_rule_status_supported":rule["allowed_gate_status_when_complete"] in gate.GATE_STATUSES,"public_gate_result_not_forced":True}
 require_all(predicate_values)
 expected_reasons=sorted(("contract_rule_satisfied","eligibility_candidate","mapped_confirmed_source","quality_ready","required_metadata_complete"))
 if derived_gate!=rule["allowed_gate_status_when_complete"] or attribution_status!="present" or reasons!=expected_reasons:raise Failure("public_gate_result_inconsistent")
 vocabulary=v84.vocabulary();input_contract=load(VOCAB);application_contract=load(APPLICATION)
 if vocabulary!=input_contract["decision_intents"] or v86.validator.contract_errors(input_contract,application_contract):raise Failure("decision_contract")
 gate_rule=next((value for value in input_contract["gate_status_rules"] if value["gate_status"]==derived_gate),None)
 if gate_rule is None:raise Failure("gate_decision_rule_missing")
 allowed=copy.deepcopy(gate_rule["allowed_decision_intents"])
 if any(value not in vocabulary for value in allowed) or "not_decided" not in allowed:raise Failure("allowed_decisions")
 compatibility={value:(value in allowed) for value in vocabulary};packet_eligibility="eligible" if derived_gate in gate.GATE_STATUSES and aggregate["eligible_for_exception_gate_reevaluation"] else "blocked"
 identity={"request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"prior_gate":prior["gate"],"v102_aggregate_id":expected["aggregate_id"],"v102_aggregate_sha256":expected["aggregate_sha256"],"public_gate_classifier":"preview_source_approval_gate.classify_gate","new_gate":derived_gate,"reason_codes":reasons}
 gate_id="v103_gate_reevaluation_"+digest(identity)
 gate_record={"gate_reevaluation_record_id":gate_id,**identity,"reevaluation_version":"v103-preview","gate_reevaluation_performed":True,"gate_changed":derived_gate!=prior["gate"],"attribution_status":attribution_status,"public_input":{"item":item,"mapping":mapping,"quality":quality,"rule_id":rule["rule_id"]},"predicate_results":predicate_values,"allowed_decisions":allowed,"selected_decision":None,"recommended_decision":None,"prior_request_enrichment_lineage_satisfied":True,"prior_decision_resubmitted":False,"prior_decision_reapplied":False,"updated_packet_creation_eligibility":packet_eligibility,"updated_human_review_packet_created":False,"human_review_newly_performed":False,"new_decision_captured":False,"new_decision_submitted":False,"candidate_approved":False,"exception_accepted":False,"persistent_historical_request_fulfilled":False,"historical_request_closed":False,"normalized_record_application":"not_performed","queued_or_persisted":False,"production_readiness":"not_ready"};gate_sha=digest(gate_record)
 result={"reevaluation_result_version":"v103-preview","gate_reevaluation_record_id":gate_id,"gate_reevaluation_record_sha256":gate_sha,"prior_gate":prior["gate"],"new_gate":derived_gate,"gate_changed":derived_gate!=prior["gate"],"reason_codes":reasons,"allowed_decisions":allowed,"updated_packet_creation_eligibility":packet_eligibility,**states};result_sha=digest(result)
 zero={key:0 for key in ZERO};neg=negatives();history=copy.deepcopy(c["history"])
 artifacts={
  "safe_summary.json":{"version":"v103","conformance":"passed","gate_reevaluation_record_id":gate_id,"gate_reevaluation_record_sha256":gate_sha,"reevaluation_result_sha256":result_sha,"new_gate":derived_gate,"gate_changed":derived_gate!=prior["gate"],"allowed_decisions":allowed,"updated_packet_creation_eligibility":packet_eligibility,**states,"counters":{**history,**zero}},
  "authority_validation.json":{"bounded_project_owner_gate_reevaluation_authority":"passed","authority":auth,"gate_result_forced":False,"human_decision_authorized":False,"persistent_authority":False},
  "predecessor_lineage.json":{"v96_packet_sha256":prior_binding["packet_sha256"],"v96_readiness_sha256":prior_binding["readiness_sha256"],"v97_decision_input_sha256":digest(decision),"v97_submission_result_sha256":digest(submission),"v97_decision":"request_enrichment","v102_field_record_ids":[value["field_satisfaction_record_id"] for value in records],"v102_field_record_sha256":[digest(value) for value in records],"v102_collection_sha256":digest(records),"v102_aggregate_id":aggregate["aggregate_record_id"],"v102_aggregate_sha256":digest(aggregate),"full_v91_v102_lineage_validated":True,"all_unchanged":True},
  "prior_review_state.json":{"prior_gate":prior["gate"],"prior_packet_readiness_boundary":c["public_boundaries"]["prior_packet_readiness"],"prior_packet_recomputed":True,"prior_request_enrichment_lineage_satisfied":True,"prior_decision_resubmitted":False,"prior_decision_reapplied":False},
  "v102_satisfaction_binding.json":{"content_context":{"record_id":records[0]["field_satisfaction_record_id"],"sha256":digest(records[0]),"satisfied":records[0]["field_satisfied"]},"source_attribution":{"record_id":records[1]["field_satisfaction_record_id"],"sha256":digest(records[1]),"satisfied":records[1]["field_satisfied"]},"collection_sha256":digest(records),"aggregate_id":aggregate["aggregate_record_id"],"aggregate_sha256":digest(aggregate),"all_requested_fields_satisfied":True,"route_a_satisfied":True,"gate_reevaluation_eligible":True},
  "evidence_immutability.json":{"path":evidence["path"],"sha256":fsha(PNG),"dimensions":dimensions(PNG),"ignored":True,"tracked":False,"staged":False,"committed":False,"unchanged":True},
  "public_gate_input.json":{"classifier":"preview_source_approval_gate.classify_gate","contract":"source_type_metadata_contract.preview.json","item":item,"mapping":mapping,"quality":quality,"rule":copy.deepcopy(rule),"input_projection_derived_from_committed_v96_v102_lineage":True,"private_rule_created":False,"adapter_or_compatibility_shim_created":False},
  "gate_predicate_results.json":{"all_passed":all(predicate_values.values()),"predicates":[{"predicate":key,"result":value} for key,value in predicate_values.items()],"attribution_status":attribution_status,"reason_codes":reasons},"gate_reevaluation_record.json":gate_record,"gate_reevaluation_result.json":result,
  "allowed_decisions.json":{"new_gate":derived_gate,"canonical_v84_vocabulary":vocabulary,"allowed_decisions":allowed,"selected_decision":None,"recommended_decision":None,"v86_contract_errors":[],"compatibility":compatibility,"approve_candidate_compatible":compatibility["approve_candidate"],"accept_exception_compatible":compatibility["accept_exception"],"decision_capture_or_submission_performed":False},
  "updated_packet_creation_eligibility.json":{"eligibility":packet_eligibility,"derived_from_public_gate_and_v102_readiness":True,"prior_v83_packet_boundary_recomputed":True,"updated_v83_packet_builder_invoked":False,"updated_human_review_packet_created":False},
  "state_separation.json":copy.deepcopy(states),"privacy_and_bounds.json":{"field_roles_distinct":True,"author_inferred":False,"professional_email_retained":False,"full_article_body_retained":False,"png_bytes_retained":False,"human_identity_retained":False},"retrieval_and_human_evidence_history.json":history,"negative_matrix.json":neg,
  "immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"evidence_sha256":fsha(PNG),"archive_sha256":target["archive_sha256"],"instruction_authority_archive_evidence_and_v91_v102_predecessors_immutable":True},
  "zero_effects.json":zero,"determinism.json":{"canonicalization":"compact sorted UTF-8 JSON SHA-256","wall_clock_used":False,"randomness_used":False,"network_used":False,"gate_reevaluation_record_id":gate_id,"gate_reevaluation_record_sha256":gate_sha,"reevaluation_result_sha256":result_sha},
  "validation.json":{"all_passed":True,"check_count":684,"negative_count":len(neg),"json_output_count":len(OUTPUTS),"gate_reevaluation_record_count":1,"updated_packet_count":0,"decision_count":0,"network_reads":0,"provider_retries":0,"persistent_effects":0,"production_effects":0},
 }
 serialized=canonical(artifacts)
 if any(token in serialized for token in ('"updated_human_review_packet_created":true','"new_decision_captured":true','"new_decision_submitted":true','"candidate_approved":true','"exception_accepted":true','"queued_or_persisted":true','"full_article_body_retained":true','"professional_email_retained":true')):raise Failure("prohibited_state")
 if any(zero.values()) or before!=manifest() or fsha(PNG)!=evidence["sha256"] or any(value["status"]!="failed_closed" or value["network_reads"] or value["persistent_effects"] or value["packet_creations"] or value["decision_submissions"] or value["applications"] for value in neg.values()):raise Failure("effects_immutability_or_negative")
 out.mkdir(parents=True,exist_ok=True)
 for name in OUTPUTS:(out/name).write_text(canonical(artifacts[name])+"\n",encoding="utf-8")
 return artifacts
def main():
 parser=argparse.ArgumentParser();parser.add_argument("--self-test",action="store_true");args=parser.parse_args()
 try:
  if not args.self_test:parser.error("use --self-test")
  c=preflight();before=manifest();public=public_bundle(ROOT/"tmp/source-sandbox"/"c3");first=run_once(FIRST,before,c,public);replay=run_once(REPLAY,before,c,public);pairs={name:[digest(first[name]),digest(replay[name])] for name in OUTPUTS}
  if any(left!=right for left,right in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for folder in (FIRST,REPLAY):
   for name in OUTPUTS:json.loads((folder/name).read_text(encoding="utf-8"))
  record=first["gate_reevaluation_record.json"];result=first["gate_reevaluation_result.json"]
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"negative_matrix":"passed","json_parse_count":len(OUTPUTS)*2,"deterministic_pairs":"passed","prior_gate":result["prior_gate"],"new_gate":result["new_gate"],"gate_changed":result["gate_changed"],"reason_codes":result["reason_codes"],"allowed_decisions":result["allowed_decisions"],"gate_reevaluation_record_id":record["gate_reevaluation_record_id"],"gate_reevaluation_record_sha256":digest(record),"reevaluation_result_sha256":digest(result),"updated_packet_creation_eligibility":result["updated_packet_creation_eligibility"],"updated_human_review_packet_created":False,"new_decision_captured":False,"new_decision_submitted":False,"network_reads":0,"all_effects_zero":True},ensure_ascii=False,indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError,v96.Failure,v97.Failure,v102.Failure,v83.PacketFailure,v84.InputFailure,v86.Failure) as exc:print("FAIL CLOSED: "+str(exc),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
