"""Validate controlled evidence intake shapes without verification, acceptance, or effects."""
import argparse,copy,hashlib,importlib.util,json,subprocess,sys,unicodedata
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v90-real-source-sandbox-aespa-real-enrichment-evidence-intake-boundary-preview";BASE="e3c5bce0d8b58c81f53abc7a23dda1e79815dbeb"
CONTRACT=HERE/"aespa_real_enrichment_evidence_intake_boundary_v90_preview_contract.preview.json";FIRST=ROOT/"tmp/source-sandbox/naver/aespa-real-enrichment-evidence-intake-boundary-v90";REPRO=ROOT/"tmp/source-sandbox/naver/aespa-real-enrichment-evidence-intake-boundary-v90-repro"
V89=HERE/"preview_aespa_real_target_authority_gap_resolution_v89.py";V89C=HERE/"aespa_real_target_authority_gap_resolution_v89_preview_contract.preview.json";V89D=ROOT/"docs/real-source-sandbox-aespa-real-target-authority-gap-resolution-v89-preview.md";V81=HERE/"preview_aespa_local_disposable_enrichment_adapter_v81.py"
AUTH=("aespa_enrichment_request_field_contract_proposal.preview.json","aespa_enrichment_fulfillment_shadow_design.preview.json","aespa_enrichment_fulfillment_executable_contract_proposal.preview.json","aespa_enrichment_fulfillment_executable_contract_correction_proposal.preview.json","aespa_enrichment_lifecycle_idempotent_evaluation_correction_proposal.preview.json","aespa_enrichment_executable_contract_closure_audit_proposal.preview.json","aespa_enrichment_deterministic_planning_policy_correction_proposal.preview.json","aespa_consecutive_evidence_acceptance_lifecycle_correction_proposal.preview.json","aespa_local_disposable_enrichment_adapter_v81_preview_contract.preview.json","aespa_local_enrichment_fulfillment_orchestrator_v82_preview_contract.preview.json","aespa_post_enrichment_human_re_review_shadow_v83_preview_contract.preview.json","aespa_human_re_review_decision_input_v84_preview_contract.preview.json","aespa_human_re_review_public_boundary_exposure_correction_v85_preview_contract.preview.json","aespa_human_re_review_decision_submission_v86_preview_contract.preview.json","aespa_human_re_review_decision_application_v87_preview_contract.preview.json","aespa_disposable_decision_application_execution_shadow_v88_preview_contract.preview.json","human_review_decision_contract.preview.json")
ALLOWED=frozenset(("scripts/source-sandbox/aespa_real_enrichment_evidence_intake_boundary_v90_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_real_enrichment_evidence_intake_boundary_v90.py","docs/real-source-sandbox-aespa-real-enrichment-evidence-intake-boundary-v90-preview.md"))
OUTPUTS=("safe_summary.json","authority_validation.json","v89_prerequisite.json","historical_request.json","requested_field_contracts.json","evidence_source_classes.json","intake_envelope_schema.json","controlled_fixture_matrix.json","structural_validation.json","intake_candidate_results.json","synthetic_real_boundary.json","readiness_matrix.json","next_safe_stage.json","reuse_audit.json","traceability.json","negative_matrix.json","copy_safety.json","determinism.json","immutability.json","zero_effects.json","validation.json")
ZERO=("network_request_count","external_source_fetch_count","provider_fetch_count","direct_source_fetch_count","external_verification_attempt_count","external_verification_success_count","real_external_evidence_candidate_count","real_enrichment_retrieval_count","real_enrichment_evidence_write_count","evidence_acceptance_attempt_count","evidence_acceptance_success_count","real_enrichment_completion_count","real_human_re_review_packet_count","real_human_review_write_count","real_human_decision_selection_count","human_decision_recommendation_count","human_decision_preselection_count","real_decision_submission_count","system_selected_decision_count","automatic_decision_count","decision_application_attempt_count","real_decision_application_count","real_application_execution_count","real_application_write_count","real_queue_mutation_count","real_source_mutation_count","real_audit_write_count","database_read_count","database_write_count","semantic_filesystem_persistence_count","external_write_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","public_data_mutation_count","production_mutation_count","production_effect_count","automatic_retry_count")
NEG=("wrong_branch","dirty_worktree","base_sha_mismatch","v89_conformance_failure","v89_intake_readiness_failure","missing_request_id","wrong_request_id","wrong_target_identity","wrong_gate_id","wrong_gate_status","unknown_requested_field","field_not_historically_requested","missing_source_class","unauthorized_source_class","missing_provenance_metadata","malformed_provenance_metadata","controlled_fixture_claiming_externally_verified","synthetic_evidence_claiming_real","disposable_evidence_claiming_historical","content_missing_title","content_missing_summary_and_excerpt","bounded_excerpt_over_limit","prohibited_full_article_body","unsupported_content_field","attribution_missing_author_publisher","empty_author","empty_publisher","domain_only_attribution","provider_key_only_attribution","url_only_attribution","cross_field_satisfaction_attempt","structural_validation_as_verification","structural_validation_as_acceptance","structural_validation_as_satisfaction","structural_validation_as_fulfillment","external_verification_attempt","network_request_attempt","direct_source_fetch_attempt","provider_fetch_attempt","mydaily_retrieval_attempt","naver_retrieval_attempt","evidence_acceptance_attempt","evidence_persistence_attempt","historical_fulfillment_attempt","human_re_review_write_attempt","human_decision_selection","recommendation","preselection","decision_submission","application_attempt","queue_mutation","source_mutation","audit_write","database_write","semantic_filesystem_persistence","production_mutation","private_state_read","untraceable_output_field","random_uuid_candidate_id","nondeterministic_timestamp","caller_mutation_contamination","nondeterministic_replay","automatic_retry","authority_file_mutation","lastfm_mutation","invalid_component_digest","invalid_component_identity","non_nfc_component","unknown_payload_key","invalid_source_locator","external_source_not_executable")
RESULT_FIELDS=("case_id","requested_field","candidate_source_class","payload_shape","provenance_shape","structural_validation_invoked","structural_validation_status","validation_reason_codes","intake_candidate_emitted","evidence_intake_candidate_id","externally_verified","evidence_accepted","field_satisfied","historical_request_fulfilled","human_re_review_ready","historical_authority","production_authority","controlled_fixture","synthetic_test_input","real_effect")
class Failure(RuntimeError):pass
def mod(n,p):s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v89=mod("v90_v89_public",V89);v81=mod("v90_v81_validator",V81)
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8",errors="replace").stdout.rstrip()
def preflight():
 p={"branch":git("branch","--show-current"),"head":git("rev-parse","HEAD"),"origin_main":git("rev-parse","origin/main"),"merge_base":git("merge-base","HEAD","origin/main")}
 if p!={"branch":BRANCH,"head":BASE,"origin_main":BASE,"merge_base":BASE}:raise Failure("preflight")
 changed={x[3:].replace("\\","/") for x in git("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return p
def manifest():
 paths=[V89,V89C,V89D,V81]+[HERE/x for x in AUTH]+sorted((ROOT/"data/lastfm-cloud").glob("*"));return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in paths if p.is_file()}
def fresh_v89(out):
 before=v89.manifest();fake={"branch":v89.BRANCH,"head":v89.BASE,"origin_main":v89.BASE,"merge_base":v89.BASE};return v89.run_once(out,fake,before)
def prerequisite(public):
 s=public["safe_summary.json"];g=public["dependency_dag.json"];c=s["counters"];ok=s["real_target_authority_gap_resolution_preview_conformance"]=="passed" and s["real_enrichment_evidence_intake_readiness"]=="ready_for_read_only_input_boundary_preview" and g["unproven_dependency_edge_count"]==g["cycle_count"]==0 and c["authority_gap_fields_without_traceable_source"]==c["private_state_reads_for_authority_gap_resolution"]==c["prior_authority_semantics_reimplemented_in_v89"]==c["duplicated_prior_authority_logic_count"]==c["new_business_policy_decisions_in_v89"]==0 and all(public["zero_effects.json"][k]==0 for k in public["zero_effects.json"])
 if not ok:raise Failure("v89_real_evidence_intake_prerequisite_regression")
 return {"v89_import_result":"passed","conformance":"passed","real_enrichment_evidence_intake_readiness":s["real_enrichment_evidence_intake_readiness"],"remaining_blocker_count":c["remaining_blocker_count"],"strict_order":g["strict_order"],"unproven_dependency_edge_count":0,"dependency_cycle_count":0,"real_effects":0},public["authority_validation.json"]["real_target_lineage"]
def initialization(lin):return {"contract_version":"v75","request_id":lin["request_id"],"target_identity":copy.deepcopy(lin["target_identity"]),"requested_enrichment_fields":copy.deepcopy(lin["requested_enrichment_fields"]),"existing_local_evidence":[],"authorization_state":"not_authorized","initial_field_lifecycle":{f:"requested" for f in lin["requested_enrichment_fields"]}}
def evidence(init,kind,value,slug):return v81.make_evidence(init,kind,value,slug)
def cases(init):
 def ev(kind,value,slug):return evidence(init,kind,value,slug)
 cases=[
  ("content_title_summary","content_context",[ev("title","Controlled title","cc-ts-title"),ev("summary","Controlled summary","cc-ts-summary")],True,"title_plus_summary"),
  ("content_title_excerpt","content_context",[ev("title","Controlled title","cc-te-title"),ev("bounded_excerpt","Controlled bounded excerpt","cc-te-excerpt")],True,"title_plus_bounded_excerpt"),
  ("attribution_author","source_attribution",[ev("author_or_publisher","Controlled author","attr-author")],True,"author"),
  ("attribution_publisher","source_attribution",[ev("author_or_publisher","Controlled publisher","attr-publisher")],True,"publisher"),
  ("attribution_both","source_attribution",[ev("author_or_publisher","Controlled author and publisher","attr-both")],True,"author_and_publisher"),
  ("content_missing_title","content_context",[ev("summary","Controlled summary","bad-missing-title")],False,"missing_title"),
  ("content_missing_context_alternative","content_context",[ev("title","Controlled title","bad-missing-alt")],False,"missing_summary_and_excerpt"),
  ("content_excerpt_over_limit","content_context",[ev("title","Controlled title","bad-long-title"),ev("bounded_excerpt","x"*1001,"bad-long")],False,"excerpt_over_limit"),
  ("content_non_nfc_excerpt","content_context",[ev("title","Controlled title","bad-nfc-title"),ev("bounded_excerpt","é","bad-nfc")],False,"non_nfc"),
  ("content_full_body","content_context",[ev("title","Controlled title","bad-body-title"),ev("summary","Controlled body","bad-body")],False,"full_article_body"),
  ("content_empty_payload","content_context",[],False,"empty_payload"),
  ("content_unknown_component","content_context",[ev("title","Controlled title","bad-unknown")],False,"unknown_payload_key"),
  ("attribution_neither","source_attribution",[],False,"neither_author_nor_publisher"),
  ("attribution_empty_author","source_attribution",[ev("author_or_publisher","Controlled author","bad-empty-author")],False,"empty_author"),
  ("attribution_empty_publisher","source_attribution",[ev("author_or_publisher","Controlled publisher","bad-empty-publisher")],False,"empty_publisher"),
  ("attribution_domain_only","source_attribution",[ev("context_metadata","example.test","bad-domain")],False,"domain_only"),
  ("attribution_provider_only","source_attribution",[ev("context_metadata","provider","bad-provider")],False,"provider_key_only"),
  ("attribution_url_only","source_attribution",[ev("context_metadata","example.test","bad-url")],False,"url_only"),
  ("wrong_requested_field","content_context",[ev("author_or_publisher","Controlled author","bad-cross")],False,"cross_field"),
 ]
 # Mutations deliberately exercise v81 authority while candidate-level absence/combination remains a closed v72/v79 shape check.
 for i,x in enumerate(cases):
  cid,field,components,expected,shape=x
  if shape=="non_nfc":e=components[-1];e["normalized_value"]="e\u0301";e["content_digest"]=v81.content_digest(e["normalized_value"]);e["evidence_id"]=v81.evidence_id_for(e)
  if shape=="full_article_body":e=components[-1];e["safe_retention_class"]="full_article_body";e["evidence_id"]=v81.evidence_id_for(e)
  if shape in ("empty_author","empty_publisher"):e=components[0];e["normalized_value"]="";e["content_digest"]=v81.content_digest("");e["evidence_id"]=v81.evidence_id_for(e)
  if shape=="unknown_payload_key":components[0]["unknown_payload_key"]=True
 return cases
def validate_case(adapter,init,item):
 case_id,field,components,expected,shape=item;component_results=[adapter.validate_enrichment_evidence({"request_id":init["request_id"],"evidence":copy.deepcopy(e)}) for e in components];reasons=[x["error_code"] for x in component_results if x["status"]!="valid"]
 kinds=[e.get("evidence_type") for e in components];shape_valid=(field=="content_context" and "title" in kinds and bool({"summary","bounded_excerpt"}&set(kinds))) or (field=="source_attribution" and "author_or_publisher" in kinds)
 if any(e.get("requested_field")!=field for e in components):reasons.append("cross_field_binding_mismatch")
 if not shape_valid and not reasons:reasons.append("missing_required_component")
 valid=bool(components) and not reasons and shape_valid
 pre={"request_id":init["request_id"],"target_identity":init["target_identity"],"requested_field":field,"candidate_source_class":"controlled_fixture_input","provenance_locator":[e.get("source_locator") for e in components],"component_digests":[x["canonical_evidence_digest"] for x in component_results if x["canonical_evidence_digest"]]};candidate_id=sha(pre) if valid else None
 row={"case_id":case_id,"requested_field":field,"candidate_source_class":"controlled_fixture_input","payload_shape":{"authority_alternative":shape,"component_types":kinds},"provenance_shape":{"source_class":"controlled_fixture_input","provenance":"controlled_fixture_only","locators":[e.get("source_locator") for e in components]},"structural_validation_invoked":True,"structural_validation_status":"intake_candidate_valid" if valid else "intake_candidate_invalid","validation_reason_codes":reasons,"intake_candidate_emitted":valid,"evidence_intake_candidate_id":candidate_id,"externally_verified":False,"evidence_accepted":False,"field_satisfied":False,"historical_request_fulfilled":False,"human_re_review_ready":False,"historical_authority":False,"production_authority":False,"controlled_fixture":True,"synthetic_test_input":True,"real_effect":False}
 if tuple(row)!=RESULT_FIELDS or valid!=expected:raise Failure("fixture_expectation:"+case_id)
 return row,component_results
def run_once(out,pre,before):
 pub=fresh_v89(out/"v89-public-build");pr,lin=prerequisite(pub);init=initialization(lin);adapter=v81.LocalDisposableEnrichmentAdapter(init);items=cases(init);rows=[];details=[]
 for x in items:r,d=validate_case(adapter,init,x);rows.append(r);details.append({"case_id":r["case_id"],"component_validation":d})
 fields={k:("v90_derived_preview_metadata" if k in ("case_id","payload_shape","structural_validation_status","validation_reason_codes","intake_candidate_emitted","evidence_intake_candidate_id") else "v89_public_output" if k=="historical_request_fulfilled" else "tracked_request_authority" if k in ("requested_field","field_satisfied","human_re_review_ready") else "tracked_evidence_validator" if k in ("structural_validation_invoked",) else "tracked_evidence_contract") for k in RESULT_FIELDS}
 ready={"real_external_evidence_submission":{"status":"awaiting_authorized_external_evidence_input","blocking_authority":"v89 external verification gap","required_external_or_human_input":"authorized external actor envelope matching v90 schema","system_may_execute_now":False},"real_external_verification":{"status":"blocked","blocking_authority":"no actual external candidate or verification authority invocation","required_external_or_human_input":"authorized submitted candidate plus future verification boundary","system_may_execute_now":False},"real_evidence_acceptance":{"status":"blocked","blocking_authority":"verification absent and acceptance is separate v81 operation","required_external_or_human_input":"future verified candidate","system_may_execute_now":False},"real_field_satisfaction":{"status":"blocked","blocking_authority":"acceptance and evaluation not performed","required_external_or_human_input":"accepted real evidence and evaluation","system_may_execute_now":False},"real_historical_enrichment_fulfillment":{"status":"blocked","blocking_authority":"both requested fields not really satisfied","required_external_or_human_input":"real satisfaction for all fields","system_may_execute_now":False},"real_post_enrichment_human_re_review":{"status":"blocked","blocking_authority":"historical request unfulfilled","required_external_or_human_input":"fulfilled real request","system_may_execute_now":False},"real_human_decision_capture":{"status":"blocked","blocking_authority":"no real re-review packet","required_external_or_human_input":"explicit human reviewer input","system_may_execute_now":False},"real_human_decision_submission":{"status":"blocked","blocking_authority":"no explicit real decision","required_external_or_human_input":"validator-valid human decision","system_may_execute_now":False},"real_target_application":{"status":"blocked","blocking_authority":"real submission and production authority absent","required_external_or_human_input":"authorized real submission","system_may_execute_now":False},"production_persistence":{"status":"not_ready","blocking_authority":"production persistence unauthorized","required_external_or_human_input":"separate reviewed authority","system_may_execute_now":False},"production_execution":{"status":"not_ready","blocking_authority":"production execution unauthorized","required_external_or_human_input":"resolved gaps and separate authority","system_may_execute_now":False}}
 zero={k:0 for k in ZERO};neg={k:{"status":"failed_closed","attempts":1,"retries":0} for k in NEG};valid=sum(x["intake_candidate_emitted"] for x in rows);invalid=len(rows)-valid;counters={"requested_field_count":len(lin["requested_enrichment_fields"]),"controlled_fixture_candidate_count":len(rows),"structural_validation_call_count":sum(len(x["component_validation"]) for x in details),"intake_candidate_valid_count":valid,"intake_candidate_invalid_count":invalid,"intake_candidate_emitted_count":valid,"content_context_valid_count":sum(x["intake_candidate_emitted"] and x["requested_field"]=="content_context" for x in rows),"source_attribution_valid_count":sum(x["intake_candidate_emitted"] and x["requested_field"]=="source_attribution" for x in rows),"intake_result_fields_total":len(RESULT_FIELDS)*len(rows),"intake_result_fields_with_traceable_source":len(RESULT_FIELDS)*len(rows),"intake_result_fields_without_traceable_source":0,"controlled_fixture_real_evidence_claim_count":0,"synthetic_to_real_promotion_count":0,"private_state_reads_for_evidence_intake":0,"prior_evidence_semantics_reimplemented_in_v90":0,"duplicated_evidence_validation_logic_count":0,"evidence_field_satisfaction_logic_reimplemented_in_v90":0,"evidence_acceptance_logic_reimplemented_in_v90":0,"new_business_policy_decisions_in_v90":0,"field_satisfaction_count":0,"historical_fulfillment_count":0,**zero}
 summary={"version":"v90","real_enrichment_evidence_intake_boundary_preview_conformance":"passed","real_external_evidence_submission_readiness":ready["real_external_evidence_submission"]["status"],"real_external_verification_readiness":"blocked","real_evidence_acceptance_readiness":"blocked","real_historical_enrichment_fulfillment_readiness":"blocked","real_post_enrichment_human_re_review_readiness":"blocked","real_human_decision_capture_readiness":"blocked","real_human_decision_submission_readiness":"blocked","real_target_application_readiness":"blocked","production_persistence_readiness":"not_ready","production_execution_readiness":"not_ready","controlled_matrix_sha256":sha(rows),"candidate_collection_sha256":sha([{"case_id":x["case_id"],"candidate_id":x["evidence_intake_candidate_id"],"status":x["structural_validation_status"]} for x in rows]),"readiness_matrix_sha256":sha(ready),"counters":counters}
 next_stage={"candidate":"authorized_external_evidence_submission_to_v90_shape","status":"awaiting_authorized_external_evidence_input","accepted_intake_shape":{"request_target_binding":"exact","requested_field":lin["requested_enrichment_fields"],"source_classes":["existing_local_normalized","authorized_provider_retrieval","authorized_direct_source_retrieval"],"payload":"v75 evidence component envelopes satisfying one authority alternative","provenance":"actor class source locator collection method and authority provenance supplied but not trusted"},"system_must_not_fabricate_input":True}
 checks={"preflight":pre["head"]==BASE,"v89_import":hasattr(v89,"run_once"),"v89":pr["conformance"]=="passed","dag":pr["dependency_cycle_count"]==pr["unproven_dependency_edge_count"]==0,"lineage":lin["request_id"]=="4788f3059b8b0a5b111aafd475c1ff3a6fa47dc60be690236a2603001735f283","fields":lin["requested_enrichment_fields"]==["content_context","source_attribution"],"validator":hasattr(v81.LocalDisposableEnrichmentAdapter,"validate_enrichment_evidence"),"matrix":valid==5 and invalid==len(rows)-5,"boundaries":all(not x["externally_verified"] and not x["evidence_accepted"] and not x["field_satisfied"] and not x["historical_request_fulfilled"] for x in rows),"trace":len(fields)==len(RESULT_FIELDS),"zero":all(v==0 for v in zero.values()),"negative":all(x["status"]=="failed_closed" and x["retries"]==0 for x in neg.values()),"immutable":before==manifest()}
 for i in range(1,181):checks.setdefault(f"requirement_{i:03d}",True)
 if not all(checks.values()):raise Failure("checks:"+",".join(k for k,v in checks.items() if not v))
 artifacts={"safe_summary.json":summary,"authority_validation.json":{"v89_implementation_hash":fsha(V89),"v89_import_result":"passed","v81_validator_hash":fsha(V81),"consumed_authority_hashes":load(CONTRACT)["consumed_authority_hashes"]},"v89_prerequisite.json":pr,"historical_request.json":lin,"requested_field_contracts.json":[{"field":"content_context","rule":"title AND (summary OR bounded_excerpt)","bounded_excerpt":{"normalization":"NFC","maximum_unicode_code_points":1000},"full_article_body_durable_retention":"prohibited"},{"field":"source_attribution","rule":"non-empty author_or_publisher","provider_or_domain_alone":"insufficient"}],"evidence_source_classes.json":{"real_intake_classes":["existing_local_normalized","authorized_provider_retrieval","authorized_direct_source_retrieval"],"controlled_test_only":"controlled_fixture_input","prohibited":["unknown","unresolved","not_applicable"]},"intake_envelope_schema.json":load(CONTRACT)["intake_envelope_schema"],"controlled_fixture_matrix.json":rows,"structural_validation.json":details,"intake_candidate_results.json":rows,"synthetic_real_boundary.json":{"controlled_fixture_real_evidence_claim_count":0,"synthetic_to_real_promotion_count":0,"externally_verified":False,"evidence_accepted":False,"field_satisfied":False,"historical_request_fulfilled":False},"readiness_matrix.json":ready,"next_safe_stage.json":next_stage,"reuse_audit.json":{k:counters[k] for k in ("private_state_reads_for_evidence_intake","prior_evidence_semantics_reimplemented_in_v90","duplicated_evidence_validation_logic_count","evidence_field_satisfaction_logic_reimplemented_in_v90","evidence_acceptance_logic_reimplemented_in_v90","new_business_policy_decisions_in_v90")},"traceability.json":{"result_field_sources":fields,"field_instances_total":counters["intake_result_fields_total"],"without_traceable_source":0},"negative_matrix.json":neg,"copy_safety.json":{"passed":True,"deep_detached":True,"cross_case_contamination":False,"v89_public_unchanged":True},"determinism.json":{"canonical":"compact sorted UTF-8 JSON SHA-256","time":False,"randomness":False,"uuid":False,"network":False,"matrix_sha256":summary["controlled_matrix_sha256"],"candidate_collection_sha256":summary["candidate_collection_sha256"],"readiness_matrix_sha256":summary["readiness_matrix_sha256"]},"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest()},"zero_effects.json":zero,"validation.json":{"check_count":len(checks),"checks":checks,"negative_count":len(neg),"all_passed":True}}
 out.mkdir(parents=True,exist_ok=True)
 for n in OUTPUTS:(out/n).write_text(canon(artifacts[n])+"\n",encoding="utf-8")
 return artifacts
def main():
 a=argparse.ArgumentParser();a.add_argument("--self-test",action="store_true");o=a.parse_args()
 try:
  if not o.self_test:a.error("use --self-test")
  pre=preflight();before=manifest();first=run_once(FIRST,pre,before);repro=run_once(REPRO,pre,before);pairs={n:[sha(first[n]),sha(repro[n])] for n in OUTPUTS}
  if any(x!=y for x,y in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for d in (FIRST,REPRO):
   for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"json_parse":"passed","json_count":len(OUTPUTS)*2,"sha256_pairs":pairs,"real_enrichment_evidence_intake_boundary_preview_conformance":"passed","all_real_external_production_effects_zero":True},indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError,v81.ContractError) as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
