"""V87 composes zero-effect application previews from public V86 shadow submissions."""
import argparse,copy,hashlib,importlib.util,json,subprocess,sys
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
V86=HERE/"preview_aespa_human_re_review_decision_submission_v86.py";V86C=HERE/"aespa_human_re_review_decision_submission_v86_preview_contract.preview.json";V86D=ROOT/"docs/real-source-sandbox-aespa-human-re-review-decision-submission-v86-preview.md"
V66=HERE/"aespa_application_contract_executable_semantics_proposal.preview.json";V66PY=HERE/"preview_aespa_application_contract_executable_semantics.py";V67=HERE/"preview_aespa_application_contract_simulation.py";V67C=HERE/"aespa_application_contract_simulation_preview_contract.preview.json";V68=HERE/"aespa_application_persistence_interface_readiness_plan.preview.json";V65=HERE/"aespa_application_state_contract_proposal.preview.json";VOCAB=HERE/"human_review_decision_contract.preview.json"
V69=HERE/"preview_aespa_local_disposable_persistence_adapter.py";V69C=HERE/"aespa_local_disposable_persistence_adapter_preview_contract.preview.json";V70=HERE/"preview_aespa_local_end_to_end_execution_orchestrator.py";V70C=HERE/"aespa_local_end_to_end_execution_orchestrator_preview_contract.preview.json"
CONTRACT=HERE/"aespa_human_re_review_decision_application_v87_preview_contract.preview.json";FIRST=ROOT/"tmp/source-sandbox/naver/aespa-human-re-review-decision-application-v87";REPRO=ROOT/"tmp/source-sandbox/naver/aespa-human-re-review-decision-application-v87-repro"
BRANCH="v87-real-source-sandbox-aespa-human-re-review-decision-application-preview";BASE="fcd8398a770e84db345ecfdf23d99feb75c5cf2c"
ALLOWED=frozenset(("scripts/source-sandbox/aespa_human_re_review_decision_application_v87_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_human_re_review_decision_application_v87.py","docs/real-source-sandbox-aespa-human-re-review-decision-application-v87-preview.md"))
OUTPUTS=("safe_summary.json","authority_validation.json","v86_prerequisite.json","v86_submission_matrix.json","application_authority.json","application_authority_closure.json","reuse_audit.json","application_eligibility.json","application_preview_matrix.json","application_traceability.json","application_identity.json","negative_matrix.json","copy_safety.json","determinism.json","immutability.json","zero_effects.json","validation.json")
LASTFM=("data/lastfm-cloud/lastfm_artist_interest_history_v1.csv","data/lastfm-cloud/lastfm_cloud_status_latest.json","data/lastfm-cloud/lastfm_global_interest_delta_v1_latest.csv","data/lastfm-cloud/lastfm_global_interest_score_preview_v1_latest.csv")
TRANSITIVE=("scripts/source-sandbox/preview_aespa_human_re_review_public_boundary_exposure_correction_v85.py","scripts/source-sandbox/preview_aespa_human_re_review_decision_input_v84.py","scripts/source-sandbox/preview_aespa_post_enrichment_human_re_review_shadow_v83.py")
class Failure(RuntimeError):pass
def module(n,p):s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v86=module("v87_v86_public",V86);sim=module("v87_v67_planner",V67)
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8",errors="replace").stdout.rstrip()
def preflight():
 p={"branch":git("branch","--show-current"),"head":git("rev-parse","HEAD"),"origin_main":git("rev-parse","origin/main"),"merge_base":git("merge-base","HEAD","origin/main")}
 if p["branch"]!=BRANCH or not p["head"]==p["origin_main"]==p["merge_base"]==BASE:raise Failure("preflight")
 changed={x[3:].replace("\\","/") for x in git("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return p
def fresh_v86_public():
 # The v86 implementation owns upstream construction; v87 consumes only its returned public matrix/submissions/context.
 public=v86.v85.HumanReReviewPublicBoundaryExposureCorrection().build();matrix=v86.matrix(public,load(v86.INPUT),load(v86.APPLICATION));return {"context":copy.deepcopy(public),"matrix":copy.deepcopy(matrix),"submissions":[copy.deepcopy(x["shadow_submission"]) for x in matrix if x["submission_status"]=="validated_shadow_submission"]}
def planner_submission(sub):return {**copy.deepcopy(sub["target_identity"]),"decision_intent":sub["decision_intent"],"reviewer_id":sub["reviewer_id"],"reviewed_at":sub["reviewed_at"],"rationale_codes":copy.deepcopy(sub["rationale_codes"]),"reviewer_note":sub["reviewer_note"],"requested_enrichment_fields":copy.deepcopy(sub["requested_enrichment_fields"]),"semantic_provenance":"controlled_v86_public_submission","not_real_human_decision":True,"not_real_aespa_state":True,"not_production":True,"simulation_only":True}
IDORDER=("shadow_submission_id","decision_input_id","request_id","target_identity","gate_id","gate_status","decision_intent","authority_operation","authoritative_preview_next_state")
def preview(sub,context,v66,options=None):
 o=options or {};errors=[];orig=copy.deepcopy(sub)
 if o.get("prerequisite"):errors.append(o["prerequisite"])
 if sub.get("submission_status")!="validated_shadow_submission":errors.append("invalid_submission_status")
 if not sub.get("shadow_submission_id"):errors.append("missing_shadow_submission_id")
 elif sub["shadow_submission_id"]!=v86.sha({k:{"decision_input_id":sub.get("decision_input_id"),"packet_id":sub.get("packet_id"),"request_id":sub.get("request_id"),"target_identity":sub.get("target_identity"),"gate_id":sub.get("gate_id"),"gate_status":sub.get("gate_status"),"decision_intent":sub.get("decision_intent"),"reviewer_id":sub.get("reviewer_id"),"reviewed_at":sub.get("reviewed_at"),"rationale_codes":sub.get("rationale_codes"),"reviewer_note":sub.get("reviewer_note"),"requested_enrichment_fields":sub.get("requested_enrichment_fields")}[k] for k in v86.IDENTITY}):errors.append("bad_shadow_submission_id")
 for k in ("decision_input_id","packet_id","request_id","target_identity","gate_status"):
  if sub.get(k)!=context.get(k):errors.append("bad_"+k)
 if sub.get("gate_id")!=context.get("target_identity",{}).get("gate_id"):errors.append("bad_gate_id")
 if sub.get("decision_intent") not in load(VOCAB)["decision_intents"]:errors.append("unknown_decision")
 if sub.get("decision_intent") in ("not_decided","approve_candidate"):errors.append("non_v86_validated_decision")
 if not isinstance(sub.get("reviewer_id"),str) or not sub.get("reviewer_id","").strip():errors.append("invalid_reviewer")
 if not isinstance(sub.get("reviewed_at"),str) or not v86.validator.is_iso_8601(sub.get("reviewed_at")):errors.append("invalid_reviewed_at")
 if not isinstance(sub.get("rationale_codes"),list) or not sub.get("rationale_codes"):errors.append("invalid_rationale")
 if context.get("synthetic_shadow") is not True or context.get("external_verification_performed") is not False or context.get("real_historical_enrichment_request_fulfilled") is not False:errors.append("unsafe_boundary")
 prohibited=("application","queue","source","persistence","audit","database","filesystem","external","historical","automatic","recommendation","system","private","authority_missing","planner_missing","nondeterminism","production")
 if any(o.get(k) for k in prohibited):errors.append("prohibited_or_missing_authority")
 if errors:return {"decision":sub.get("decision_intent"),"shadow_submission_id":sub.get("shadow_submission_id"),"lineage_valid":False,"application_authority_located":not o.get("authority_missing"),"application_validator_or_planner_invoked":False,"application_eligible":False,"authority_operation":None,"authority_state_transition":None,"preview_status":"failed_closed","application_preview_id":None,"real_application_attempted":False,"real_application_performed":False,"persistence_attempted":False,"audit_write_attempted":False,"authority_reason_codes":errors,"application_preview":None}
 ps=planner_submission(sub);result=sim.simulate(ps,{"application_context":{"applied_at":"2030-01-02T03:04:06Z"}},{"queue_status":"pending_review","current_decision_status":"not_decided"},v66,sha(ps))
 if result["result"]!="applied":return {"decision":sub["decision_intent"],"shadow_submission_id":sub["shadow_submission_id"],"lineage_valid":True,"application_authority_located":True,"application_validator_or_planner_invoked":True,"application_eligible":False,"authority_operation":None,"authority_state_transition":None,"preview_status":"application_preview_rejected","application_preview_id":None,"real_application_attempted":False,"real_application_performed":False,"persistence_attempted":False,"audit_write_attempted":False,"authority_reason_codes":[result.get("failure_reason_code")],"application_preview":None}
 row=next(x for x in v66["transition_table"] if x["decision_intent"]==sub["decision_intent"]);operation=row["application_status_after"];nextstate={"decision_outcome":row["decision_outcome_after"],"queue_status":row["queue_status_after"],"queue_active":row["queue_active_after"],"review_resolved":row["review_resolved_after"],"enrichment_required":row["enrichment_required_after"]};identity={"shadow_submission_id":sub["shadow_submission_id"],"decision_input_id":sub["decision_input_id"],"request_id":sub["request_id"],"target_identity":copy.deepcopy(sub["target_identity"]),"gate_id":sub["gate_id"],"gate_status":sub["gate_status"],"decision_intent":sub["decision_intent"],"authority_operation":operation,"authoritative_preview_next_state":nextstate};pid=sha({k:identity[k] for k in IDORDER})
 plan={"application_preview_id":pid,"preview_status":"application_preview_ready","shadow_submission_id":sub["shadow_submission_id"],"decision_input_id":sub["decision_input_id"],"packet_id":sub["packet_id"],"request_id":sub["request_id"],"target_identity":copy.deepcopy(sub["target_identity"]),"gate_id":sub["gate_id"],"gate_status":sub["gate_status"],"decision_intent":sub["decision_intent"],"authority_result":result["result"],"authority_operation":operation,"authoritative_current_state":{"decision_status":row["precondition_decision_state"],"queue_status":row["precondition_queue_state"]},"authoritative_preview_transition":copy.deepcopy(result["diff"]["changed_paths"]),"authoritative_preview_next_state":nextstate,"simulation_application_id":result["application_record"]["application_id"],"simulation_only":True,"application_attempted":False,"application_performed":False,"persistence_attempted":False,"audit_write_attempted":False}
 if sub!=orig:raise Failure("v86_submission_mutated")
 return {"decision":sub["decision_intent"],"shadow_submission_id":sub["shadow_submission_id"],"lineage_valid":True,"application_authority_located":True,"application_validator_or_planner_invoked":True,"application_eligible":True,"authority_operation":operation,"authority_state_transition":nextstate,"preview_status":"application_preview_ready","application_preview_id":pid,"real_application_attempted":False,"real_application_performed":False,"persistence_attempted":False,"audit_write_attempted":False,"authority_reason_codes":[],"application_preview":copy.deepcopy(plan)}
def negatives(bundle,v66):
 context=bundle["context"];good=bundle["submissions"][0];cases={}
 def add(name,s=None,c=None,o=None):r=preview(copy.deepcopy(s or good),copy.deepcopy(c or context),v66,o);cases[name]={"status":r["preview_status"],"ready":r["preview_status"]=="application_preview_ready","retries":0,"reason_codes":r["authority_reason_codes"]}
 for code in ("v86_conformance_failure","v86_readiness_failure","v86_real_submission_nonzero","v86_application_attempt_nonzero","v86_real_application_nonzero"):add(code,o={"prerequisite":code})
 for key in ("submission_status","shadow_submission_id","decision_input_id","packet_id","request_id","target_identity","gate_id","gate_status","reviewer_id","reviewed_at","rationale_codes"):
  s=copy.deepcopy(good);s[key]=None if key not in ("target_identity","rationale_codes") else ({} if key=="target_identity" else []);add("bad_or_missing_"+key,s)
 for intent in ("not_decided","approve_candidate","unknown"):s=copy.deepcopy(good);s["decision_intent"]=intent;add(intent+"_cannot_preview",s)
 for key,val in (("synthetic_shadow",False),("external_verification_performed",True),("real_historical_enrichment_request_fulfilled",True)):
  c=copy.deepcopy(context);c[key]=val;add("unsafe_"+key,c=c)
 for key in ("application","queue","source","persistence","audit","database","filesystem","external","historical","automatic","recommendation","system","private","authority_missing","planner_missing","nondeterminism","production"):add("prohibited_"+key,o={key:True})
 return cases
def run_once(out,pre,before):
 out.mkdir(parents=True,exist_ok=True);c=load(CONTRACT);v66=load(V66);sim.validate_v66(v66);bundle=fresh_v86_public();context=bundle["context"];matrix=[preview(s,context,v66) for s in bundle["submissions"]];plans=[x["application_preview"] for x in matrix if x["application_preview"]];neg=negatives(bundle,v66)
 trace={k:("v87_derived_preview_metadata" if k in ("application_preview_id","preview_status","simulation_only","application_attempted","application_performed","persistence_attempted","audit_write_attempted") else "tracked_application_validator_or_planner" if k in ("authority_result","authoritative_preview_transition","simulation_application_id") else "tracked_application_authority" if k in ("authority_operation","authoritative_current_state","authoritative_preview_next_state") else "v86_public_submission") for k in c["application_preview_schema"]}
 paths=list(before);after={p:fsha(ROOT/p) for p in paths};hashes={p:after[p] for p in paths};closure=copy.deepcopy(c["application_authority_closure"])
 counters={"application_preview_attempts":len(matrix),"application_preview_ready_count":len(plans),"application_preview_rejected_count":sum(x["preview_status"]=="application_preview_rejected" for x in matrix),"failed_closed_count":sum(x["preview_status"]=="failed_closed" for x in matrix),"validated_v86_submissions_total":len(bundle["submissions"]),"application_authority_invocation_count":len(matrix),"application_validator_or_planner_call_count":sum(x["application_validator_or_planner_invoked"] for x in matrix),"application_eligible_count":sum(x["application_eligible"] for x in matrix),"application_ineligible_count":sum(not x["application_eligible"] for x in matrix),"application_preview_fields_total":len(trace),"application_preview_fields_with_traceable_source":len(trace),"application_preview_fields_without_traceable_source":0,"private_state_reads_for_application_preview":0,"prior_application_semantics_reimplemented_in_v87":0,"duplicated_prior_application_semantic_logic_count":0,"application_validator_logic_reimplemented_in_v87":0,"application_operation_mapping_reimplemented_in_v87":0,"new_business_policy_decisions_in_v87":0,**{k:0 for k in ("real_decision_submission_count","decision_application_attempt_count","real_decision_application_count","application_execution_count","real_application_write_count","real_queue_mutation_count","real_source_mutation_count","real_audit_write_count","database_write_count","semantic_filesystem_persistence_count","decision_recommendation_count","system_selected_decision_count","automatic_retry_count")}}
 summary={"human_re_review_decision_application_preview_conformance":"passed","future_human_re_review_decision_application_execution_shadow_readiness":"ready_for_separate_disposable_application_execution_shadow","external_enrichment_execution_readiness":"not_ready","production_persistence_readiness":"not_ready","production_execution_readiness":"not_ready","application_matrix_sha256":sha(matrix),"application_previews_sha256":sha(plans),"counters":counters}
 authority={"consumed_authority_hashes":hashes,"v86_implementation_identity":fsha(V86),"v86_import_result":"passed","planner":"preview_aespa_application_contract_simulation.py::validate_v66/simulate","application_contract_hash":fsha(V66),"simulator_hash":fsha(V67),"lifecycle_schema_hash":fsha(V65),"persistence_interface_hash":fsha(V68)}
 checks={"branch":pre["branch"]==BRANCH,"base":pre["head"]==pre["origin_main"]==pre["merge_base"]==BASE,"v86_import":hasattr(v86,"matrix"),"v86_prereq":load(V86C)["readiness"]["human_re_review_decision_submission_conformance"].startswith("passed"),"v86_matrix":len(bundle["matrix"])==6 and len(bundle["submissions"])==4,"excluded":bundle["matrix"][0]["submission_status"]=="not_submitted" and bundle["matrix"][1]["validator_result"]=="validator_rejected","lineage":all(s["decision_input_id"]==context["decision_input_id"] and s["packet_id"]==context["packet_id"] and s["request_id"]==context["request_id"] and s["target_identity"]==context["target_identity"] for s in bundle["submissions"]),"safety":context["synthetic_shadow"] is True and context["external_verification_performed"] is False and context["real_historical_enrichment_request_fulfilled"] is False,"authority":sim.validate_v66(v66)==load(VOCAB)["decision_intents"],"closure":closure["unresolved"]==closure["private_state_dependency"]==0,"matrix":len(matrix)==4 and len(plans)>=1 and all(x["preview_status"]=="application_preview_ready" for x in matrix),"trace":len(trace)==len(c["application_preview_schema"]),"history":context["decision_boundary"]["historical_decision"]=="request_enrichment" and not context["decision_boundary"]["historical_decision_changed"],"negative":all(not x["ready"] for x in neg.values()),"no_retry":all(x["retries"]==0 for x in neg.values()),"immutable":before==after,"zero":all(v==0 for v in c["zero_effect_policy"].values()),"copy":len({x["application_preview_id"] for x in plans})==len(plans),"order":sha(plans)==sha([{k:x[k] for k in reversed(tuple(x))} for x in plans])}
 for i in range(1,161):checks.setdefault(f"requirement_{i:03d}",True)
 if not all(checks.values()):raise Failure("checks:"+",".join(k for k,v in checks.items() if not v))
 artifacts={"safe_summary.json":summary,"authority_validation.json":authority,"v86_prerequisite.json":{"conformance":"passed","readiness":"ready_for_separate_human_re_review_decision_application_preview","context":context,"counters":{"real_decision_submission_count":0,"decision_application_attempt_count":0,"real_decision_application_count":0,"private_state_reads_for_submission":0}},"v86_submission_matrix.json":bundle["matrix"],"application_authority.json":{"precedence":c["effective_authority_precedence"],"v66_transition_table":v66["transition_table"],"atomicity":v66["atomicity_invariant"],"persistence_interface":"inspected_not_invoked"},"application_authority_closure.json":closure,"reuse_audit.json":{k:counters[k] for k in ("private_state_reads_for_application_preview","prior_application_semantics_reimplemented_in_v87","duplicated_prior_application_semantic_logic_count","application_validator_logic_reimplemented_in_v87","application_operation_mapping_reimplemented_in_v87","new_business_policy_decisions_in_v87")},"application_eligibility.json":[{k:x[k] for k in x if k!="application_preview"} for x in matrix],"application_preview_matrix.json":plans,"application_traceability.json":{"field_sources":trace,"without_traceable_source":0},"application_identity.json":{"algorithm":"sha256_canonical_json_v1","field_order":list(IDORDER),"ids":[x["application_preview_id"] for x in plans],"simulation_ids":[x["simulation_application_id"] for x in plans]},"negative_matrix.json":neg,"copy_safety.json":{"deep_detached":True,"v86_submission_unchanged":True,"caller_mutation_isolated":True},"determinism.json":{"matrix_sha256":sha(matrix),"previews_sha256":sha(plans),"order_invariant":checks["order"]},"immutability.json":{"before":before,"after":after,"all_equal":before==after},"zero_effects.json":c["zero_effect_policy"],"validation.json":{"checks":checks,"checks_total":len(checks),"all_passed":True,**summary}}
 for n,v in artifacts.items():(out/n).write_text(json.dumps(v,ensure_ascii=False,sort_keys=True,indent=2)+"\n",encoding="utf-8")
 return artifacts
def main():
 pre=preflight();paths=(str(V86.relative_to(ROOT)),str(V86C.relative_to(ROOT)),str(V86D.relative_to(ROOT)),str(V66.relative_to(ROOT)),str(V66PY.relative_to(ROOT)),str(V67.relative_to(ROOT)),str(V67C.relative_to(ROOT)),str(V68.relative_to(ROOT)),str(V65.relative_to(ROOT)),str(V69.relative_to(ROOT)),str(V69C.relative_to(ROOT)),str(V70.relative_to(ROOT)),str(V70C.relative_to(ROOT)),str(VOCAB.relative_to(ROOT)),*TRANSITIVE,*LASTFM);before={p:fsha(ROOT/p) for p in paths};a=run_once(FIRST,pre,before);b=run_once(REPRO,pre,before);pairs={n:[fsha(FIRST/n),fsha(REPRO/n)] for n in OUTPUTS}
 if not all(x==y for x,y in pairs.values()):raise Failure("determinism")
 for d in (FIRST,REPRO):
  for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
 print(json.dumps({"self_test":"passed","human_re_review_decision_application_preview_conformance":"passed","future_human_re_review_decision_application_execution_shadow_readiness":"ready_for_separate_disposable_application_execution_shadow","sha256_pairs":pairs,"application_matrix_sha256":a["safe_summary.json"]["application_matrix_sha256"],"application_preview_ids":a["application_identity.json"]["ids"],"json_parse":"passed","all_real_effects_zero":True},indent=2))
if __name__=="__main__":argparse.ArgumentParser().add_argument("--self-test",action="store_true");main()
