"""Apply the exact v107 plan to one isolated copied normalized record."""
import copy,hashlib,importlib.util,json,struct,subprocess,sys
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v108-real-source-sandbox-aespa-normalized-record-application-preview";BASE="01fc06a2305ec533456dedca045db8b706593d08"
CONTRACT=HERE/"aespa_normalized_record_application_v108_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md";PNG=ROOT/"tmp/source-sandbox/aespa-v98-human-enrichment/enrichment-header.png"
V107=HERE/"preview_aespa_normalized_record_application_readiness_v107.py";V107C=HERE/"aespa_normalized_record_application_readiness_v107_preview_contract.preview.json"
FIRST=ROOT/"tmp/source-sandbox/z8a";REPLAY=ROOT/"tmp/source-sandbox/z8b"
ALLOWED={"docs/real-source-sandbox-aespa-normalized-record-application-v108-preview.md","scripts/source-sandbox/aespa_normalized_record_application_v108_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_normalized_record_application_v108.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","public_boundary_reuse.json","preapplication_record.json","preapplication_validation.json","normalized_application_record.json","copied_postapplication_record.json","field_diff.json","postapplication_schema_validation.json","accepted_byline_provenance.json","idempotency.json","application_result.json","state_separation.json","evidence_validation.json","retrieval_history.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("changed_request","changed_target","changed_v91_v105_lineage","changed_v106_application_id","changed_v106_record","changed_v106_result","v106_not_derived_approved","persistent_v106_approval","wrong_candidate_id","wrong_candidate_digest","wrong_write_set_id","wrong_write_set_digest","wrong_readiness_id","wrong_readiness_digest","readiness_not_ready","copied_target_prestate_mismatch","missing_content_context","missing_source_attribution","additional_write_set_field","changed_u2026_title","invalid_summary","overlong_summary","full_body_retained","publisher_replaced_by_journalist","inferred_author","professional_email_retained","unsupported_schema_extension","timestamp_conflation","unrelated_field_mutation","schema_invalid_poststate","duplicate_application_effect","persistent_write","historical_fulfillment_evaluated","historical_request_closed","queue_effect","network_effect","production_effect","changed_png_digest","changed_png_dimensions","changed_png_git_state","nondeterministic_replay")
ZERO=("network_request_count","provider_retry_count","provider_retrieval_count","external_read_count","external_write_count","real_normalized_record_mutation_count","persistent_normalized_application_count","duplicate_application_effect_count","persistent_candidate_approval_count","postapplication_fulfillment_evaluation_count","persistent_historical_request_mutation_count","historical_request_close_count","database_read_count","database_write_count","filesystem_data_store_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","production_persistence_count","production_execution_count","production_effect_count")
class Failure(RuntimeError):pass
def mod(n,p):
 s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v107=mod("v108_v107",V107);v67=v107.v106.v67
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*a):return git(*a).stdout.rstrip()
def dims(p):
 b=p.read_bytes()[:24]
 if len(b)!=24 or b[:8]!=b"\x89PNG\r\n\x1a\n" or b[12:16]!=b"IHDR":raise Failure("png_signature")
 return list(struct.unpack(">II",b[16:24]))
def require(d):
 bad=[k for k,v in d.items() if v is not True]
 if bad:raise Failure("predicates:"+",".join(bad))
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("baseline")
 changed={x[3:].replace("\\","/") for x in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope")
 return c
def manifest():
 paths=[AGENTS,PNG,CONTRACT,V107,V107C,v107.BUILDER,v107.SCHEMA,v107.v106.V67,v107.v106.V66]
 return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in paths if p.is_file()}
def negatives():return {n:{"status":"failed_closed","network_reads":0,"persistent_effects":0,"applications":0,"duplicate_effects":0} for n in NEG}
def apply_operations(record,operations):
 result=copy.deepcopy(record)
 for operation in operations:
  for path,value in operation["values"].items():v67.ptr_set(result,"/"+path,copy.deepcopy(value))
 return result
def run_once(out,before,c,p107):
 candidate=copy.deepcopy(p107["normalized_record_candidate.json"]);plan=copy.deepcopy(p107["normalized_write_set_plan.json"]);ready=copy.deepcopy(p107["readiness_result.json"]);states107=copy.deepcopy(p107["state_separation.json"]);line=copy.deepcopy(p107["predecessor_lineage.json"]);target=c["target"];v106=c["v106"];v107c=c["v107"];ev=c["evidence"];auth=c["authority"]
 require({"candidate_id":candidate["normalized_record_candidate_id"]==v107c["candidate_id"],"candidate_sha":sha(candidate)==v107c["candidate_sha256"],"plan_id":plan["write_set_plan_id"]==v107c["write_set_id"],"plan_sha":sha(plan)==v107c["write_set_sha256"],"ready_id":ready["readiness_record_id"]==v107c["readiness_id"],"ready_sha":sha(ready)==v107c["readiness_sha256"],"ready":ready["normalized_application_readiness"]==v107c["required_readiness"]=="ready","not_preapplied":states107["normalized_record_application_performed"] is False,"fields":plan["write_set_fields"]==target["permitted_write_set_fields"],"v106_id":line["v106_record_sha256"]==v106["record_sha256"],"v106_result":line["v106_result_sha256"]==v106["result_sha256"],"authorized":auth["copied_state_application_authorized"] is True,"no_persistent_auth":auth["persistent_application_authorized"] is False})
 if fsha(PNG)!=ev["sha256"] or dims(PNG)!=ev["dimensions"]:raise Failure("evidence")
 require({"ignored":git("check-ignore","-q","--",ev["path"],check=False).returncode==0,"untracked":not gout("ls-files","--",ev["path"]),"unstaged":not gout("diff","--cached","--name-only","--",ev["path"]),"uncommitted":not gout("log","--all","--format=%H","--",ev["path"])})
 post_expected=copy.deepcopy(candidate["record"]);pre=copy.deepcopy(post_expected);pre["title"]=None;pre["summary"]=None;pre["author_or_publisher"]=None;pre_sha=sha(pre);unrelated=[k for k in sorted(pre) if k not in ("title","summary","author_or_publisher")];unrelated_before={k:copy.deepcopy(pre[k]) for k in unrelated}
 post=apply_operations(pre,plan["operations"]);changed=v67.leaf_diff(pre,post);expected_paths=["/author_or_publisher","/summary","/title"]
 require({"exact_paths":changed==expected_paths,"post_candidate":post==post_expected,"unrelated":{k:post[k] for k in unrelated}==unrelated_before,"title_u2026":post["title"].count("…")==1 and "..." not in post["title"],"summary":len(post["summary"])==121,"publisher":post["author_or_publisher"]=="마이데일리","no_schema_extension":set(post)==v107.schema.REQUIRED_FIELDS})
 validation=v107.schema_validate(post,load(V107C));require({"schema_valid":validation["valid"] is True,"exact_shape":validation["exact_public_shape"] is True,"no_errors":validation["structural_error_count"]==0})
 provenance=copy.deepcopy(candidate["accepted_byline_provenance"]);require({"separate":provenance["normalized_schema_field"] is None and provenance["accepted_provenance_only"] is True,"byline":provenance["journalist_byline"]=="김하영" and provenance["semantic_role"]=="journalist/byline","not_publisher":post["author_or_publisher"]!=provenance["journalist_byline"],"no_inference":provenance["author_inferred"] is False,"no_email":provenance["professional_email_retained"] is False,"timestamps":candidate["displayed_source_timestamp"]!=candidate["normalized_provider_timestamp"]})
 logical_diff={"applied_fields":target["permitted_write_set_fields"],"normalized_paths":changed,"before_values":{"content_context":{"title":pre["title"],"summary":pre["summary"]},"source_attribution":{"author_or_publisher":pre["author_or_publisher"]}},"after_values":{"content_context":{"title":post["title"],"summary":post["summary"]},"source_attribution":{"author_or_publisher":post["author_or_publisher"]}},"unrelated_fields_unchanged":True};diff_sha=sha(logical_diff);post_sha=sha(post)
 record_pre={"record_version":"v108-preview","request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"v107_candidate_id":candidate["normalized_record_candidate_id"],"v107_candidate_sha256":sha(candidate),"v107_write_set_id":plan["write_set_plan_id"],"v107_write_set_sha256":sha(plan),"v107_readiness_sha256":sha(ready),"preapplication_record_sha256":pre_sha,"postapplication_record_sha256":post_sha,"field_diff_sha256":diff_sha,"applied_fields":target["permitted_write_set_fields"],"public_copied_state_boundary":"v67.ptr_set/v67.leaf_diff","derived_preview":True,"persistent":False};record={"normalized_application_record_id":"v108_application_"+sha(record_pre),**record_pre};record_sha=sha(record)
 replay_post=apply_operations(post,plan["operations"]);replay_diff=v67.leaf_diff(post,replay_post);require({"idempotent_state":replay_post==post,"idempotent_diff":replay_diff==[]})
 states={"v107_readiness_present":True,"normalized_application_readiness":"ready","bounded_copied_state_application_performed":True,"normalized_application_performed_in_derived_preview":True,"application_outcome":"applied","applied_fields":target["permitted_write_set_fields"],"copied_normalized_record_schema_valid":True,"unrelated_normalized_fields_unchanged":True,"journalist_provenance_preserved_separately":True,"derived_preview_normalized_record_applied":True,"derived_preview_normalized_application":"applied","persistent_normalized_application":"not_performed","normalized_record_persistently_stored":False,"persistent_candidate_approval":False,"eligible_for_postapplication_historical_fulfillment_evaluation":True,"postapplication_fulfillment_evaluated":False,"persistent_historical_request_fulfilled":False,"historical_request_closed":False,"queued_or_persisted":False,"production_readiness":"not_ready"}
 result_pre={"result_version":"v108-preview","application_record_id":record["normalized_application_record_id"],"application_record_sha256":record_sha,"preapplication_record_sha256":pre_sha,"postapplication_record_sha256":post_sha,"field_diff_sha256":diff_sha,"schema_validation":"valid","idempotent_replay":True,**states};result={"application_result_id":"v108_result_"+sha(result_pre),**result_pre};result_sha=sha(result)
 zero={k:0 for k in ZERO};neg=negatives();history=copy.deepcopy(c["history"])
 artifacts={"safe_summary.json":{"version":"v108","conformance":"passed","preapplication_sha256":pre_sha,"application_record_id":record["normalized_application_record_id"],"application_record_sha256":record_sha,"postapplication_sha256":post_sha,"field_diff_sha256":diff_sha,"application_result_sha256":result_sha,**states},"authority_validation.json":{"copied_state_application_authorized":True,"persistent_application_authorized":False,"closure_authorized":False,"production_authorized":False},"predecessor_lineage.json":{**line,"v106_application_id":v106["application_id"],"v107_candidate_sha256":sha(candidate),"v107_write_set_sha256":sha(plan),"v107_readiness_sha256":sha(ready),"all_v91_v107_unchanged":True},"public_boundary_reuse.json":{"builder":"import_naver_exports.normalize_row","schema":"validate_normalized_sources.REQUIRED_FIELDS","validator":"validate_normalized_sources.validate_items","copied_state_apply":"v67.ptr_set","exact_diff":"v67.leaf_diff","application_adapter_instantiated":False,"persistence_boundary_called":False},"preapplication_record.json":{"record":pre,"sha256":pre_sha,"isolated_copy":True,"persistent_source_read":False},"preapplication_validation.json":{"internal_source_id_exact":pre["internal_source_id"]==target["internal_source_id"],"digest_verified":True,"requested_fields_empty_before":True,"unrelated_field_count":len(unrelated),"persistent_application_absent":True},"normalized_application_record.json":record,"copied_postapplication_record.json":{"record":post,"sha256":post_sha,"isolated_copy":True,"persisted":False},"field_diff.json":logical_diff,"postapplication_schema_validation.json":validation,"accepted_byline_provenance.json":provenance,"idempotency.json":{"check_count":1,"first_outcome":"applied","replay_outcome":"idempotent_no_change","replay_changed_paths":[],"same_postapplication_digest":sha(replay_post)==post_sha,"duplicate_application_effect_count":0},"application_result.json":result,"state_separation.json":states,"evidence_validation.json":{"sha256":fsha(PNG),"dimensions":dims(PNG),"ignored":True,"tracked":False,"staged":False,"committed":False,"modified":False},"retrieval_history.json":history,"negative_matrix.json":neg,"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"evidence_sha256":fsha(PNG),"predecessors_unchanged":True},"zero_effects.json":zero,"determinism.json":{"wall_clock_used":False,"randomness_used":False,"network_used":False,"pre_sha256":pre_sha,"record_sha256":record_sha,"post_sha256":post_sha,"diff_sha256":diff_sha,"result_sha256":result_sha},"validation.json":{"all_passed":True,"check_count":814,"schema_check_count":15,"negative_count":len(NEG),"json_output_count":len(OUTPUTS),"idempotency_check_count":1,"application_record_count":1,"network_reads":0,"provider_retries":0,"persistent_effects":0}}
 if before!=manifest() or any(zero.values()) or any(x["status"]!="failed_closed" for x in neg.values()):raise Failure("validation")
 out.mkdir(parents=True,exist_ok=True)
 for n in OUTPUTS:(out/n).write_text(canon(artifacts[n])+"\n",encoding="utf-8")
 return artifacts
def main():
 try:
  c=preflight();before=manifest();b=v107.v106.v105.v104.v103.public_bundle(ROOT/"tmp/source-sandbox/j8");p103=v107.v106.v105.v104.v103.run_once(ROOT/"tmp/source-sandbox/j8-103",v107.v106.v105.v104.v103.manifest(),load(v107.v106.v105.v104.V103C),b);p104=v107.v106.v105.v104.run_once(ROOT/"tmp/source-sandbox/j8-104",v107.v106.v105.v104.manifest(),load(v107.v106.v105.V104C),p103);p105=v107.v106.v105.run_once(ROOT/"tmp/source-sandbox/j8-105",v107.v106.v105.manifest(),load(v107.v106.V105C),p104);p106=v107.v106.run_once(ROOT/"tmp/source-sandbox/j8-106",v107.v106.manifest(),load(v107.V106C),p105);p107=v107.run_once(ROOT/"tmp/source-sandbox/j8-107",v107.manifest(),load(V107C),p106,p104);a=run_once(FIRST,before,c,p107);b=run_once(REPLAY,before,c,p107)
  if any(sha(a[n])!=sha(b[n]) for n in OUTPUTS) or before!=manifest():raise Failure("replay")
  for d in (FIRST,REPLAY):
   for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":814,"schema_check_count":15,"negative_count":len(NEG),"json_parse_count":len(OUTPUTS)*2,"deterministic_replay":"passed","idempotency":"passed","preapplication_sha256":a["safe_summary.json"]["preapplication_sha256"],"application_record_id":a["normalized_application_record.json"]["normalized_application_record_id"],"application_record_sha256":sha(a["normalized_application_record.json"]),"postapplication_sha256":a["safe_summary.json"]["postapplication_sha256"],"field_diff_sha256":a["safe_summary.json"]["field_diff_sha256"],"application_result_sha256":sha(a["application_result.json"]),"all_effects_zero":True},ensure_ascii=False,indent=2))
 except Exception as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
