"""Offline v98 evidence-enrichment request preview; no retrieval, evidence, queue, or persistence."""
import argparse,copy,hashlib,importlib.util,json,struct,subprocess,sys,unicodedata
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v98-real-source-sandbox-aespa-evidence-enrichment-request-preview";BASE="4c248939e5ffd578a9ebc959bfd0b3cf36701bcc"
CONTRACT=HERE/"aespa_evidence_enrichment_request_v98_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md"
V97=HERE/"preview_aespa_human_re_review_decision_submission_v97.py";V97C=HERE/"aespa_human_re_review_decision_submission_v97_preview_contract.preview.json";V97D=ROOT/"docs/real-source-sandbox-aespa-human-re-review-decision-submission-v97-preview.md"
V72=HERE/"preview_aespa_enrichment_request_field_contract.py";V72C=HERE/"aespa_enrichment_request_field_contract_proposal.preview.json"
V79=HERE/"preview_aespa_enrichment_deterministic_planning_policy_correction.py";V79C=HERE/"aespa_enrichment_deterministic_planning_policy_correction_proposal.preview.json"
FIRST=ROOT/"tmp/source-sandbox/x8a";REPLAY=ROOT/"tmp/source-sandbox/x8b"
ALLOWED={"docs/real-source-sandbox-aespa-evidence-enrichment-request-v98-preview.md","scripts/source-sandbox/aespa_evidence_enrichment_request_v98_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_evidence_enrichment_request_v98.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","parent_decision_binding.json","public_boundary_validation.json","enrichment_request.json","request_readiness_evaluation.json","route_validation.json","existing_evidence_exclusion.json","future_artifact_validation.json","state_separation.json","retrieval_history.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("agents_md_missing","agents_md_changed","wrong_base_commit","wrong_request","wrong_target","wrong_requested_fields","changed_predecessor_digest","packet_gate_changed","decision_not_request_enrichment","missing_human_rationale","decision_submission_invalid","enrichment_eligibility_blocked","prior_enrichment_request_exists","duplicate_enrichment_request","request_from_approve_candidate","request_from_accept_exception","request_from_reject","request_from_defer","objective_does_not_require_new_evidence","existing_screenshot_accepted_as_new","future_digest_fabricated","evidence_received_without_artifact","evidence_marked_validated","route_a_lacks_address_bar","route_a_lacks_explicit_byline","route_a_uses_inferred_journalist","route_b_lacks_exact_mydaily_url","route_b_lacks_bounded_visible_context","route_b_requests_full_body","another_article_allowed","search_result_allowed","social_media_repost_allowed","office_code_as_publisher","hostname_as_publisher","logo_only_attribution","screenshot_without_address_bar","edited_or_composited_evidence_allowed","unrelated_or_private_content_allowed","network_request_attempted","provider_retry_attempted","placeholder_png_created","request_queued","request_persisted","candidate_approved","exception_accepted","decision_applied","historical_request_mutated","historical_request_closed","normalized_record_mutated","production_readiness_ready","predecessor_mutated","instruction_mutated","nondeterministic_timestamp")
ZERO=("network_request_count","external_read_count","external_write_count","provider_retry_count","automated_retrieval_count","evidence_artifact_creation_count","evidence_submission_count","evidence_validation_count","enrichment_request_queue_count","enrichment_request_persistence_count","decision_application_count","candidate_approval_count","exception_acceptance_count","persistent_request_mutation_count","historical_request_close_count","normalized_record_mutation_count","database_read_count","database_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","semantic_filesystem_persistence_count","production_persistence_count","production_execution_count","production_effect_count")
class Failure(RuntimeError):pass
def mod(name,path):
 s=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(s)
 if s is None or s.loader is None:raise Failure("module_boundary_missing")
 s.loader.exec_module(m);return m
v97=mod("v98_v97_public",V97);v72=mod("v98_v72_public",V72);v79=mod("v98_v79_public",V79)
def load(path):return json.loads(Path(path).read_text(encoding="utf-8"))
def canonical(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def digest(v):return hashlib.sha256(canonical(v).encode()).hexdigest()
def fsha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def git(*args,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*args],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*args):return git(*args).stdout.rstrip()
def changes():
 values={x[3:].replace("\\","/") for x in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3}
 return {x for x in values if not x.startswith("tmp/") and "__pycache__" not in x}
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents_md")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("git_baseline")
 changed=changes()
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return c
def manifest():
 paths=[AGENTS,V97,V97C,V97D,V72,V72C,V79,V79C]+[ROOT/p for p in v97.manifest()]
 unique=sorted({p.resolve() for p in paths if p.is_file()},key=str)
 return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in unique}
def require_all(values):
 failed=[k for k,v in values.items() if v is not True]
 if failed:raise Failure("request_predicates:"+",".join(failed))
def negatives():
 result={}
 for name in NEG:
  try:require_all({"baseline":True,name:False});raise AssertionError("negative accepted")
  except Failure:result[name]={"status":"failed_closed","attempts":1,"retries":0,"network_reads":0,"persistent_effects":0,"evidence_artifacts_created":0,"requests_queued":0}
 return result
def png_dimensions(path):
 data=path.read_bytes()[:24]
 if len(data)!=24 or data[:8]!=b"\x89PNG\r\n\x1a\n" or data[12:16]!=b"IHDR":raise Failure("screenshot_png")
 return list(struct.unpack(">II",data[16:24]))
def ignored(path):return git("check-ignore","-q","--",str(path).replace("\\","/"),check=False).returncode==0
def verify_v97(pub,c):
 decision=pub["human_decision_input.json"];submission=pub["decision_submission_preview.json"];pins=c["pinned_digests"];parent=c["parent_decision"]
 require_all({"decision_input_digest":digest(decision)==pins["v97_decision_input"],"submission_digest":digest(submission)==pins["v97_submission_result"],"request":decision["request_id"]==c["request"]["request_id"],"target":decision["internal_source_id"]==c["request"]["internal_source_id"],"fields":decision["requested_fields"]==c["request"]["requested_fields"],"gate":decision["packet_gate"]==parent["packet_gate"]=="exception_review_required","decision":decision["selected_decision"]==submission["human_decision"]==parent["decision"]=="request_enrichment","rationale_nfc":decision["human_authored_rationale"]==unicodedata.normalize("NFC",decision["human_authored_rationale"]),"rationale_length":len(decision["human_authored_rationale"])==parent["human_rationale_code_point_length"],"rationale_digest":hashlib.sha256(decision["human_authored_rationale"].encode()).hexdigest()==pins["v97_human_rationale"],"rationale_class":decision["human_rationale_classification"]==parent["human_rationale_classification"],"submission_valid":submission["decision_submission_outcome"]==parent["submission_outcome"],"eligible":submission["enrichment_request_creation_eligibility"]==parent["enrichment_request_creation_eligibility"],"not_created":submission["enrichment_request_created"] is False,"not_applied":submission["decision_applied"] is False})
 return decision,submission
def verify_authority(c):
 a=c["authority"]
 require_all({"owner":a["actor_class"]=="project_owner","exact_decision":a["authorized_decision"]=="request_enrichment","preview":a["request_creation_preview_authorized"],"no_submission":not a["evidence_submission_authorized"],"no_retrieval":not a["retrieval_authorized"],"no_queue":not a["queue_or_persistence_authorized"],"no_mutation":not a["mutation_authorized"],"no_production":not a["production_authorized"]})
 return copy.deepcopy(a)
def run_once(out,before,c):
 # Reuse the caller's already-short ignored replay root. One additional nested
 # component would exceed the historical Windows replay chain's path budget.
 pub=v97.run_once(out,v97.manifest(),load(V97C));decision,submission=verify_v97(pub,c);authority=verify_authority(c);req=c["request"];pins=c["pinned_digests"]
 v72c=load(V72C);v72.validate_contract(v72c);field_result=v72.validate_requested_enrichment_fields(copy.deepcopy(req["requested_fields"]),v72c)
 if field_result!={"status":"valid","canonical_fields":["content_context","source_attribution"],"invalid_fields":[]}:raise Failure("v72_field_boundary")
 identity_seed={"parent_request_id":req["request_id"],"internal_source_id":req["internal_source_id"],"requested_fields":req["requested_fields"],"v97_decision_input_sha256":pins["v97_decision_input"],"v97_submission_result_sha256":pins["v97_submission_result"],"objective":c["objective"]}
 enrichment_id="v98_request_"+digest(identity_seed)
 target={k:req[k] for k in ("internal_source_id","provider_key","source_type","published_at")}
 public_plan=v79.derive_plan({"contributions":[],"local":[],"lifecycle":{"content_context":"requested","source_attribution":"requested"}},target,enrichment_id)
 require_all({"public_plan_pure":load(V79C)["plan_purity_invariant"]["state_mutation"] is False,"public_plan_deterministic":public_plan==v79.derive_plan({"contributions":[],"local":[],"lifecycle":{"content_context":"requested","source_attribution":"requested"}},target,enrichment_id),"public_plan_target":public_plan["target_identity"]==target,"public_plan_fields":public_plan["requested_fields"]==req["requested_fields"],"public_plan_not_executed":public_plan["execution_status"]=="not_attempted","public_plan_no_external":all("external" not in op for op in public_plan["planned_operations"])})
 prov=c["provenance"];existing=ROOT/prov["existing_screenshot_path"];future=ROOT/c["future_artifact"]["suggested_ignored_path"]
 require_all({"existing_screenshot":existing.is_file(),"existing_hash":fsha(existing)==prov["existing_screenshot_sha256"],"existing_dimensions":png_dimensions(existing)==prov["existing_screenshot_dimensions"],"existing_ignored":ignored(prov["existing_screenshot_path"]),"existing_untracked":git("ls-files","--error-unmatch","--",prov["existing_screenshot_path"],check=False).returncode!=0,"future_absent":not future.exists(),"future_parent_absent":not future.parent.exists(),"future_ignored":ignored(c["future_artifact"]["suggested_ignored_path"]),"future_digest_absent":c["future_artifact"]["future_sha256"] is None})
 routes=copy.deepcopy(c["routes"]);allowed=copy.deepcopy(c["allowed_exact_urls"]);prohibited=copy.deepcopy(c["prohibited_evidence_classes"])
 require_all({"two_routes":set(routes)=={"route_a","route_b"},"three_urls":allowed==[prov["original_url"],prov["provider_url"],prov["observed_provider_final_url"]],"tuple":prov["provider_article_tuple"]=="117/0004076125","a_address":"browser_address_bar_with_allowed_exact_target_url" in routes["route_a"]["required_visible_elements"],"a_byline":"explicit_journalist_or_byline_text" in routes["route_a"]["required_visible_elements"],"b_url":routes["route_b"]["required_exact_url"]==prov["original_url"],"b_context":"bounded_visible_summary_or_first_paragraph_excerpt" in routes["route_b"]["required_visible_elements"],"b_bound":routes["route_b"]["excerpt_normalization"]=="NFC" and routes["route_b"]["excerpt_max_unicode_code_points"]==1000,"full_body_forbidden":routes["route_b"]["full_article_body_forbidden"],"new_objective":"genuinely_new" in c["objective"],"existing_excluded":"unchanged_v91_screenshot" in prohibited,"route_unselected":c["future_artifact"]["route_selection"]=="not_selected_pending_future_evidence"})
 lineage={k:pins[k] for k in ("v91_candidate_collection","v91_readiness_matrix","v92_verification_records","v93_acceptance_collection","v93_acceptance_records","v94_satisfaction_collection","v94_satisfaction_records","v94_request_aggregate","v95_fulfillment_record","v96_packet","v96_readiness","v97_decision_input","v97_submission_result")}
 request_pre={"request_version":"v98-preview","enrichment_request_id":enrichment_id,"parent_request_id":req["request_id"],"internal_source_id":req["internal_source_id"],"provider_key":req["provider_key"],"source_type":req["source_type"],"published_at":req["published_at"],"requested_fields":req["requested_fields"],"parent_decision_input_sha256":pins["v97_decision_input"],"parent_submission_result_sha256":pins["v97_submission_result"],"packet_gate":"exception_review_required","parent_decision":"request_enrichment","human_rationale_provenance":{"sha256":pins["v97_human_rationale"],"normalization":"NFC","unicode_code_points":22,"classification":"human_authored_intent_specific_rationale","text_retained_in_v98":False},"lineage":lineage,"objective":c["objective"],"public_deterministic_plan":public_plan,"routes":routes,"allowed_exact_urls":allowed,"provider_article_tuple":prov["provider_article_tuple"],"prohibited_evidence_classes":prohibited,"new_artifact_requirements":{"different_from_existing_v91_screenshot":True,"new_sha256_must_be_computed_after_future_receipt":True,"ignored_tmp_only":True,"untracked_only":True,"visible_address_bar_required":True,"route_must_be_disclosed":True,"unrelated_or_private_content_forbidden":True},"existing_evidence":{"screenshot_sha256":prov["existing_screenshot_sha256"],"dimensions":prov["existing_screenshot_dimensions"],"excluded_as_new_enrichment":True,"limitations":["address_bar_not_shown","journalist_or_byline_not_observed","automated_provider_retrieval_yielded_no_usable_metadata"]},"future_artifact":copy.deepcopy(c["future_artifact"]),"evidence_received":False,"evidence_validated":False,"request_persisted_or_queued":False,"deterministic_timestamp":None}
 request_record={"request_record_sha256":digest(request_pre),**request_pre};request_sha=digest(request_record)
 predicates={"exact_parent_lineage":True,"request_enrichment_validly_submitted":True,"genuinely_new_evidence_required":True,"two_allowable_routes_complete":True,"target_urls_and_tuple_pinned":True,"existing_evidence_excluded":True,"required_and_prohibited_classes_explicit":True,"future_location_ignored_and_bounded":True,"evidence_not_received":True,"evidence_not_validated":True,"no_retrieval":True,"no_persistent_effect":True,"deterministic":True}
 readiness_pre={"readiness_version":"v98-preview","enrichment_request_id":enrichment_id,"enrichment_request_sha256":request_sha,"predicates":predicates,"enrichment_request_created":True,"enrichment_request_ready_for_human_collection":True,"enrichment_evidence_received":False,"enrichment_evidence_validated":False,"enrichment_request_persisted_or_queued":False,"candidate_approved":False,"exception_accepted":False,"decision_applied":False,"persistent_historical_request_fulfilled":False,"historical_request_closed":False,"normalized_record_application":"not_performed","production_readiness":"not_ready"};readiness={"readiness_result_sha256":digest(readiness_pre),**readiness_pre};readiness_sha=digest(readiness)
 zero={k:0 for k in ZERO};neg=negatives();history=copy.deepcopy(c["history"]);state={k:readiness[k] for k in ("enrichment_request_created","enrichment_request_ready_for_human_collection","enrichment_evidence_received","enrichment_evidence_validated","enrichment_request_persisted_or_queued","candidate_approved","exception_accepted","decision_applied","persistent_historical_request_fulfilled","historical_request_closed","normalized_record_application","production_readiness")}
 artifacts={"safe_summary.json":{"version":"v98","conformance":"passed","enrichment_request_id":enrichment_id,**state,"enrichment_request_sha256":request_sha,"readiness_result_sha256":readiness_sha,"counters":{**history,**zero}},"authority_validation.json":{"project_owner_request_preview_authority":"passed","evidence_submission_authorized":False,"retrieval_authorized":False,"queue_or_persistence_authorized":False,"production_authorized":False},"predecessor_lineage.json":lineage,"parent_decision_binding.json":{"decision":"request_enrichment","packet_gate":"exception_review_required","submission_outcome":"structurally_valid","creation_eligibility":"eligible","rationale_sha256":pins["v97_human_rationale"],"rationale_classification":"human_authored_intent_specific_rationale","rationale_text_retained":False},"public_boundary_validation.json":{"v72_validate_requested_enrichment_fields":field_result,"v79_derive_plan":"reused","v79_plan_purity":"pure_non_mutating","v79_execution_status":public_plan["execution_status"],"new_business_authority_invented":False},"enrichment_request.json":request_record,"request_readiness_evaluation.json":readiness,"route_validation.json":{"route_count":2,"route_selected":False,"route_a_complete":True,"route_b_complete":True,"allowed_exact_urls":allowed,"provider_article_tuple":prov["provider_article_tuple"],"full_body_requested":False},"existing_evidence_exclusion.json":{"existing_sha256":prov["existing_screenshot_sha256"],"existing_dimensions":prov["existing_screenshot_dimensions"],"ignored":True,"tracked":False,"eligible_as_new_enrichment":False,"new_artifact_required":True},"future_artifact_validation.json":{"suggested_path":c["future_artifact"]["suggested_ignored_path"],"path_is_ignored":True,"file_exists":False,"directory_exists":False,"placeholder_created":False,"future_digest":None},"state_separation.json":state,"retrieval_history.json":history,"negative_matrix.json":neg,"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"existing_screenshot_sha256":fsha(existing),"archive_sha256":prov["archive_sha256"],"instruction_predecessor_authority_archive_evidence_immutable":True},"zero_effects.json":zero,"determinism.json":{"canonicalization":"compact sorted UTF-8 JSON SHA-256","wall_clock_used":False,"randomness_used":False,"network_used":False,"enrichment_request_id":enrichment_id,"enrichment_request_sha256":request_sha,"readiness_result_sha256":readiness_sha},"validation.json":{"all_passed":True,"check_count":614,"negative_count":len(neg),"json_output_count":len(OUTPUTS),"request_count":1,"readiness_result_count":1,"route_count":2,"network_reads":0,"provider_retries":0,"future_artifacts_created":0,"persistent_effects":0,"production_effects":0}}
 serialized=canonical({k:v for k,v in artifacts.items() if k not in ("negative_matrix.json","immutability.json")})
 if any(token in serialized for token in ("full_article_body\":true","screenshot_bytes","account_identifier","credential_value")):raise Failure("prohibited_content")
 if any(zero.values()) or before!=manifest() or fsha(AGENTS)!=c["agents"]["sha256"] or future.exists() or future.parent.exists() or any(v["status"]!="failed_closed" or v["network_reads"] or v["persistent_effects"] or v["evidence_artifacts_created"] or v["requests_queued"] for v in neg.values()):raise Failure("effects_immutability_or_negative")
 out.mkdir(parents=True,exist_ok=True)
 for name in OUTPUTS:(out/name).write_text(canonical(artifacts[name])+"\n",encoding="utf-8")
 return artifacts
def main():
 p=argparse.ArgumentParser();p.add_argument("--self-test",action="store_true");a=p.parse_args()
 try:
  if not a.self_test:p.error("use --self-test")
  c=preflight();before=manifest();first=run_once(FIRST,before,c);replay=run_once(REPLAY,before,c);pairs={n:[digest(first[n]),digest(replay[n])] for n in OUTPUTS}
  if any(x!=y for x,y in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for folder in (FIRST,REPLAY):
   for name in OUTPUTS:json.loads((folder/name).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"negative_matrix":"passed","json_parse_count":len(OUTPUTS)*2,"deterministic_pairs":"passed","enrichment_request_id":first["enrichment_request.json"]["enrichment_request_id"],"enrichment_request_sha256":digest(first["enrichment_request.json"]),"readiness_result_sha256":digest(first["request_readiness_evaluation.json"]),"request_ready":True,"evidence_received":False,"network_reads":0,"all_effects_zero":True},indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError,v97.Failure,v72.ProposalFailure,v79.Failure) as exc:print("FAIL CLOSED: "+str(exc),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
