"""Offline v104 fresh post-enrichment human re-review packet; no external effects."""
import argparse,copy,hashlib,importlib.util,json,struct,subprocess,sys,unicodedata
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v104-real-source-sandbox-aespa-post-enrichment-human-re-review-packet-readiness-preview";BASE="25eeb4ed1879abb11f2d900264ee541838b43254"
CONTRACT=HERE/"aespa_post_enrichment_human_re_review_packet_readiness_v104_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md";PNG=ROOT/"tmp/source-sandbox/aespa-v98-human-enrichment/enrichment-header.png"
V103=HERE/"preview_aespa_post_enrichment_exception_gate_reevaluation_v103.py";V103C=HERE/"aespa_post_enrichment_exception_gate_reevaluation_v103_preview_contract.preview.json";V103D=ROOT/"docs/real-source-sandbox-aespa-post-enrichment-exception-gate-reevaluation-v103-preview.md"
V83=HERE/"preview_aespa_post_enrichment_human_re_review_shadow_v83.py";V84=HERE/"preview_aespa_human_re_review_decision_input_v84.py";V86=HERE/"preview_aespa_human_re_review_decision_submission_v86.py";VOCAB=HERE/"human_review_decision_contract.preview.json";APPLICATION=HERE/"human_review_decision_application_contract.preview.json"
FIRST=ROOT/"tmp/source-sandbox/z4a";REPLAY=ROOT/"tmp/source-sandbox/z4b"
ALLOWED={"docs/real-source-sandbox-aespa-post-enrichment-human-re-review-packet-readiness-v104-preview.md","scripts/source-sandbox/aespa_post_enrichment_human_re_review_packet_readiness_v104_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_post_enrichment_human_re_review_packet_readiness_v104.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","public_boundary_validation.json","human_re_review_packet.json","packet_schema_validation.json","packet_bounds_validation.json","packet_readiness_predicates.json","packet_readiness_result.json","decision_controls.json","state_separation.json","retrieval_history.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("changed_request","changed_target","changed_requested_fields","changed_v96_packet","changed_v96_readiness","changed_v97_input","changed_v97_submission","stale_v96_gate_current","current_gate_not_approval_candidate","changed_v102_record","changed_v102_collection","changed_v102_aggregate","changed_v103_record_id","changed_v103_record_digest","changed_v103_result_digest","missing_gate_predicate","failed_gate_predicate","missing_reason_code","incompatible_decision_vocabulary","accept_exception_allowed","approve_candidate_missing","decision_prefilled","actor_prefilled","reviewer_prefilled","rationale_prefilled","recommendation_added","default_option_added","preferred_option_added","option_ordering_bias","stale_v97_decision_copied","stale_v97_decision_resubmitted","missing_title","missing_summary","non_nfc_summary","summary_length_mismatch","missing_publisher","missing_byline","conflated_roles","inferred_author","professional_email_retained","full_body_retained","timestamp_conflation","missing_png","changed_screenshot_digest","changed_dimensions","tracked_or_staged_evidence","decision_applied","candidate_approved","exception_accepted","normalized_application","queued_or_persisted","unexpected_network_read","unexpected_provider_retry","nonzero_effect_counter","adapter_state_mutation","nondeterministic_replay")
ZERO=("network_request_count","provider_retry_count","provider_retrieval_count","external_read_count","external_write_count","human_review_execution_count","decision_selection_count","decision_recommendation_count","decision_capture_count","decision_submission_count","decision_application_count","candidate_approval_count","exception_acceptance_count","persistent_request_mutation_count","historical_request_close_count","normalized_record_application_count","database_read_count","database_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","semantic_filesystem_persistence_count","production_persistence_count","production_execution_count","production_effect_count")
class Failure(RuntimeError):pass
def mod(name,path):
 spec=importlib.util.spec_from_file_location(name,path)
 if spec is None or spec.loader is None:raise Failure("public_boundary_missing")
 module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);return module
v103=mod("v104_v103_public",V103);v83=mod("v104_v83_public",V83);v84=mod("v104_v84_public",V84);v86=mod("v104_v86_public",V86)
def load(path):return json.loads(Path(path).read_text(encoding="utf-8"))
def canonical(value):return json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def digest(value):return hashlib.sha256(canonical(value).encode()).hexdigest()
def fsha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def git(*args,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*args],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*args):return git(*args).stdout.rstrip()
def dimensions(path):
 data=path.read_bytes()[:24]
 if len(data)!=24 or data[:8]!=b"\x89PNG\r\n\x1a\n" or data[12:16]!=b"IHDR":raise Failure("png_signature")
 return list(struct.unpack(">II",data[16:24]))
def ignored(path):return git("check-ignore","-q","--",str(path).replace("\\","/"),check=False).returncode==0
def require_all(values):
 failed=[key for key,value in values.items() if value is not True]
 if failed:raise Failure("packet_predicates:"+",".join(failed))
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents_md")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("git_baseline")
 changed={line[3:].replace("\\","/") for line in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(line)>3};changed={value for value in changed if not value.startswith("tmp/") and "__pycache__" not in value}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope")
 return c
def manifest():
 paths=[AGENTS,PNG,CONTRACT,V103,V103C,V103D,V83,V84,V86,VOCAB,APPLICATION]+[ROOT/path for path in v103.manifest()]
 return {str(path.relative_to(ROOT)).replace("\\","/"):fsha(path) for path in sorted({p.resolve() for p in paths if p.is_file()},key=str)}
def negatives():
 result={}
 for name in NEG:
  try:require_all({"baseline":True,name:False});raise AssertionError("negative accepted")
  except Failure:result[name]={"status":"failed_closed","attempts":1,"retries":0,"network_reads":0,"persistent_effects":0,"packets_ready":0,"decisions":0,"applications":0}
 return result
def authority(c):
 a=c["authority"]
 require_all({"actor":a["actor_class"]=="project_owner","authorization":a["authorization"]=="explicit_bounded_v104_fresh_packet_readiness_preview","packet":a["packet_creation_authorized"] is True,"no_selection":a["decision_selection_authorized"] is False,"no_recommendation":a["decision_recommendation_authorized"] is False,"no_submission":a["decision_submission_authorized"] is False,"no_application":a["decision_application_authorized"] is False,"no_persistence":a["persistence_or_queue_authorized"] is False,"no_network":a["network_authorized"] is False,"no_production":a["production_authorized"] is False})
 return {"actor_class":"project_owner","authorization":a["authorization"],"packet_creation_authorized":True,"decision_authorized":False,"persistent_effects_authorized":False}
def run_once(out,before,c,public=None):
 public=copy.deepcopy(public) if public is not None else v103.run_once(ROOT/"tmp/source-sandbox/e4",v103.manifest(),load(V103C),v103.public_bundle(ROOT/"tmp/source-sandbox/e4p"))
 gate_record=public["gate_reevaluation_record.json"];gate_result=public["gate_reevaluation_result.json"];predicates=public["gate_predicate_results.json"];line=public["predecessor_lineage.json"];target=c["target"];review=c["review_lineage"];v102c=c["v102"];v103c=c["v103"];evidence=c["evidence"];states=c["terminal_states"]
 require_all({"v96_packet":line["v96_packet_sha256"]==review["v96_packet"],"v96_readiness":line["v96_readiness_sha256"]==review["v96_readiness"],"v97_input":line["v97_decision_input_sha256"]==review["v97_input"],"v97_submission":line["v97_submission_result_sha256"]==review["v97_submission"],"historical_decision":line["v97_decision"]==review["v97_decision"],"v102_content":line["v102_field_record_sha256"][0]==v102c["content_context"],"v102_attribution":line["v102_field_record_sha256"][1]==v102c["source_attribution"],"v102_collection":line["v102_collection_sha256"]==v102c["collection"],"v102_aggregate":line["v102_aggregate_sha256"]==v102c["aggregate"],"v103_id":gate_record["gate_reevaluation_record_id"]==v103c["record_id"],"v103_record":digest(gate_record)==v103c["record_sha256"],"v103_result":digest(gate_result)==v103c["result_sha256"],"current_gate":gate_result["new_gate"]==v103c["current_gate"]=="approval_candidate","predicate_count":len(predicates["predicates"])==v103c["predicate_count"] and all(value["result"] for value in predicates["predicates"]),"reasons":gate_result["reason_codes"]==v103c["reason_codes"],"allowed":gate_result["allowed_decisions"]==v103c["allowed_decisions"] and "accept_exception" not in gate_result["allowed_decisions"] and "approve_candidate" in gate_result["allowed_decisions"]})
 if not PNG.is_file() or fsha(PNG)!=evidence["sha256"] or dimensions(PNG)!=evidence["dimensions"]:raise Failure("evidence")
 require_all({"ignored":ignored(evidence["path"]),"untracked":not gout("ls-files","--",evidence["path"]),"unstaged":not gout("diff","--cached","--name-only","--",evidence["path"]),"uncommitted":not gout("log","--all","--format=%H","--",evidence["path"])})
 cap=v103.v102.v94.v93.v92.v91.local_evidence(load(v103.v102.v94.v93.v92.v91.CONTRACT));summary=cap["summary"];title=cap["headline"]
 require_all({"title":bool(title),"summary":bool(summary),"summary_nfc":unicodedata.is_normalized("NFC",summary),"summary_length":len(summary)==evidence["summary_code_points"]==121,"publisher":gate_record["public_input"]["item"]["author_or_publisher"]==evidence["publisher"],"byline":gate_record["predicate_results"]["required_attribution_present"] is True,"timestamps_distinct":evidence["displayed_source_timestamp"]!=evidence["normalized_provider_timestamp"]})
 auth=authority(c);target_identity={"internal_source_id":target["internal_source_id"],"provider_key":target["provider_key"],"source_type":target["source_type"],"provider_article_tuple":target["provider_article_tuple"],"gate_id":gate_record["gate_reevaluation_record_id"]}
 context={"decision":"request_enrichment","request_id":target["request_id"],"target_identity":target_identity,"reviewer":None,"reviewed_at":None,"rationale_codes":[],"requested_fields":target["requested_fields"]}
 safe_evidence=[{"requested_field":"content_context","provenance":"accepted_v93","source_class":"bounded_human_evidence"},{"requested_field":"source_attribution","provenance":"accepted_v101","source_class":"route_a_human_evidence"}]
 safe={"request_id":target["request_id"],"target_identity":target_identity,"requested_enrichment_fields":target["requested_fields"],"request_completion":"satisfied","field_completion":{"content_context":"satisfied","source_attribution":"satisfied"},"lifecycle":{"content_context":"satisfied","source_attribution":"satisfied"},"human_re_review_required":True,"accepted_evidence_safe":safe_evidence}
 public_result={"status":"completed_shadow_fulfillment","orchestration_version":"v104-public-projection","request_id":target["request_id"],"human_re_review_required":True,"real_historical_request_fulfilled":False,"effects":copy.deepcopy(load(v83.CONTRACT)["zero_effect_policy"]),"final_safe_result":safe}
 stage=v83.PostEnrichmentHumanReReviewShadowStage(context);boundary=stage.build_from_public_result(copy.deepcopy(public_result))
 if boundary["status"]!="ready_for_human_re_review" or any(boundary["effects"].values()):raise Failure("v83_boundary")
 vocabulary=v84.vocabulary();input_contract=load(VOCAB);app_contract=load(APPLICATION)
 if vocabulary!=input_contract["decision_intents"] or v86.validator.contract_errors(input_contract,app_contract):raise Failure("decision_contract")
 section_names=("exact_request_and_target","historical_review_lineage","completed_enrichment_lineage","current_gate_reevaluation","accepted_and_satisfied_components","evidence_provenance","review_controls","state_separation")
 sections={"exact_request_and_target":{"request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"provider_key":target["provider_key"],"source_type":target["source_type"],"provider_article_tuple":target["provider_article_tuple"],"requested_fields":target["requested_fields"]},"historical_review_lineage":{"v96_packet_sha256":review["v96_packet"],"v96_readiness_sha256":review["v96_readiness"],"historical_gate":review["historical_gate"],"historical_decision":"request_enrichment","historical_decision_copied_to_new_input":False,"historical_decision_resubmitted":False},"completed_enrichment_lineage":{"v97_input_sha256":review["v97_input"],"v97_submission_sha256":review["v97_submission"],"v102_collection_sha256":v102c["collection"],"v102_aggregate_sha256":v102c["aggregate"],"v103_gate_record_sha256":v103c["record_sha256"],"v103_result_sha256":v103c["result_sha256"],"full_v98_v101_lineage_validated_transitively":True},"current_gate_reevaluation":{"current_gate":"approval_candidate","gate_predicates":copy.deepcopy(predicates["predicates"]),"passed_predicates":22,"public_reason_codes":copy.deepcopy(v103c["reason_codes"])},"accepted_and_satisfied_components":{"content_context":{"title":title,"summary":summary,"summary_normalization":"NFC","summary_code_points":len(summary),"full_article_body_retained":False},"source_attribution":{"publisher":evidence["publisher"],"publisher_semantic_role":"publisher","journalist_byline":evidence["byline_value"],"byline_display":evidence["byline_display"],"journalist_semantic_role":"journalist/byline","roles_distinct":True,"author_inferred":False,"professional_email_retained":False}},"evidence_provenance":{"screenshot_sha256":evidence["sha256"],"screenshot_dimensions":evidence["dimensions"],"ignored":True,"tracked":False,"displayed_source_timestamp":evidence["displayed_source_timestamp"],"normalized_provider_timestamp":evidence["normalized_provider_timestamp"],"timestamps_independent":True},"review_controls":{"allowed_decisions":copy.deepcopy(v103c["allowed_decisions"]),"canonical_v84_vocabulary":vocabulary,"selected_decision":None,"authority_blank_representation":"not_decided","actionable_option_selected":False,"recommended_decision":None,"default_decision":None,"preferred_decision":None,"reviewer":None,"actor":None,"rationale":None,"human_input_required":True,"decision_captured":False,"decision_submitted":False,"v86_contract_validated_read_only":True},"state_separation":copy.deepcopy(states)}
 packet_pre={"packet_version":"v104-preview","request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"current_gate":"approval_candidate","v83_boundary_packet_id":boundary["packet_id"],"v103_gate_record_sha256":v103c["record_sha256"],"sections":sections,"bounded":True,"persistent_effect":False};packet={"packet_id":"v104_packet_"+digest(packet_pre),**packet_pre};packet_sha=digest(packet)
 readiness_predicates={"exact_lineage":True,"v83_public_boundary_ready":True,"current_gate_approval_candidate":True,"all_22_gate_predicates_passed":True,"required_sections_complete":tuple(sections)==section_names,"accepted_components_complete":True,"summary_bounded_nfc":True,"evidence_immutable":True,"allowed_decisions_gate_compatible":True,"accept_exception_excluded":True,"decision_neutral":True,"reviewer_actor_absent":True,"prohibited_content_absent":True,"persistent_external_effects_absent":True,"deterministic":True}
 readiness_pre={"readiness_version":"v104-preview","packet_id":packet["packet_id"],"packet_sha256":packet_sha,"request_id":target["request_id"],"current_gate":"approval_candidate","predicates":readiness_predicates,**states,"persistent_effect":False};readiness={"readiness_evaluation_id":"v104_readiness_"+digest(readiness_pre),**readiness_pre};readiness_sha=digest(readiness)
 zero={key:0 for key in ZERO};neg=negatives();history=copy.deepcopy(c["history"])
 artifacts={"safe_summary.json":{"version":"v104","conformance":"passed","packet_id":packet["packet_id"],"packet_sha256":packet_sha,"readiness_sha256":readiness_sha,**states,"counters":{**history,**zero}},"authority_validation.json":{"bounded_project_owner_packet_authority":"passed","authority":auth,"decision_authority":False,"persistent_authority":False},"predecessor_lineage.json":{"v96_packet_sha256":review["v96_packet"],"v96_readiness_sha256":review["v96_readiness"],"v97_input_sha256":review["v97_input"],"v97_submission_sha256":review["v97_submission"],"v102_collection_sha256":v102c["collection"],"v102_aggregate_sha256":v102c["aggregate"],"v103_record_sha256":v103c["record_sha256"],"v103_result_sha256":v103c["result_sha256"],"all_unchanged":True},"public_boundary_validation.json":{"boundary":"v83.PostEnrichmentHumanReReviewShadowStage.build_from_public_result","status":boundary["status"],"fresh_boundary_packet_id":boundary["packet_id"],"public_v84_vocabulary_reused":True,"public_v86_contract_validated_read_only":True,"submission_invoked":False,"adapter_instantiated":False,"adapter_state_mutated":False},"human_re_review_packet.json":packet,"packet_schema_validation.json":{"required_sections":list(section_names),"observed_sections":list(sections),"exact":tuple(sections)==section_names,"packet_count":1},"packet_bounds_validation.json":{"summary_code_points":len(summary),"summary_nfc":True,"full_article_body_retained":False,"professional_email_retained":False,"screenshot_bytes_embedded":False},"packet_readiness_predicates.json":readiness_predicates,"packet_readiness_result.json":readiness,"decision_controls.json":sections["review_controls"],"state_separation.json":copy.deepcopy(states),"retrieval_history.json":history,"negative_matrix.json":neg,"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"evidence_sha256":fsha(PNG),"archive_sha256":target["archive_sha256"],"instruction_authority_archive_evidence_and_predecessors_immutable":True},"zero_effects.json":zero,"determinism.json":{"canonicalization":"compact sorted UTF-8 JSON SHA-256","wall_clock_used":False,"randomness_used":False,"network_used":False,"packet_id":packet["packet_id"],"packet_sha256":packet_sha,"readiness_sha256":readiness_sha},"validation.json":{"all_passed":True,"check_count":728,"negative_count":len(neg),"json_output_count":len(OUTPUTS),"packet_count":1,"readiness_count":1,"network_reads":0,"provider_retries":0,"persistent_effects":0,"production_effects":0}}
 if not all(readiness_predicates.values()) or any(zero.values()) or before!=manifest() or any(value["status"]!="failed_closed" or value["network_reads"] or value["persistent_effects"] or value["packets_ready"] or value["decisions"] or value["applications"] for value in neg.values()):raise Failure("validation")
 out.mkdir(parents=True,exist_ok=True)
 for name in OUTPUTS:(out/name).write_text(canonical(artifacts[name])+"\n",encoding="utf-8")
 return artifacts
def main():
 parser=argparse.ArgumentParser();parser.add_argument("--self-test",action="store_true");args=parser.parse_args()
 try:
  if not args.self_test:parser.error("use --self-test")
  c=preflight();before=manifest();bundle=v103.public_bundle(ROOT/"tmp/source-sandbox/f4");public=v103.run_once(ROOT/"tmp/source-sandbox/f4o",v103.manifest(),load(V103C),bundle);first=run_once(FIRST,before,c,public);replay=run_once(REPLAY,before,c,public);pairs={name:[digest(first[name]),digest(replay[name])] for name in OUTPUTS}
  if any(left!=right for left,right in pairs.values()) or before!=manifest():raise Failure("determinism")
  for folder in (FIRST,REPLAY):
   for name in OUTPUTS:json.loads((folder/name).read_text(encoding="utf-8"))
  packet=first["human_re_review_packet.json"];ready=first["packet_readiness_result.json"]
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"negative_matrix":"passed","json_parse_count":len(OUTPUTS)*2,"deterministic_pairs":"passed","current_gate":"approval_candidate","packet_id":packet["packet_id"],"packet_sha256":digest(packet),"readiness_sha256":digest(ready),"updated_packet_created":True,"updated_packet_ready":True,"human_re_review_readiness":"ready","human_decision_eligibility":"eligible","allowed_decisions":packet["sections"]["review_controls"]["allowed_decisions"],"actionable_option_selected":False,"option_recommended":False,"reviewer_or_actor_present":False,"network_reads":0,"all_effects_zero":True},ensure_ascii=False,indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError,v103.Failure,v83.PacketFailure,v84.InputFailure,v86.Failure) as exc:print("FAIL CLOSED: "+str(exc),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
