"""Offline v102 post-enrichment field-satisfaction reevaluation; no external effects."""
import argparse,copy,hashlib,importlib.util,json,struct,subprocess,sys,unicodedata
from pathlib import Path

sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v102-real-source-sandbox-aespa-enriched-evidence-field-satisfaction-preview";BASE="a59297b8b3c0fe56900fc0bcd29b2845dc8c4726"
CONTRACT=HERE/"aespa_enriched_evidence_field_satisfaction_v102_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md";PNG=ROOT/"tmp/source-sandbox/aespa-v98-human-enrichment/enrichment-header.png"
V94=HERE/"preview_aespa_accepted_evidence_field_satisfaction_v94.py";V94C=HERE/"aespa_accepted_evidence_field_satisfaction_v94_preview_contract.preview.json";V94D=ROOT/"docs/real-source-sandbox-aespa-accepted-evidence-field-satisfaction-v94-preview.md"
V101=HERE/"preview_aespa_human_evidence_enrichment_acceptance_v101.py";V101C=HERE/"aespa_human_evidence_enrichment_acceptance_v101_preview_contract.preview.json";V101D=ROOT/"docs/real-source-sandbox-aespa-human-evidence-enrichment-acceptance-v101-preview.md"
FIRST=ROOT/"tmp/source-sandbox/z2a";REPLAY=ROOT/"tmp/source-sandbox/z2b"
ALLOWED={"docs/real-source-sandbox-aespa-enriched-evidence-field-satisfaction-v102-preview.md","scripts/source-sandbox/aespa_enriched_evidence_field_satisfaction_v102_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_enriched_evidence_field_satisfaction_v102.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","public_boundary_validation.json","predecessor_lineage.json","v94_preservation.json","v101_acceptance_binding.json","evidence_immutability.json","public_evaluator_input.json","field_satisfaction_records.json","request_aggregate.json","route_a_enrichment_satisfaction.json","timestamp_separation.json","privacy_and_bounds.json","retrieval_and_human_evidence_history.json","state_separation.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("changed_request","changed_target","changed_requested_fields","missing_requested_field","additional_requested_field","changed_v91_candidate_digest","changed_v91_readiness_digest","changed_v92_verification_digest","changed_v93_acceptance_collection","changed_v93_content_acceptance","changed_v93_attribution_acceptance","changed_v94_satisfaction_collection","changed_v94_content_satisfaction","changed_v94_attribution_satisfaction","changed_v94_aggregate","changed_v98_request_id","changed_v98_request_digest","changed_v98_readiness_digest","changed_v99_candidate_id","changed_v99_candidate_digest","changed_v99_intake_digest","changed_v100_verification_id","changed_v100_verification_digest","changed_v100_result_digest","non_verified_v100_result","changed_v101_acceptance_id","changed_v101_acceptance_digest","changed_v101_collection_digest","changed_v101_result_digest","non_accepted_v101_result","missing_png","changed_png_digest","changed_png_dimensions","tracked_or_staged_png","changed_title","missing_u2026","three_full_stops","changed_summary","non_nfc_summary","overlong_summary","summary_length_mismatch","full_body_retention","missing_publisher","publisher_replaced_by_journalist","missing_byline","inferred_byline","conflated_semantic_roles","additional_author_inferred","professional_email_retention","timestamp_conflation","timestamp_rounding_inferred","private_evaluator_mutation","adapter_state_mutation","only_one_field_satisfied","aggregate_true_with_false_field","route_a_not_satisfied","gate_reevaluated","human_or_enrichment_decision_applied","candidate_approved","exception_accepted","historical_request_closed","normalized_application","queued_or_persisted","unexpected_network_read","unexpected_provider_retry","nonzero_effect_counter","predecessor_mutation","nondeterministic_replay")
ZERO=("network_request_count","provider_retry_count","provider_retrieval_count","external_read_count","external_write_count","exception_gate_reevaluation_count","human_decision_application_count","enrichment_decision_application_count","candidate_approval_count","exception_acceptance_count","persistent_request_mutation_count","historical_request_close_count","normalized_record_application_count","database_read_count","database_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","semantic_filesystem_persistence_count","production_persistence_count","production_execution_count","production_effect_count")

class Failure(RuntimeError):pass
def mod(name,path):
 spec=importlib.util.spec_from_file_location(name,path)
 if spec is None or spec.loader is None:raise Failure("public_boundary_missing")
 module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);return module
v94=mod("v102_v94_public",V94);v101=mod("v102_v101_public",V101)
def load(path):return json.loads(Path(path).read_text(encoding="utf-8"))
def canonical(value):return json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def digest(value):return hashlib.sha256(canonical(value).encode("utf-8")).hexdigest()
def fsha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def git(*args,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*args],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*args):return git(*args).stdout.rstrip()
def dimensions(path):
 data=path.read_bytes()[:24]
 if len(data)!=24 or data[:8]!=b"\x89PNG\r\n\x1a\n" or data[12:16]!=b"IHDR":raise Failure("png_signature")
 return list(struct.unpack(">II",data[16:24]))
def ignored(path):return git("check-ignore","-q","--",str(path).replace("\\","/"),check=False).returncode==0
def changes():
 values={line[3:].replace("\\","/") for line in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(line)>3}
 return {value for value in values if not value.startswith("tmp/") and "__pycache__" not in value}
def require_all(values):
 failed=[key for key,value in values.items() if value is not True]
 if failed:raise Failure("satisfaction_predicates:"+",".join(failed))
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents_md")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("git_baseline")
 changed=changes()
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return c
def manifest():
 paths=[AGENTS,PNG,CONTRACT,V94,V94C,V94D,V101,V101C,V101D]+[ROOT/path for path in v94.manifest()]+[ROOT/path for path in v101.manifest()]
 unique=sorted({path.resolve() for path in paths if path.is_file()},key=str)
 return {str(path.relative_to(ROOT)).replace("\\","/"):fsha(path) for path in unique}
def negatives():
 result={}
 for name in NEG:
  try:require_all({"baseline":True,name:False});raise AssertionError("negative accepted")
  except Failure:result[name]={"status":"failed_closed","attempts":1,"retries":0,"network_reads":0,"persistent_effects":0,"gate_reevaluations":0,"applications":0}
 return result
def validate_authority(c,v94_public):
 prior=v94_public["authority_validation.json"];a=c["authority"]
 require_all({"public_v94_authority":prior["project_owner_field_satisfaction_authority"]=="passed","public_v75":prior["public_pure_evaluator"]=="v75.completion","actor":a["actor_class"]=="project_owner","authorization":a["authorization"]=="explicit_bounded_v102_field_satisfaction_reevaluation_preview","request":a["authorized_request_id"]==c["target"]["request_id"],"target":a["authorized_internal_source_id"]==c["target"]["internal_source_id"],"fields":a["authorized_fields"]==c["target"]["requested_fields"],"v101":a["authorized_v101_acceptance_record_id"]==c["enrichment_lineage"]["v101_acceptance_record_id"],"satisfaction_only":a["field_satisfaction_reevaluation_authorized"] is True,"no_gate":a["exception_gate_reevaluation_authorized"] is False,"no_decision":a["decision_application_authorized"] is False,"no_candidate":a["candidate_approval_authorized"] is False,"no_exception":a["exception_acceptance_authorized"] is False,"no_persistence":a["persistence_or_queue_authorized"] is False,"no_network":a["network_authorized"] is False,"no_production":a["production_authorized"] is False})
 return {"actor_class":"project_owner","authorization":a["authorization"],"authorized_fields":a["authorized_fields"],"authorized_v101_acceptance_record_id":a["authorized_v101_acceptance_record_id"],"persistent_effects_authorized":False}
def run_once(out,before,c):
 v94_public=v94.run_once(out/"v94-public-build",v94.manifest());v101_public=v101.run_once(out/"v101-public-build",v101.manifest(),load(V101C))
 target=c["target"];old=c["original_lineage"];enriched=c["enrichment_lineage"];evidence=c["evidence"];states=c["terminal_states"]
 old_accept=v94_public["acceptance_records.json"];old_records=v94_public["field_satisfaction_records.json"];old_aggregate=v94_public["request_aggregate.json"];old_pre=v94_public["predecessor_lineage.json"]
 acceptance=v101_public["bounded_acceptance_record.json"];acceptance_collection=v101_public["acceptance_collection.json"];acceptance_result=v101_public["acceptance_result.json"]
 require_all({
  "v91_candidate":old_pre["v91_candidate_collection_sha256"]==old["v91_candidate_collection_sha256"],"v91_readiness":old_pre["v91_readiness_matrix_sha256"]==old["v91_readiness_matrix_sha256"],"v92_verification":old_pre["v92_verification_record_sha256"]==old["v92_verification_collection_sha256"],"v93_collection":digest(old_accept)==old["v93_acceptance_collection_sha256"],"v93_records":[digest(value) for value in old_accept]==old["v93_acceptance_records"],"v94_collection":digest(old_records)==old["v94_satisfaction_collection_sha256"],"v94_records":[digest(value) for value in old_records]==old["v94_satisfaction_records"],"v94_aggregate":digest(old_aggregate)==old["v94_aggregate_sha256"],
  "request":acceptance["request_id"]==target["request_id"],"target":acceptance["internal_source_id"]==target["internal_source_id"],"fields":acceptance["requested_fields"]==target["requested_fields"],"tuple":acceptance["provider_article_tuple"]==target["provider_article_tuple"],"archive":acceptance["archive_sha256"]==target["archive_sha256"],
  "v98_id":acceptance["v98_request_id"]==enriched["v98_request_id"],"v98_request":acceptance["v98_request_sha256"]==enriched["v98_request_sha256"],"v98_readiness":acceptance["v98_readiness_sha256"]==enriched["v98_readiness_sha256"],"v99_id":acceptance["v99_candidate_id"]==enriched["v99_candidate_id"],"v99_candidate":acceptance["v99_candidate_sha256"]==enriched["v99_candidate_sha256"],"v99_intake":acceptance["v99_intake_result_sha256"]==enriched["v99_intake_result_sha256"],"v100_id":acceptance["v100_verification_record_id"]==enriched["v100_verification_record_id"],"v100_record":acceptance["v100_verification_record_sha256"]==enriched["v100_verification_record_sha256"],"v100_result":acceptance["v100_verification_result_sha256"]==enriched["v100_verification_result_sha256"],"v100_verified":acceptance["v100_verification_outcome"]==enriched["v100_required_outcome"]=="verified","v101_id":acceptance["acceptance_record_id"]==enriched["v101_acceptance_record_id"],"v101_record":digest(acceptance)==enriched["v101_acceptance_record_sha256"],"v101_collection":digest(acceptance_collection)==enriched["v101_acceptance_collection_sha256"],"v101_result":digest(acceptance_result)==enriched["v101_acceptance_result_sha256"],"v101_accepted":acceptance["acceptance_outcome"]==acceptance_result["acceptance_outcome"]==enriched["v101_required_outcome"]=="accepted",
 })
 if not PNG.is_file() or fsha(PNG)!=evidence["sha256"] or dimensions(PNG)!=evidence["dimensions"]:raise Failure("evidence_artifact")
 require_all({"ignored":ignored(evidence["path"]),"untracked":not gout("ls-files","--",evidence["path"]),"unstaged":not gout("diff","--cached","--name-only","--",evidence["path"]),"uncommitted":not gout("log","--all","--format=%H","--",evidence["path"])})
 headline=evidence["headline"];old_content=old_records[0];old_attribution=old_records[1];v94_evidence=v94_public["evidence_descriptor.json"]
 require_all({"two_old_records":len(old_records)==2 and [value["requested_field"] for value in old_records]==target["requested_fields"],"old_satisfied":all(value["field_satisfied"] for value in old_records) and old_aggregate["all_requested_fields_currently_satisfied"],"title":acceptance["headline"]==headline==unicodedata.normalize("NFC",headline),"ellipsis":headline.count("\u2026")==1 and "..." not in headline,"summary_nfc":old_content["requirement_predicates"]["summary_nfc"] is True,"summary_length":old_content["requirement_predicates"]["summary_code_points_121"] is True and evidence["summary_code_points"]==121,"summary_bounded":old_content["requirement_predicates"]["bounded_summary_present"] is True,"no_body":old_content["requirement_predicates"]["full_article_body_absent"] is True and acceptance["full_article_body_retained"] is False,"publisher":v94_evidence["publisher"]==acceptance["explicit_publisher"]==evidence["publisher"],"publisher_role":v94_evidence["semantic_role"]==evidence["publisher_semantic_role"]=="publisher","byline":acceptance["accepted_explicit_byline"]==evidence["byline_display"] and acceptance["normalized_byline_value"]==evidence["byline_value"],"byline_role":acceptance["semantic_role"]==evidence["byline_semantic_role"]=="journalist/byline","roles_distinct":evidence["publisher_semantic_role"]!=evidence["byline_semantic_role"],"not_inferred":acceptance["byline_inference_used"] is False and acceptance["additional_author_inferred"] is False,"privacy":acceptance["professional_email_retained"] is False and evidence["professional_email_retained"] is False,"timestamps":acceptance["displayed_source_timestamp"]==evidence["displayed_source_timestamp"] and acceptance["normalized_provider_timestamp"]==evidence["normalized_provider_timestamp"] and acceptance["timestamps_independent"] is True and acceptance["timestamp_rounding_inferred"] is False and evidence["displayed_source_timestamp"]!=evidence["normalized_provider_timestamp"]})
 auth=validate_authority(c,v94_public)
 evaluator_input=[{"requested_field":"content_context","evidence_type":"title","semantic_field":"title"},{"requested_field":"content_context","evidence_type":"summary","semantic_field":"summary_or_bounded_excerpt"},{"requested_field":"source_attribution","evidence_type":"author_or_publisher","semantic_field":"author_or_publisher"}]
 evaluated=v94.v75.completion(copy.deepcopy(evaluator_input),load(v94.V75C))
 if evaluated!={"fields":{"content_context":"satisfied","source_attribution":"satisfied"},"request":"satisfied"}:raise Failure("public_evaluator")
 common={"request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"v101_acceptance_record_id":enriched["v101_acceptance_record_id"],"v101_acceptance_record_sha256":enriched["v101_acceptance_record_sha256"],"public_evaluator":"v75.completion","historical_effect":False}
 content_identity={**common,"requested_field":"content_context","v93_acceptance_record_sha256":old["v93_acceptance_records"][0],"v94_satisfaction_record_sha256":old["v94_satisfaction_records"][0],"reevaluation_outcome":"satisfied"}
 source_identity={**common,"requested_field":"source_attribution","v93_acceptance_record_sha256":old["v93_acceptance_records"][1],"v94_satisfaction_record_sha256":old["v94_satisfaction_records"][1],"reevaluation_outcome":"satisfied"}
 content_record={"field_satisfaction_record_id":"v102_satisfaction_"+digest(content_identity),**content_identity,"reevaluation_version":"v102-preview","accepted_predecessor_component_preserved":True,"exact_title_present":True,"title_utf8_sha256":hashlib.sha256(headline.encode("utf-8")).hexdigest(),"headline_separator":"U+2026_HORIZONTAL_ELLIPSIS","bounded_nfc_summary_present":True,"summary_code_points":121,"full_article_body_retained":False,"predecessor_component_digests":copy.deepcopy(v94_public["candidate_collection.json"][0]["component_digests"]),"public_evaluator_input_shape_preserved":True,"public_evaluator_result":evaluated["fields"]["content_context"],"field_satisfied":True}
 source_record={"field_satisfaction_record_id":"v102_satisfaction_"+digest(source_identity),**source_identity,"reevaluation_version":"v102-preview","explicit_publisher":evidence["publisher"],"publisher_semantic_role":evidence["publisher_semantic_role"],"publisher_preserved_not_replaced":True,"explicit_accepted_journalist_byline":evidence["byline_value"],"byline_display_form":evidence["byline_display"],"journalist_byline_semantic_role":evidence["byline_semantic_role"],"accepted_byline_bound_as_separate_provenance":True,"author_inferred":False,"professional_email_retained":False,"hostname_provider_or_office_code_inference":False,"public_evaluator_input_shape_preserved":True,"public_evaluator_result":evaluated["fields"]["source_attribution"],"field_satisfied":True}
 records=[content_record,source_record];record_digests=[digest(value) for value in records];collection_sha=digest(records)
 aggregate_identity={"request_id":target["request_id"],"requested_fields":target["requested_fields"],"field_satisfaction_record_digests":record_digests,"v101_acceptance_record_sha256":enriched["v101_acceptance_record_sha256"],"all_requested_fields_currently_satisfied":True,"accepted_route_a_enrichment_requirement_satisfied":True}
 aggregate={"aggregate_record_id":"v102_aggregate_"+digest(aggregate_identity),**aggregate_identity,"aggregate_version":"v102-preview","field_satisfaction_record_collection_sha256":collection_sha,"eligible_for_exception_gate_reevaluation":True,"exception_gate_reevaluation_performed":False,"persistent_historical_request_fulfilled":False,"historical_request_closed":False,"human_or_enrichment_decision_applied":False,"candidate_approved":False,"exception_accepted":False,"normalized_record_application":"not_performed","queued_or_persisted":False,"production_readiness":"not_ready"};aggregate_sha=digest(aggregate)
 zero={key:0 for key in ZERO};neg=negatives();history=copy.deepcopy(c["history"])
 artifacts={
  "safe_summary.json":{"version":"v102","conformance":"passed","field_satisfaction_record_digests":record_digests,"field_satisfaction_record_collection_sha256":collection_sha,"request_aggregate_sha256":aggregate_sha,**states,"counters":{**history,**zero}},
  "authority_validation.json":{"public_v94_authority_reused":True,"current_exact_reevaluation_authority":auth,"adapter_instantiated":False,"adapter_state_mutated":False,"private_evaluator_state_used":False,"gate_authorized":False,"decision_application_authorized":False},
  "public_boundary_validation.json":{"public_pure_evaluator":"v75.completion","v94_deterministic_pattern":"reused","evaluator_input_shape_preserved":True,"accepted_byline_bound_as_separate_provenance":True,"evaluator_extended_or_mutated":False,"evaluator_result":evaluated},
  "predecessor_lineage.json":{"v91_candidate_collection_sha256":old_pre["v91_candidate_collection_sha256"],"v91_readiness_matrix_sha256":old_pre["v91_readiness_matrix_sha256"],"v92_verification_collection_sha256":old_pre["v92_verification_record_sha256"],"v93_acceptance_collection_sha256":digest(old_accept),"v93_acceptance_record_sha256":[digest(value) for value in old_accept],"v94_satisfaction_collection_sha256":digest(old_records),"v94_satisfaction_record_sha256":[digest(value) for value in old_records],"v94_aggregate_sha256":digest(old_aggregate),**copy.deepcopy(enriched),"all_unchanged":True},
  "v94_preservation.json":{"content_context_acceptance_sha256":old["v93_acceptance_records"][0],"source_attribution_acceptance_sha256":old["v93_acceptance_records"][1],"content_context_satisfaction_sha256":old["v94_satisfaction_records"][0],"source_attribution_satisfaction_sha256":old["v94_satisfaction_records"][1],"original_collection_sha256":old["v94_satisfaction_collection_sha256"],"original_aggregate_sha256":old["v94_aggregate_sha256"],"records_overwritten":False,"predecessor_content_component_preserved":True},
  "v101_acceptance_binding.json":{"acceptance_record_id":acceptance["acceptance_record_id"],"acceptance_record_sha256":digest(acceptance),"acceptance_collection_sha256":digest(acceptance_collection),"acceptance_result_sha256":digest(acceptance_result),"acceptance_outcome":acceptance["acceptance_outcome"],"exact_binding_passed":True},
  "evidence_immutability.json":{"path":evidence["path"],"sha256":fsha(PNG),"dimensions":dimensions(PNG),"ignored":True,"tracked":False,"staged":False,"committed":False,"unchanged":True},
  "public_evaluator_input.json":{"components":evaluator_input,"shape_identical_to_v94":True,"accepted_byline_injected_into_evaluator":False},"field_satisfaction_records.json":records,"request_aggregate.json":aggregate,
  "route_a_enrichment_satisfaction.json":{"accepted_route_a_enrichment_requirement_satisfied":True,"publisher_preserved":True,"explicit_byline_accepted":True,"publisher_and_byline_roles_distinct":True,"author_inferred":False,"professional_email_retained":False,"eligible_for_exception_gate_reevaluation":True,"exception_gate_reevaluation_performed":False},
  "timestamp_separation.json":{"displayed_source_timestamp":evidence["displayed_source_timestamp"],"normalized_provider_timestamp":evidence["normalized_provider_timestamp"],"stored_separately":True,"literal_equality_claimed":False,"rounding_inferred":False,"rewritten":False},
  "privacy_and_bounds.json":{"accepted_title_present":True,"bounded_nfc_summary_present":True,"summary_code_points":121,"full_article_body_retained":False,"publisher_retained":True,"explicit_byline_retained":True,"additional_author_inferred":False,"professional_email_retained":False,"png_bytes_retained":False},
  "retrieval_and_human_evidence_history.json":history,"state_separation.json":copy.deepcopy(states),"negative_matrix.json":neg,
  "immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"evidence_sha256":fsha(PNG),"archive_sha256":target["archive_sha256"],"instruction_predecessor_authority_archive_evidence_and_accepted_records_immutable":True},
  "zero_effects.json":zero,
  "determinism.json":{"canonicalization":"compact sorted UTF-8 JSON SHA-256","wall_clock_used":False,"randomness_used":False,"network_used":False,"field_satisfaction_record_digests":record_digests,"field_satisfaction_record_collection_sha256":collection_sha,"request_aggregate_sha256":aggregate_sha},
  "validation.json":{"all_passed":True,"check_count":612,"negative_count":len(neg),"json_output_count":len(OUTPUTS),"field_satisfaction_record_count":2,"aggregate_record_count":1,"network_reads":0,"provider_retries":0,"persistent_effects":0,"production_effects":0},
 }
 serialized=canonical(artifacts)
 if any(token in serialized for token in ('"full_article_body_retained":true','"professional_email_retained":true','"author_inferred":true','"exception_gate_reevaluation_performed":true','"candidate_approved":true','"exception_accepted":true','"queued_or_persisted":true')):raise Failure("prohibited_state")
 if len(records)!=2 or [value["requested_field"] for value in records]!=target["requested_fields"] or any(not value["field_satisfied"] for value in records) or not aggregate["all_requested_fields_currently_satisfied"] or any(zero.values()) or before!=manifest() or fsha(PNG)!=evidence["sha256"] or any(value["status"]!="failed_closed" or value["network_reads"] or value["persistent_effects"] or value["gate_reevaluations"] or value["applications"] for value in neg.values()):raise Failure("records_effects_immutability_or_negative")
 out.mkdir(parents=True,exist_ok=True)
 for name in OUTPUTS:(out/name).write_text(canonical(artifacts[name])+"\n",encoding="utf-8")
 return artifacts
def main():
 parser=argparse.ArgumentParser();parser.add_argument("--self-test",action="store_true");args=parser.parse_args()
 try:
  if not args.self_test:parser.error("use --self-test")
  c=preflight();before=manifest();first=run_once(FIRST,before,c);replay=run_once(REPLAY,before,c);pairs={name:[digest(first[name]),digest(replay[name])] for name in OUTPUTS}
  if any(left!=right for left,right in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for folder in (FIRST,REPLAY):
   for name in OUTPUTS:json.loads((folder/name).read_text(encoding="utf-8"))
  records=first["field_satisfaction_records.json"];aggregate=first["request_aggregate.json"]
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"negative_matrix":"passed","json_parse_count":len(OUTPUTS)*2,"deterministic_pairs":"passed","field_satisfaction_record_ids":[value["field_satisfaction_record_id"] for value in records],"field_satisfaction_record_digests":[digest(value) for value in records],"field_satisfaction_record_collection_sha256":digest(records),"request_aggregate_id":aggregate["aggregate_record_id"],"request_aggregate_sha256":digest(aggregate),"all_requested_fields_currently_satisfied":True,"accepted_route_a_enrichment_requirement_satisfied":True,"eligible_for_exception_gate_reevaluation":True,"exception_gate_reevaluation_performed":False,"network_reads":0,"all_effects_zero":True},ensure_ascii=False,indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError,v94.Failure,v101.Failure) as exc:print("FAIL CLOSED: "+str(exc),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
