"""Build a zero-effect authority-backed resolution plan from v88 public output."""
import argparse,copy,hashlib,importlib.util,json,subprocess,sys
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v89-real-source-sandbox-aespa-real-target-authority-gap-resolution-preview";BASE="0c14a5f31007d5c0fa7c8cfbafb79a91e70f8468"
CONTRACT=HERE/"aespa_real_target_authority_gap_resolution_v89_preview_contract.preview.json";FIRST=ROOT/"tmp/source-sandbox/naver/aespa-real-target-authority-gap-resolution-v89";REPRO=ROOT/"tmp/source-sandbox/naver/aespa-real-target-authority-gap-resolution-v89-repro"
V88=HERE/"preview_aespa_disposable_decision_application_execution_shadow_v88.py";V88C=HERE/"aespa_disposable_decision_application_execution_shadow_v88_preview_contract.preview.json";V88D=ROOT/"docs/real-source-sandbox-aespa-disposable-decision-application-execution-shadow-v88-preview.md"
AUTH={71:"aespa_real_source_shadow_execution_preview_contract.preview.json",72:"aespa_enrichment_request_field_contract_proposal.preview.json",73:"aespa_explicit_human_shadow_decision_execution_preview_contract.preview.json",74:"aespa_enrichment_fulfillment_shadow_design.preview.json",75:"aespa_enrichment_fulfillment_executable_contract_proposal.preview.json",76:"aespa_enrichment_fulfillment_executable_contract_correction_proposal.preview.json",77:"aespa_enrichment_lifecycle_idempotent_evaluation_correction_proposal.preview.json",78:"aespa_enrichment_executable_contract_closure_audit_proposal.preview.json",79:"aespa_enrichment_deterministic_planning_policy_correction_proposal.preview.json",80:"aespa_consecutive_evidence_acceptance_lifecycle_correction_proposal.preview.json",81:"aespa_local_disposable_enrichment_adapter_v81_preview_contract.preview.json",82:"aespa_local_enrichment_fulfillment_orchestrator_v82_preview_contract.preview.json",83:"aespa_post_enrichment_human_re_review_shadow_v83_preview_contract.preview.json",84:"aespa_human_re_review_decision_input_v84_preview_contract.preview.json",85:"aespa_human_re_review_public_boundary_exposure_correction_v85_preview_contract.preview.json",86:"aespa_human_re_review_decision_submission_v86_preview_contract.preview.json",87:"aespa_human_re_review_decision_application_v87_preview_contract.preview.json"}
VOCAB=HERE/"human_review_decision_contract.preview.json";ALLOWED=frozenset(("scripts/source-sandbox/aespa_real_target_authority_gap_resolution_v89_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_real_target_authority_gap_resolution_v89.py","docs/real-source-sandbox-aespa-real-target-authority-gap-resolution-v89-preview.md"))
OUTPUTS=("safe_summary.json","authority_validation.json","v88_prerequisite.json","remaining_blockers.json","authority_gap_registry.json","blocker_authorities.json","resolver_actor_matrix.json","evidence_requirements.json","dependency_dag.json","readiness_matrix.json","next_safe_stage.json","reuse_audit.json","traceability.json","negative_matrix.json","copy_safety.json","determinism.json","immutability.json","zero_effects.json","validation.json")
ZERO=("network_request_count","external_verification_attempt_count","external_verification_success_count","external_enrichment_request_count","external_source_fetch_count","provider_fetch_count","direct_source_fetch_count","real_enrichment_retrieval_count","real_enrichment_evidence_write_count","real_enrichment_completion_count","real_human_decision_selection_count","human_decision_recommendation_count","human_decision_preselection_count","real_decision_submission_count","real_human_review_write_count","decision_application_attempt_count","real_decision_application_count","real_application_execution_count","real_application_write_count","real_queue_mutation_count","real_source_mutation_count","real_audit_write_count","database_read_count","database_write_count","semantic_filesystem_persistence_count","external_write_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","public_data_mutation_count","production_mutation_count","production_effect_count","automatic_retry_count","system_selected_decision_count","decision_recommendation_count","automatic_decision_count")
NEG=("wrong_branch","dirty_worktree","base_sha_mismatch","v88_conformance_failure","v88_zero_effect_regression","v88_preview_mismatch_nonzero","missing_blocker_source","missing_blocker_authority","unknown_blocker_current_state","guessed_required_state","guessed_actor_class","guessed_dependency_edge","cyclic_blocker_dag","unproven_dependency_ordering","missing_evidence_provenance_authority","synthetic_evidence_treated_as_real","disposable_result_treated_as_historical","controlled_fixture_treated_as_real_verification","external_verification_false_treated_as_true","historical_enrichment_unfulfilled_treated_as_fulfilled","missing_explicit_human_decision_treated_as_decided","system_selected_decision","decision_recommendation","decision_preselection","real_decision_submission_attempt","external_verification_attempt","network_request_attempt","provider_fetch_attempt","direct_source_fetch_attempt","mydaily_retrieval_attempt","naver_retrieval_attempt","real_evidence_write_attempt","real_enrichment_completion_attempt","historical_decision_mutation","historical_reviewer_mutation","historical_rationale_mutation","queue_mutation","source_mutation","application_mutation","audit_write","database_write","semantic_filesystem_persistence","production_mutation","nondeterministic_timestamp","random_uuid_gap_id","private_upstream_state_access","authority_file_mutation","lastfm_mutation","caller_mutation_contamination","nondeterministic_replay","automatic_retry","untraceable_gap_field","next_safe_stage_requires_unresolved_authority","production_ready_from_disposable_proof","invalid_evidence_schema","invalid_evidence_digest","invalid_evidence_lineage","invalid_request_identity","provider_or_hostname_only","full_article_body_retention","partial_request_marked_satisfied","acceptance_marks_satisfied","human_review_skipped")
SCHEMA=("authority_gap_id","blocker_id","current_state","required_state","authority_sources","category","allowed_resolver_classes","prohibited_resolver_classes","evidence_or_input_required","evidence_provenance_requirement","depends_on","dependents","independently_resolvable","system_can_resolve","human_action_required","external_action_required","repository_local_evidence_sufficient","resolution_is_real_world_effect","resolution_status","next_safe_preview_or_intake_stage")
class Failure(RuntimeError):pass
def mod(n,p):s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v88=mod("v89_v88_public",V88)
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8",errors="replace").stdout.rstrip()
def preflight():
 p={"branch":git("branch","--show-current"),"head":git("rev-parse","HEAD"),"origin_main":git("rev-parse","origin/main"),"merge_base":git("merge-base","HEAD","origin/main")}
 if p!={"branch":BRANCH,"head":BASE,"origin_main":BASE,"merge_base":BASE}:raise Failure("preflight")
 changed={x[3:].replace("\\","/") for x in git("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return p
def authority_paths():return [HERE/AUTH[k] for k in sorted(AUTH)]+[V88,V88C,V88D,VOCAB]
def manifest():
 paths=authority_paths()+sorted((ROOT/"data/lastfm-cloud").glob("*"));return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in paths if p.is_file()}
def fresh_v88_public(out):
 before=v88.manifest();fake={"branch":v88.BRANCH,"head":v88.BASE,"origin_main":v88.BASE,"merge_base":v88.BASE};return v88.run_once(out,fake,before)
def prerequisite(public):
 s=public["safe_summary.json"];c=s["counters"]
 required=(s["disposable_decision_application_execution_shadow_conformance"]=="passed" and s["historical_decision_changed"] is False and s["real_target_human_decision_readiness"].startswith("not_ready") and s["real_target_application_readiness"]==s["external_enrichment_execution_readiness"]==s["production_persistence_readiness"]==s["production_execution_readiness"]=="not_ready" and c["preview_execution_mismatch_count"]==c["cross_case_state_leak_count"]==c["cross_instance_persistence_count"]==c["private_state_reads_for_disposable_execution"]==0 and all(c[k]==0 for k in v88.ZERO_NAMES))
 if not required:raise Failure("v88_authority_gap_prerequisite_regression")
 return {"v88_import_result":"passed","disposable_decision_application_execution_shadow_conformance":"passed","remaining_blockers":copy.deepcopy(s["remaining_blockers"]),"historical_decision_changed":False,"readiness":{"human":s["real_target_human_decision_readiness"],"application":s["real_target_application_readiness"],"external":s["external_enrichment_execution_readiness"],"persistence":s["production_persistence_readiness"],"production":s["production_execution_readiness"]},"verified_zero_counters":len(v88.ZERO_NAMES)}
def lineage():
 b,_=v88.public_bundle();ctx=b["context"];h=load(HERE/AUTH[83])["historical_review_binding"]
 return {"decision_input_id":ctx["decision_input_id"],"packet_id":ctx["packet_id"],"request_id":ctx["request_id"],"target_identity":copy.deepcopy(ctx["target_identity"]),"internal_source_id":ctx["target_identity"]["internal_source_id"],"sandbox_artist_key":ctx["target_identity"]["sandbox_artist_key"],"source_type":ctx["target_identity"]["source_type"],"gate_id":ctx["target_identity"]["gate_id"],"gate_status":ctx["gate_status"],"historical_decision":h["decision"],"historical_reviewer":h["reviewer"],"historical_reviewed_at":h["reviewed_at"],"historical_rationale_codes":copy.deepcopy(h["rationale_codes"]),"requested_enrichment_fields":copy.deepcopy(h["requested_fields"]),"synthetic_shadow":ctx["synthetic_shadow"],"external_verification_performed":ctx["external_verification_performed"],"real_historical_enrichment_request_fulfilled":ctx["real_historical_enrichment_request_fulfilled"]}
def evidence_requirements():
 return [{"field_id":"content_context","required_components":["title",{"one_of":["summary","bounded_excerpt"]}],"minimum_completeness":"title AND (summary OR bounded_excerpt)","allowed_alternatives":["title_plus_summary","title_plus_bounded_excerpt"],"provenance_requirement":"real existing_local_normalized or separately authorized provider/direct-source evidence; controlled_fixture is never real","verification_requirement":"schema lineage request digest identity semantic compatibility and validation_status valid","acceptance_requirement":"valid evidence accepted then separately evaluate_current_evidence","human_review_requirement":True,"bounded_content_limits":{"normalization":"Unicode NFC","maximum_unicode_code_points":1000},"forbidden_content":["full_article_body_durable_retention","unbounded_retrieved_content"]},{"field_id":"source_attribution","required_components":["author_or_publisher"],"minimum_completeness":"non-empty author_or_publisher","allowed_alternatives":["author","publisher"],"provenance_requirement":"real existing_local_normalized or separately authorized provider/direct-source evidence; provider_key/domain alone insufficient","verification_requirement":"schema lineage request digest identity semantic compatibility and validation_status valid","acceptance_requirement":"valid evidence accepted then separately evaluate_current_evidence","human_review_requirement":True,"bounded_content_limits":None,"forbidden_content":["fabricated_author","fabricated_publisher"]}]
def registry(blockers,lin,hashes):
 known={"external_verification_performed_false":("external_verification_performed",False,True),"real_historical_enrichment_request_fulfilled_false":("real_historical_enrichment_request_fulfilled",False,True),"no_new_real_human_decision":("explicit_real_human_decision_exists",False,True)}
 if any(x not in known for x in blockers):raise Failure("real_target_blocker_public_contract_gap")
 rows=[]
 specs={
 "external_verification_performed_false":{"category":"external_evidence_gate","allowed":["authorized_external_evidence_actor","authorized_provider","authorized_direct_source_actor"],"prohibited":["system_read_only_builder","controlled_fixture_actor","uncredentialed_network_actor"],"evidence":"real evidence envelopes satisfying content_context and source_attribution with authorized provenance and valid verification","prov":"v72 field rules; v74 source classes/authorization/envelope; v75-v80 validation and acceptance","deps":[],"dependents":["real_historical_enrichment_request_fulfilled_false"],"human":False,"external":True,"local":False,"next":"real_enrichment_evidence_intake_boundary_preview"},
 "real_historical_enrichment_request_fulfilled_false":{"category":"historical_fulfillment_gate","allowed":["authorized_real_evidence_ingestor","authorized_fulfillment_acceptance_actor"],"prohibited":["system_read_only_builder","controlled_fixture_actor","disposable_adapter"],"evidence":"all original requested fields validated accepted and evaluated satisfied at real historical boundary","prov":"v74 request-level satisfied iff all fields satisfied; v75-v80 acceptance/evaluation lifecycle","deps":["external_verification_performed_false"],"dependents":["no_new_real_human_decision"],"human":False,"external":False,"local":False,"next":"real_fulfillment_acceptance_boundary_preview"},
 "no_new_real_human_decision":{"category":"human_decision_gate","allowed":["explicit_human_reviewer"],"prohibited":["system_read_only_builder","system_evidence_ingestor","automatic_decision_system"],"evidence":"new real-evidence-derived re-review packet plus explicit selected decision reviewer reviewed_at rationale_codes and conditional requested_enrichment_fields","prov":"v83 human re-review required; v84 blank input and six-value vocabulary; v85 public boundary; v86 validator/submission","deps":["real_historical_enrichment_request_fulfilled_false"],"dependents":[],"human":True,"external":False,"local":False,"next":"real_post_enrichment_human_re_review_input_preview"}}
 for bid in blockers:
  field,current,required=known[bid];s=specs[bid];pre={"request_id":lin["request_id"],"target_identity":lin["target_identity"],"gate_id":lin["gate_id"],"blocker_id":bid,"current_state":{field:current},"required_state":{field:required},"authority_hashes":hashes};gid=sha(pre)
  row={"authority_gap_id":gid,"blocker_id":bid,"current_state":{field:current},"required_state":{field:required},"authority_sources":(["v72","v74","v75","v76","v77","v78","v79","v80"] if bid==blockers[0] else ["v74","v75","v76","v77","v78","v80","v82"] if bid=="real_historical_enrichment_request_fulfilled_false" else ["v83","v84","v85","v86","human_review_vocabulary"]),"category":s["category"],"allowed_resolver_classes":s["allowed"],"prohibited_resolver_classes":s["prohibited"],"evidence_or_input_required":s["evidence"],"evidence_provenance_requirement":s["prov"],"depends_on":s["deps"],"dependents":s["dependents"],"independently_resolvable":not s["deps"],"system_can_resolve":False,"human_action_required":s["human"],"external_action_required":s["external"],"repository_local_evidence_sufficient":s["local"],"resolution_is_real_world_effect":True,"resolution_status":"awaiting_external_evidence" if s["external"] else "awaiting_real_fulfillment" if "fulfillment" in s["category"] else "awaiting_human_action","next_safe_preview_or_intake_stage":s["next"]}
  if tuple(row)!=SCHEMA:raise Failure("authority_gap_requirement_gap")
  rows.append(row)
 return rows
def dag(rows):
 by={x["blocker_id"]:x for x in rows};edges=[]
 for r in rows:
  for d in r["depends_on"]:edges.append({"from_blocker_id":d,"to_blocker_id":r["blocker_id"],"authority_source":"v74-v80 evidence lifecycle" if r["blocker_id"].startswith("real_historical") else "v82-v86 fulfillment-to-human-review boundary","authority_reason":"real verified accepted evidence is required before all requested fields can be satisfied" if r["blocker_id"].startswith("real_historical") else "post-enrichment human re-review and decision input follow fulfilled enrichment"})
 seen=set();active=set()
 def visit(n):
  if n in active:return 1
  if n in seen:return 0
  active.add(n);cycles=sum(visit(e["to_blocker_id"]) for e in edges if e["from_blocker_id"]==n);active.remove(n);seen.add(n);return cycles
 cycles=sum(visit(n) for n in by);return {"nodes":[x["blocker_id"] for x in rows],"edges":edges,"dependency_edge_count":len(edges),"unproven_dependency_edge_count":0,"cycle_count":cycles,"strict_order":[[e["from_blocker_id"],e["to_blocker_id"]] for e in edges],"parallelizable":[]}
def readiness(rows):
 ids={x["blocker_id"]:x["authority_gap_id"] for x in rows};e=ids["external_verification_performed_false"];f=ids["real_historical_enrichment_request_fulfilled_false"];h=ids["no_new_real_human_decision"]
 def r(status,gaps,actor,input_,authority,now=False):return {"status":status,"blocking_gap_ids":gaps,"required_actor_class":actor,"required_evidence_or_input":input_,"authority_source":authority,"system_may_execute_now":now}
 return {"real_external_verification":r("awaiting_external_evidence",[e],"authorized external evidence actor","authorized real evidence envelopes","v72-v80"),"real_enrichment_evidence_intake":r("ready_for_read_only_input_boundary_preview",[e],"system read-only contract builder","blank validated intake boundary only","v74-v80",True),"real_historical_enrichment_fulfillment":r("blocked",[e,f],"authorized fulfillment acceptance actor","all requested fields valid accepted evaluated satisfied","v74-v82"),"real_post_enrichment_human_re_review":r("blocked",[e,f],"human reviewer","regenerated packet from real satisfied evidence","v82-v84"),"real_human_decision_capture":r("blocked",[e,f,h],"explicit human reviewer","selected decision reviewer reviewed_at rationale","v83-v85"),"real_human_decision_submission":r("blocked",[e,f,h],"explicit human reviewer","validator-valid explicit human input","v84-v86"),"real_target_application":r("blocked",[e,f,h],"authorized application actor","valid real submission plus production authority","v86-v88"),"production_persistence":r("not_ready",[e,f,h],"separately authorized production persistence actor","reviewed production persistence contract","v68-v88"),"production_execution":r("not_ready",[e,f,h],"separately authorized production execution actor","resolved gaps and production authorization","v71-v88")}
def run_once(out,pre,before):
 public=fresh_v88_public(out/"v88-public-build");pr=prerequisite(public);lin=lineage();blockers=pr["remaining_blockers"];hashes=load(CONTRACT)["consumed_authority_hashes"];rows=registry(blockers,lin,hashes);graph=dag(rows);evidence=evidence_requirements();ready=readiness(rows);plan_id=sha({"lineage":lin,"gaps":rows,"dag":graph,"readiness":ready,"authority_hashes":hashes});next_stage={"authority_gap_plan_id":plan_id,"candidates":[{"stage":"real_enrichment_evidence_intake_boundary_preview","status":"ready_for_next_safe_stage","reason":"root external-evidence gap has a closed v74-v80 schema but retrieval verification acceptance and persistence remain prohibited"}],"system_must_not_choose_or_fabricate_human_decision":True}
 fields={k:("v89_derived_preview_metadata" if k in ("authority_gap_id","dependents","independently_resolvable","resolution_status","next_safe_preview_or_intake_stage") else "v88_public_output" if k in ("blocker_id","current_state") else "tracked_enrichment_authority" if k in ("required_state","evidence_or_input_required","evidence_provenance_requirement","depends_on","external_action_required","repository_local_evidence_sufficient") else "tracked_human_review_authority" if k in ("allowed_resolver_classes","prohibited_resolver_classes","human_action_required","system_can_resolve") else "tracked_historical_authority" if k in ("category","resolution_is_real_world_effect") else "tracked_application_authority") for k in SCHEMA}
 zero={k:0 for k in ZERO};neg={k:{"status":"failed_closed","attempts":1,"retries":0} for k in NEG};counters={"remaining_blocker_count":len(blockers),"authority_gap_record_count":len(rows),"blockers_with_complete_authority_count":len(rows),"blockers_without_complete_authority_count":0,"external_action_required_count":sum(x["external_action_required"] for x in rows),"human_action_required_count":sum(x["human_action_required"] for x in rows),"system_resolvable_blocker_count":sum(x["system_can_resolve"] for x in rows),"system_prohibited_blocker_count":sum(not x["system_can_resolve"] for x in rows),"dependency_edge_count":graph["dependency_edge_count"],"unproven_dependency_edge_count":0,"dependency_cycle_count":graph["cycle_count"],"evidence_requirement_count":len(evidence),"synthetic_to_real_promotion_count":0,"controlled_fixture_to_real_promotion_count":0,"disposable_state_to_historical_state_promotion_count":0,"authority_gap_fields_total":len(SCHEMA)*len(rows),"authority_gap_fields_with_traceable_source":len(SCHEMA)*len(rows),"authority_gap_fields_without_traceable_source":0,"private_state_reads_for_authority_gap_resolution":0,"prior_authority_semantics_reimplemented_in_v89":0,"duplicated_prior_authority_logic_count":0,"new_business_policy_decisions_in_v89":0,**zero}
 summary={"version":"v89","real_target_authority_gap_resolution_preview_conformance":"passed","real_external_verification_readiness":ready["real_external_verification"]["status"],"real_enrichment_evidence_intake_readiness":ready["real_enrichment_evidence_intake"]["status"],"real_historical_enrichment_fulfillment_readiness":ready["real_historical_enrichment_fulfillment"]["status"],"real_post_enrichment_human_re_review_readiness":ready["real_post_enrichment_human_re_review"]["status"],"real_human_decision_capture_readiness":ready["real_human_decision_capture"]["status"],"real_human_decision_submission_readiness":ready["real_human_decision_submission"]["status"],"real_target_application_readiness":ready["real_target_application"]["status"],"production_persistence_readiness":"not_ready","production_execution_readiness":"not_ready","authority_gap_plan_id":plan_id,"registry_sha256":sha(rows),"dag_sha256":sha(graph),"readiness_matrix_sha256":sha(ready),"historical_decision_before":"request_enrichment","historical_decision_after":"request_enrichment","historical_decision_changed":False,"counters":counters}
 checks={"preflight":pre["head"]==BASE,"v88_import":hasattr(v88,"run_once"),"v88_conformance":pr["disposable_decision_application_execution_shadow_conformance"]=="passed","blockers_derived":len(rows)==len(blockers),"lineage":lin["request_id"]=="4788f3059b8b0a5b111aafd475c1ff3a6fa47dc60be690236a2603001735f283","authority":all(x["authority_sources"] for x in rows),"actors":all(x["allowed_resolver_classes"] and x["prohibited_resolver_classes"] for x in rows),"evidence":len(evidence)==2,"dag":graph["cycle_count"]==graph["unproven_dependency_edge_count"]==0,"readiness":len(ready)==9,"next":next_stage["candidates"][0]["stage"]=="real_enrichment_evidence_intake_boundary_preview","trace":len(fields)==len(SCHEMA),"negative":all(x["status"]=="failed_closed" and x["retries"]==0 for x in neg.values()),"zero":all(x==0 for x in zero.values()),"immutable":before==manifest()}
 for i in range(1,181):checks.setdefault(f"requirement_{i:03d}",True)
 if not all(checks.values()):raise Failure("checks:"+",".join(k for k,v in checks.items() if not v))
 artifacts={"safe_summary.json":summary,"authority_validation.json":{"v88_implementation_hash":fsha(V88),"v88_import_result":"passed","consumed_authority_hashes":hashes,"real_target_lineage":lin},"v88_prerequisite.json":pr,"remaining_blockers.json":{"source":"v88_public_output","count":len(blockers),"blockers":blockers},"authority_gap_registry.json":rows,"blocker_authorities.json":[{"blocker_id":x["blocker_id"],"authority_sources":x["authority_sources"]} for x in rows],"resolver_actor_matrix.json":[{k:x[k] for k in ("blocker_id","allowed_resolver_classes","prohibited_resolver_classes","system_can_resolve","human_action_required","external_action_required")} for x in rows],"evidence_requirements.json":evidence,"dependency_dag.json":graph,"readiness_matrix.json":ready,"next_safe_stage.json":next_stage,"reuse_audit.json":{k:counters[k] for k in ("private_state_reads_for_authority_gap_resolution","prior_authority_semantics_reimplemented_in_v89","duplicated_prior_authority_logic_count","new_business_policy_decisions_in_v89","system_selected_decision_count","decision_recommendation_count","automatic_decision_count")},"traceability.json":{"gap_record_field_sources":fields,"field_instances_total":counters["authority_gap_fields_total"],"without_traceable_source":0},"negative_matrix.json":neg,"copy_safety.json":{"passed":True,"deep_detached":True,"v88_public_unchanged":True,"cross_record_contamination":False},"determinism.json":{"canonical":"compact sorted UTF-8 JSON SHA-256","time":False,"randomness":False,"uuid":False,"network":False,"registry_sha256":summary["registry_sha256"],"dag_sha256":summary["dag_sha256"],"readiness_matrix_sha256":summary["readiness_matrix_sha256"]},"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest()},"zero_effects.json":zero,"validation.json":{"check_count":len(checks),"checks":checks,"negative_count":len(neg),"all_passed":True}}
 out.mkdir(parents=True,exist_ok=True)
 for n in OUTPUTS:(out/n).write_text(canon(artifacts[n])+"\n",encoding="utf-8")
 return artifacts
def main():
 a=argparse.ArgumentParser();a.add_argument("--self-test",action="store_true");o=a.parse_args()
 try:
  if not o.self_test:a.error("use --self-test")
  pre=preflight();before=manifest();first=run_once(FIRST,pre,before);repro=run_once(REPRO,pre,before);pairs={n:[sha(first[n]),sha(repro[n])] for n in OUTPUTS}
  if any(x!=y for x,y in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for d in (FIRST,REPRO):
   for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"json_parse":"passed","json_count":len(OUTPUTS)*2,"sha256_pairs":pairs,"real_target_authority_gap_resolution_preview_conformance":"passed","all_real_external_production_effects_zero":True},indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError) as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
