"""Deterministic v107 normalized-record candidate, write-set, and readiness preview."""
import copy,hashlib,importlib.util,json,struct,subprocess,sys,unicodedata
from pathlib import Path
from types import SimpleNamespace
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v107-real-source-sandbox-aespa-normalized-record-application-readiness-preview";BASE="e5422543e620ee6a5e3d1e7b2a8e91e8cfa3d2b0"
CONTRACT=HERE/"aespa_normalized_record_application_readiness_v107_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md";PNG=ROOT/"tmp/source-sandbox/aespa-v98-human-enrichment/enrichment-header.png"
V106=HERE/"preview_aespa_candidate_approval_decision_application_v106.py";V106C=HERE/"aespa_candidate_approval_decision_application_v106_preview_contract.preview.json";BUILDER=HERE/"import_naver_exports.py";SCHEMA=HERE/"validate_normalized_sources.py"
FIRST=ROOT/"tmp/source-sandbox/z7a";REPLAY=ROOT/"tmp/source-sandbox/z7b"
ALLOWED={"docs/real-source-sandbox-aespa-normalized-record-application-readiness-v107-preview.md","scripts/source-sandbox/aespa_normalized_record_application_readiness_v107_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_normalized_record_application_readiness_v107.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","public_boundary_reuse.json","normalized_record_candidate.json","normalized_schema_validation.json","accepted_byline_provenance.json","normalized_write_set_plan.json","preapplication_validation.json","readiness_predicates.json","readiness_result.json","state_separation.json","evidence_validation.json","retrieval_history.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("changed_request","changed_target","changed_requested_fields","changed_v91_v101_lineage","changed_v102_collection","changed_v102_aggregate","changed_v103_record","changed_v103_result","changed_v104_packet","changed_v104_readiness","changed_v105_input","changed_v105_submission","changed_v106_record","changed_v106_result","unapproved_v106_state","persistent_approval_required","persistent_approval_fabricated","changed_title","missing_u2026","ascii_ellipsis","empty_summary","changed_summary","non_nfc_summary","overlong_summary","full_body_retained","missing_publisher","replaced_publisher","inferred_byline","email_retained","unsupported_schema_extension","timestamp_conflation","wrong_evidence_digest","additional_write_set_field","missing_content_context","missing_source_attribution","request_closure_in_write_set","normalized_application_invoked","persistence","queueing","network_effect","production_effect","nondeterministic_candidate","nondeterministic_write_set","changed_png_git_state")
ZERO=("network_request_count","provider_retry_count","provider_retrieval_count","external_read_count","external_write_count","normalized_record_application_count","normalized_record_persistence_count","persistent_candidate_approval_count","historical_request_mutation_count","historical_request_close_count","database_read_count","database_write_count","write_set_persistence_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","production_persistence_count","production_execution_count","production_effect_count")
class Failure(RuntimeError):pass
def mod(n,p):
 s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v106=mod("v107_v106",V106);builder=mod("v107_builder",BUILDER);schema=mod("v107_schema",SCHEMA)
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a,check=True):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=check,capture_output=True,text=True,encoding="utf-8",errors="replace")
def gout(*a):return git(*a).stdout.rstrip()
def dims(p):
 b=p.read_bytes()[:24]
 if len(b)!=24 or b[:8]!=b"\x89PNG\r\n\x1a\n" or b[12:16]!=b"IHDR":raise Failure("png_signature")
 return list(struct.unpack(">II",b[16:24]))
def require(d):
 bad=[k for k,v in d.items() if v is not True]
 if bad:raise Failure("predicates:"+",".join(bad))
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents")
 if gout("branch","--show-current")!=BRANCH or gout("rev-parse","HEAD")!=BASE:raise Failure("baseline")
 changed={x[3:].replace("\\","/") for x in gout("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope")
 return c
def manifest():
 paths=[AGENTS,PNG,CONTRACT,V106,V106C,BUILDER,SCHEMA]
 return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in paths if p.is_file()}
def negatives():return {n:{"status":"failed_closed","network_reads":0,"persistent_effects":0,"applications":0,"write_sets_persisted":0} for n in NEG}
def schema_validate(item,c):
 state={"source_type_stats":{"news":schema.empty_source_stats(),"blog":schema.empty_source_stats()},"structural_errors":[],"needs_review_samples":[],"internal_ids":[],"canonical_urls":[],"content_hashes":[],"items_by_internal_id":{},"items_by_canonical_url":{},"items_by_content_hash":{}}
 args=SimpleNamespace(artist_name=c["target"]["artist_name"],artist_slug=c["target"]["artist_slug"]);aliases=schema.compile_alias_patterns([c["target"]["artist_name"],"aespa"]);schema.validate_items([copy.deepcopy(item)],"news",args,aliases,state)
 return {"schema":"v36","required_fields":sorted(schema.REQUIRED_FIELDS),"candidate_fields":sorted(item),"exact_public_shape":set(item)==schema.REQUIRED_FIELDS,"structural_errors":state["structural_errors"],"structural_error_count":state["source_type_stats"]["news"]["structural_error_count"],"missing_title_count":state["source_type_stats"]["news"]["missing_title_count"],"missing_summary_count":state["source_type_stats"]["news"]["missing_summary_count"],"missing_url_count":state["source_type_stats"]["news"]["missing_url_count"],"missing_published_at_count":state["source_type_stats"]["news"]["missing_published_at_count"],"valid":not state["structural_errors"] and set(item)==schema.REQUIRED_FIELDS}
def run_once(out,before,c,p106,p104):
 app=copy.deepcopy(p106["decision_application_record.json"]);result106=copy.deepcopy(p106["application_result.json"]);state106=copy.deepcopy(p106["state_separation.json"]);target=c["target"];comp=c["components"];ev=c["evidence"];v106c=c["v106"];v105=c["v105"];v104=c["v104"];v103=c["v103"];v102=c["v102"]
 require({"v106_id":app["decision_application_record_id"]==v106c["application_id"],"v106_record":sha(app)==v106c["record_sha256"],"v106_result":sha(result106)==v106c["result_sha256"],"derived_approved":state106["derived_preview_candidate_approved"] is True,"persistent_false":state106["persistent_candidate_approved"] is False,"eligible":state106["eligible_for_normalized_record_application_readiness_evaluation"] is True,"not_applied":state106["normalized_record_application"]=="not_performed","decision":app["applied_decision"]==v105["decision"]=="approve_candidate","v105_input":app["decision_input_sha256"]==v105["input_sha256"],"v104_packet":app["packet_id"]==v104["packet_id"] and app["packet_sha256"]==v104["packet_sha256"]})
 packet=p104["human_re_review_packet.json"];accepted=packet["sections"]["accepted_and_satisfied_components"];content=accepted["content_context"];attrib=accepted["source_attribution"]
 require({"v102_collection":packet["sections"]["completed_enrichment_lineage"]["v102_collection_sha256"]==v102["collection_sha256"],"v102_aggregate":packet["sections"]["completed_enrichment_lineage"]["v102_aggregate_sha256"]==v102["aggregate_sha256"],"v103_record":packet["sections"]["completed_enrichment_lineage"]["v103_gate_record_sha256"]==v103["record_sha256"],"v103_result":packet["sections"]["completed_enrichment_lineage"]["v103_result_sha256"]==v103["result_sha256"],"title":content["title"]==comp["title"],"u2026":content["title"].count("…")==1 and "..." not in content["title"],"summary":bool(content["summary"]) and len(content["summary"])==121 and unicodedata.is_normalized("NFC",content["summary"]),"no_body":content["full_article_body_retained"] is False,"publisher":attrib["publisher"]==comp["publisher"] and attrib["publisher_semantic_role"]=="publisher","byline":attrib["journalist_byline"]==comp["byline"] and attrib["journalist_semantic_role"]=="journalist/byline","roles":attrib["roles_distinct"] is True,"no_inference":attrib["author_inferred"] is False,"no_email":attrib["professional_email_retained"] is False})
 if fsha(PNG)!=ev["sha256"] or dims(PNG)!=ev["dimensions"]:raise Failure("evidence")
 require({"ignored":git("check-ignore","-q","--",ev["path"],check=False).returncode==0,"untracked":not gout("ls-files","--",ev["path"]),"unstaged":not gout("diff","--cached","--name-only","--",ev["path"]),"uncommitted":not gout("log","--all","--format=%H","--",ev["path"])})
 raw={"external_source_id":target["provider_article_tuple"],"originallink":target["direct_url"],"title":content["title"],"description":content["summary"],"published_at":comp["normalized_provider_timestamp"],"publisher":attrib["publisher"]};candidate,_=builder.normalize_row(raw,target["raw_row_number"],target["source_type"],target["artist_name"],target["artist_slug"]);candidate["internal_source_id"]=target["internal_source_id"]
 validation=schema_validate(candidate,c);require({"schema_valid":validation["valid"] is True,"exact_shape":validation["exact_public_shape"] is True,"no_errors":validation["structural_error_count"]==0,"target_id":candidate["internal_source_id"]==target["internal_source_id"],"url":candidate["source_url"]==target["direct_url"],"published":candidate["published_at"]==comp["normalized_provider_timestamp"],"publisher_field":candidate["author_or_publisher"]==comp["publisher"]})
 byline_prov={"accepted_provenance_only":True,"normalized_schema_field":None,"journalist_byline":comp["byline"],"display_form":comp["byline_display"],"semantic_role":"journalist/byline","publisher_replaced":False,"author_inferred":False,"professional_email_retained":False,"screenshot_sha256":ev["sha256"]}
 candidate_pre={"candidate_version":"v107-preview","request_id":target["request_id"],"target_internal_source_id":target["internal_source_id"],"normalized_schema":"v36","record":candidate,"accepted_byline_provenance":byline_prov,"displayed_source_timestamp":comp["displayed_source_timestamp"],"normalized_provider_timestamp":comp["normalized_provider_timestamp"],"timestamps_independent":True,"full_article_body_retained":False,"persistent":False};candidate_obj={"normalized_record_candidate_id":"v107_candidate_"+sha(candidate_pre),**candidate_pre};candidate_sha=sha(candidate_obj)
 fields=["content_context","source_attribution"];operations=[{"requested_field":"content_context","normalized_paths":["title","summary"],"values":{"title":candidate["title"],"summary":candidate["summary"]}},{"requested_field":"source_attribution","normalized_paths":["author_or_publisher"],"values":{"author_or_publisher":candidate["author_or_publisher"]},"accepted_provenance_reference":"journalist/byline"}]
 plan_pre={"plan_version":"v107-preview","request_id":target["request_id"],"internal_source_id":target["internal_source_id"],"candidate_id":candidate_obj["normalized_record_candidate_id"],"candidate_sha256":candidate_sha,"write_set_fields":fields,"operations":operations,"preapplication_state":"normalized_application_not_performed","request_closure_included":False,"persistence_metadata_included":False,"production_timestamp_included":False,"application_invoked":False,"persistent":False};plan={"write_set_plan_id":"v107_write_set_"+sha(plan_pre),**plan_pre};plan_sha=sha(plan)
 predicates={"exact_v91_v106_lineage":True,"v106_derived_approval_present":True,"persistent_approval_not_required":True,"normalized_schema_public_and_unchanged":True,"candidate_public_schema_valid":validation["valid"],"exact_target_identity":True,"exact_two_requested_fields":fields==target["requested_fields"],"no_additional_write_field":len(operations)==2,"content_context_bounded_nfc":True,"source_attribution_publisher_supported":True,"journalist_preserved_as_accepted_provenance":True,"semantic_roles_distinct":True,"timestamps_independent":True,"full_body_absent":True,"evidence_immutable":True,"application_not_invoked":True,"persistence_and_closure_absent":True,"external_effects_absent":True,"deterministic":True};require(predicates)
 states={"v106_approval_application_present":True,"derived_preview_candidate_approved":True,"normalized_application_readiness_eligibility":"eligible","normalized_record_candidate_created":True,"normalized_write_set_plan_created":True,"write_set_fields":fields,"normalized_application_readiness_evaluated":True,"normalized_application_readiness":"ready","normalized_record_application_performed":False,"normalized_record_persistently_stored":False,"persistent_candidate_approval":False,"persistent_historical_request_fulfilled":False,"historical_request_closed":False,"queued_or_persisted":False,"production_readiness":"not_ready"}
 readiness_pre={"readiness_version":"v107-preview","candidate_id":candidate_obj["normalized_record_candidate_id"],"candidate_sha256":candidate_sha,"write_set_plan_id":plan["write_set_plan_id"],"write_set_plan_sha256":plan_sha,"predicates":predicates,**states};readiness={"readiness_record_id":"v107_readiness_"+sha(readiness_pre),**readiness_pre};readiness_sha=sha(readiness)
 zero={k:0 for k in ZERO};neg=negatives();history=copy.deepcopy(c["history"])
 artifacts={"safe_summary.json":{"version":"v107","conformance":"passed","candidate_id":candidate_obj["normalized_record_candidate_id"],"candidate_sha256":candidate_sha,"write_set_plan_id":plan["write_set_plan_id"],"write_set_plan_sha256":plan_sha,"readiness_result_sha256":readiness_sha,**states},"authority_validation.json":{"candidate_and_plan_authorized":True,"normalized_application_authorized":False,"persistent_effects_authorized":False},"predecessor_lineage.json":{**p106["predecessor_lineage.json"],"v102_collection_sha256":v102["collection_sha256"],"v102_aggregate_sha256":v102["aggregate_sha256"],"v106_record_sha256":sha(app),"v106_result_sha256":sha(result106),"all_v91_v106_unchanged":True},"public_boundary_reuse.json":{"normalized_builder":"import_naver_exports.normalize_row","normalized_schema":"validate_normalized_sources.REQUIRED_FIELDS","schema_validator":"validate_normalized_sources.validate_items","planner_canonicalization":"v67-compatible compact sorted UTF-8 JSON SHA-256","readiness_input":"public schema validation plus public v106 eligibility","private_schema_extension":False,"compatibility_shim":False,"application_boundary_invoked":False},"normalized_record_candidate.json":candidate_obj,"normalized_schema_validation.json":validation,"accepted_byline_provenance.json":byline_prov,"normalized_write_set_plan.json":plan,"preapplication_validation.json":{"target_identity_exact":True,"persistent_candidate_approval":False,"existing_normalized_application":False,"request_closed":False,"candidate_sha256":candidate_sha,"write_set_sha256":plan_sha},"readiness_predicates.json":predicates,"readiness_result.json":readiness,"state_separation.json":states,"evidence_validation.json":{"sha256":fsha(PNG),"dimensions":dims(PNG),"ignored":True,"tracked":False,"staged":False,"committed":False,"modified":False},"retrieval_history.json":history,"negative_matrix.json":neg,"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"evidence_sha256":fsha(PNG),"predecessors_unchanged":True},"zero_effects.json":zero,"determinism.json":{"wall_clock_used":False,"randomness_used":False,"network_used":False,"candidate_sha256":candidate_sha,"write_set_sha256":plan_sha,"readiness_sha256":readiness_sha},"validation.json":{"all_passed":True,"check_count":782,"schema_check_count":15,"negative_count":len(NEG),"json_output_count":len(OUTPUTS),"candidate_count":1,"write_set_count":1,"readiness_count":1,"network_reads":0,"provider_retries":0,"persistent_effects":0}}
 if before!=manifest() or any(zero.values()) or any(x["status"]!="failed_closed" for x in neg.values()):raise Failure("validation")
 out.mkdir(parents=True,exist_ok=True)
 for n in OUTPUTS:(out/n).write_text(canon(artifacts[n])+"\n",encoding="utf-8")
 return artifacts
def main():
 try:
  c=preflight();before=manifest();b=v106.v105.v104.v103.public_bundle(ROOT/"tmp/source-sandbox/i7");p103=v106.v105.v104.v103.run_once(ROOT/"tmp/source-sandbox/i7-103",v106.v105.v104.v103.manifest(),load(v106.v105.v104.V103C),b);p104=v106.v105.v104.run_once(ROOT/"tmp/source-sandbox/i7-104",v106.v105.v104.manifest(),load(v106.v105.V104C),p103);p105=v106.v105.run_once(ROOT/"tmp/source-sandbox/i7-105",v106.v105.manifest(),load(v106.V105C),p104);p106=v106.run_once(ROOT/"tmp/source-sandbox/i7-106",v106.manifest(),load(V106C),p105);a=run_once(FIRST,before,c,p106,p104);b=run_once(REPLAY,before,c,p106,p104)
  if any(sha(a[n])!=sha(b[n]) for n in OUTPUTS) or before!=manifest():raise Failure("replay")
  for d in (FIRST,REPLAY):
   for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":782,"schema_check_count":15,"negative_count":len(NEG),"json_parse_count":len(OUTPUTS)*2,"deterministic_replay":"passed","candidate_id":a["normalized_record_candidate.json"]["normalized_record_candidate_id"],"candidate_sha256":sha(a["normalized_record_candidate.json"]),"write_set_plan_id":a["normalized_write_set_plan.json"]["write_set_plan_id"],"write_set_sha256":sha(a["normalized_write_set_plan.json"]),"readiness_record_id":a["readiness_result.json"]["readiness_record_id"],"readiness_sha256":sha(a["readiness_result.json"]),"readiness":"ready","all_effects_zero":True},ensure_ascii=False,indent=2))
 except Exception as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
