"""Offline v96 bounded human re-review packet readiness preview; no review or decision."""
import argparse,copy,hashlib,importlib.util,json,struct,subprocess,sys,unicodedata
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v96-real-source-sandbox-aespa-human-re-review-packet-readiness-preview";BASE="f9d2dd0b59d354d552b6c98426c2022f5046c14b"
CONTRACT=HERE/"aespa_human_re_review_packet_readiness_v96_preview_contract.preview.json";AGENTS=ROOT/"AGENTS.md"
V95=HERE/"preview_aespa_historical_request_fulfillment_v95.py";V95C=HERE/"aespa_historical_request_fulfillment_v95_preview_contract.preview.json";V95D=ROOT/"docs/real-source-sandbox-aespa-historical-request-fulfillment-v95-preview.md"
V83=HERE/"preview_aespa_post_enrichment_human_re_review_shadow_v83.py";V83C=HERE/"aespa_post_enrichment_human_re_review_shadow_v83_preview_contract.preview.json"
V84=HERE/"preview_aespa_human_re_review_decision_input_v84.py";V84C=HERE/"aespa_human_re_review_decision_input_v84_preview_contract.preview.json";V86C=HERE/"aespa_human_re_review_decision_submission_v86_preview_contract.preview.json";V72C=HERE/"aespa_enrichment_request_field_contract_proposal.preview.json"
FIRST=ROOT/"tmp/source-sandbox/v96a";REPRO=ROOT/"tmp/source-sandbox/v96b"
ALLOWED={"docs/real-source-sandbox-aespa-human-re-review-packet-readiness-v96-preview.md","scripts/source-sandbox/aespa_human_re_review_packet_readiness_v96_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_human_re_review_packet_readiness_v96.py"}
OUTPUTS=("safe_summary.json","authority_validation.json","predecessor_lineage.json","public_boundary_validation.json","human_re_review_packet.json","packet_schema_validation.json","packet_bounds_validation.json","readiness_predicates.json","packet_readiness_evaluation.json","decision_controls.json","retrieval_history.json","state_separation.json","negative_matrix.json","immutability.json","zero_effects.json","determinism.json","validation.json")
NEG=("agents_md_missing","agents_md_empty","agents_md_changed","agents_md_unloaded","wrong_base_commit","wrong_or_malformed_request_id","prior_62_character_request_id","wrong_internal_source_id","changed_provider","changed_source_type","changed_publication_time","wrong_requested_field_set","missing_requested_field","additional_requested_field","changed_candidate_collection_digest","verification_missing","verification_digest_changed","verification_not_verified","acceptance_missing","acceptance_digest_changed","acceptance_not_accepted","satisfaction_record_missing","satisfaction_record_duplicated","satisfaction_digest_changed","content_context_not_satisfied","source_attribution_not_satisfied","both_fields_not_satisfied","aggregate_digest_changed","aggregate_false","fulfillment_record_digest_changed","derived_fulfillment_not_fulfilled","persistent_request_already_fulfilled","historical_request_already_closed","human_re_review_eligibility_blocked","human_re_review_eligibility_pending","changed_raw_row","changed_archive_digest","changed_original_locator","changed_provider_locator","changed_provider_article_tuple","missing_screenshot","changed_screenshot_digest","changed_screenshot_dimensions","screenshot_no_longer_ignored","title_changed","summary_missing","summary_changed","summary_non_nfc","summary_wrong_length","full_article_body_supplied","publisher_missing","publisher_changed","wrong_attribution_semantic_role","fabricated_author_or_byline","retrieval_success_fabricated","automated_retrieval_failure_omitted","human_evidence_channel_omitted","human_evidence_channel_changed","required_packet_section_missing","unrelated_raw_row_included","screenshot_bytes_embedded","advertisement_or_unrelated_content_included","secret_credential_or_account_data_included","unsupported_decision_option","decision_option_preselected","recommendation_or_implied_decision_added","reviewer_identity_fabricated","human_review_marked_performed","human_decision_marked_captured","human_decision_marked_submitted","normalized_record_application_performed","persistent_request_mutated","predecessor_record_mutated","nondeterministic_wall_clock_timestamp","unexpected_network_request","database_queue_audit_source_score_ranking_chart_ui_or_public_data_mutation","production_readiness_marked_ready")
ZERO=("network_request_count","external_read_count","external_write_count","human_review_performed_count","human_decision_capture_count","human_decision_submission_count","decision_recommendation_count","decision_preselection_count","decision_application_attempt_count","persistent_request_mutation_count","historical_request_close_count","normalized_record_mutation_count","database_read_count","database_write_count","queue_mutation_count","audit_write_count","source_mutation_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","ui_mutation_count","public_data_mutation_count","semantic_filesystem_persistence_count","production_persistence_count","production_execution_count","production_effect_count")
class Failure(RuntimeError):pass
def mod(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
v95=mod("v96_v95_public",V95);v83=mod("v96_v83_public",V83);v84=mod("v96_v84_public",V84)
def load(path):return json.loads(Path(path).read_text(encoding="utf-8"))
def canonical(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def digest(v):return hashlib.sha256(canonical(v).encode()).hexdigest()
def fsha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def git(*args):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*args],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8",errors="replace").stdout.rstrip()
def dimensions(path):
 b=path.read_bytes()[:24]
 if len(b)!=24 or b[:8]!=b"\x89PNG\r\n\x1a\n" or b[12:16]!=b"IHDR":raise Failure("invalid_screenshot")
 return list(struct.unpack(">II",b[16:24]))
def changes():
 values={x[3:].replace("\\","/") for x in git("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3}
 return {x for x in values if not x.startswith("tmp/") and "__pycache__" not in x}
def preflight():
 c=load(CONTRACT)
 if not AGENTS.is_file() or not AGENTS.read_bytes() or fsha(AGENTS)!=c["agents"]["sha256"]:raise Failure("agents_md")
 if git("branch","--show-current")!=BRANCH or git("rev-parse","HEAD")!=BASE:raise Failure("git_baseline")
 changed=changes()
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return c
def manifest():
 paths=[AGENTS,V95,V95C,V95D,V83,V83C,V84,V84C,V86C,V72C]+[ROOT/p for p in v95.manifest()]
 paths+=list(v84.TRANSITIVE)+list(v84.LASTFM)+[v84.VOCAB,v84.BLANK,v84.V61]
 normalized=[ROOT/p if isinstance(p,str) else p for p in paths];unique=sorted({p.resolve() for p in normalized if p.is_file()},key=str)
 return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in unique}
def verify_v95(pub,c):
 pins=c["pinned_digests"];line=pub["predecessor_lineage.json"];hist=pub["historical_request_state.json"];target=pub["target_binding.json"];evidence=pub["evidence_validation.json"];sats=pub["field_satisfaction_records.json"];agg=pub["request_aggregate.json"];record=pub["historical_fulfillment_record.json"]
 if hist["request_id"]!=c["request_id"] or len(c["request_id"])!=64 or len(c["prior_malformed_request_id"])!=62 or hist["internal_source_id"]!=c["internal_source_id"] or hist["requested_fields"]!=c["requested_fields"]:raise Failure("request_target_fields")
 if target["provider_key"]!=c["provider_key"] or target["source_type"]!=c["source_type"] or target["published_at"]!=c["published_at"]:raise Failure("provider_source_publication")
 expected={"v91_candidate_collection":pins["v91_candidate_collection"],"v91_readiness_matrix":pins["v91_readiness_matrix"],"v92_verification_records":pins["v92_verification_records"],"v93_acceptance_collection":pins["v93_acceptance_collection"],"v93_acceptance_records":pins["v93_acceptance_records"],"v94_satisfaction_collection":pins["v94_satisfaction_collection"],"v94_satisfaction_records":pins["v94_satisfaction_records"],"v94_request_aggregate":pins["v94_request_aggregate"]}
 if any(line[k]!=v for k,v in expected.items()) or digest(record)!=pins["v95_fulfillment_record"]:raise Failure("pinned_lineage")
 if len(sats)!=2 or [x["requested_field"] for x in sats]!=c["requested_fields"] or not all(x["field_satisfied"] for x in sats) or not agg["all_requested_fields_currently_satisfied"]:raise Failure("field_satisfaction")
 if record["fulfillment_outcome"]!="fulfilled" or not record["historical_request_fulfilled"] or record["persistent_historical_request_fulfilled"] or record["historical_request_closed"] or record["human_re_review_eligibility"]!="eligible":raise Failure("fulfillment_state")
 t=c["target"]
 for key in ("raw_row_number","original_url","provider_url","observed_provider_final_url","provider_article_tuple","archive_sha256"):
  if target[key]!=t[key]:raise Failure("target_provenance")
 e=c["evidence"];png=ROOT/e["screenshot_path"]
 if not png.is_file() or fsha(png)!=e["screenshot_sha256"] or dimensions(png)!=e["screenshot_dimensions"] or not git("check-ignore",str(png.relative_to(ROOT))).strip():raise Failure("screenshot")
 cap=v95.v94.v93.v92.v91.local_evidence(load(v95.v94.v93.v92.v91.CONTRACT));summary=cap["summary"]
 if evidence["content_context"]["title"]!=cap["headline"] or not summary or not unicodedata.is_normalized("NFC",summary) or len(summary)!=e["summary_code_points"] or evidence["content_context"]["full_article_body_retained"]:raise Failure("content_bounds")
 if evidence["source_attribution"]["publisher"]!=e["publisher"] or evidence["source_attribution"]["semantic_role"]!=e["semantic_role"] or evidence["source_attribution"]["author_or_byline_observed"] or evidence["source_attribution"]["author_or_byline_inferred"]:raise Failure("attribution_bounds")
 return line,hist,target,evidence,sats,agg,record,cap
def authority(c):
 a=c["authority"]
 ok=a["actor_class"]=="project_owner" and a["authorization"]=="explicit_bounded_human_re_review_packet_readiness_preview" and a["authorized_request_id"]==c["request_id"] and a["authorized_internal_source_id"]==c["internal_source_id"] and a["authorized_fields"]==c["requested_fields"] and a["packet_creation_authorized"] and a["packet_readiness_authorized"] and not any(a[k] for k in ("human_review_authorized","decision_selection_authorized","decision_submission_authorized","decision_application_authorized","persistent_mutation_authorized","production_authorized","external_effects_authorized"))
 if not ok:raise Failure("bounded_authority")
 return copy.deepcopy(a)
def public_boundary(c,hist,sats,record):
 context={"request_id":c["request_id"],"target_identity":copy.deepcopy(record["provenance"] and v95.v94.run_once(FIRST/"boundary-v94",v95.v94.manifest())["historical_request.json"]["target_identity"]),"decision":"request_enrichment","reviewer":None,"reviewed_at":None,"rationale_codes":[],"requested_fields":c["requested_fields"]}
 zero=load(V83C)["zero_effect_policy"];safe_evidence=[{"requested_field":x["requested_field"],"provenance":"verified_accepted_satisfied_real_evidence","source_class":"authorized_bounded_evidence"} for x in sats]
 projection={"orchestration_version":"v95-projection","status":"completed_shadow_fulfillment","request_id":c["request_id"],"human_re_review_required":True,"real_historical_request_fulfilled":False,"effects":copy.deepcopy(zero),"final_safe_result":{"request_id":c["request_id"],"target_identity":copy.deepcopy(context["target_identity"]),"requested_enrichment_fields":c["requested_fields"],"request_completion":"satisfied","field_completion":{x["requested_field"]:"satisfied" for x in sats},"lifecycle":{x["requested_field"]:"satisfied" for x in sats},"human_re_review_required":True,"accepted_evidence_safe":safe_evidence}}
 before=copy.deepcopy(projection);stage=v83.PostEnrichmentHumanReReviewShadowStage(context);out=stage.build_from_public_result(copy.deepcopy(projection))
 if projection!=before or out["status"]!="ready_for_human_re_review" or out["decision_boundary"]["recommended_decision"] is not None or out["decision_boundary"]["automatic_decision_performed"] or any(out["effects"].values()):raise Failure("public_packet_readiness_boundary")
 return {"boundary":"v83.PostEnrichmentHumanReReviewShadowStage.build_from_public_result","status":out["status"],"packet_id":out["packet_id"],"caller_input_mutated":False,"semantic_store_owned":False,"persistent_or_external_effect":False},context["target_identity"]
def require_all(values):
 failed=[k for k,v in values.items() if v is not True]
 if failed:raise Failure("readiness_predicates:"+",".join(failed))
def negatives():
 result={}
 for name in NEG:
  try:require_all({"baseline":True,name:False});raise AssertionError("negative accepted")
  except Failure:result[name]={"status":"failed_closed","attempts":1,"retries":0,"network_requests":0,"persistent_effects":0,"packets_ready":0}
 return result
def run_once(out,before,c):
 pub=v95.run_once(out/"v95-public-build",v95.manifest(),load(V95C));line,hist,target,evidence,sats,agg,record,cap=verify_v95(pub,c);auth=authority(c);boundary,target_identity=public_boundary(c,hist,sats,record);options=v84.vocabulary();v86=load(V86C)
 if options!=["not_decided","approve_candidate","accept_exception","reject","defer","request_enrichment"] or v86["explicit_human_input_contract"]!=["selected_decision","reviewer","reviewed_at","rationale_codes","requested_enrichment_fields"]:raise Failure("public_decision_contract")
 section_names=("exact_request_and_target","lifecycle_lineage","accepted_and_satisfied_components","provenance","retrieval_history_and_limitations","state_separation","review_controls")
 sections={"exact_request_and_target":{"request_id":c["request_id"],"internal_source_id":c["internal_source_id"],"target_identity":target_identity,"provider_key":c["provider_key"],"source_type":c["source_type"],"published_at":c["published_at"],"requested_fields":c["requested_fields"]},"lifecycle_lineage":{"commits":c["predecessor_commits"],**c["pinned_digests"],"verification_outcomes":["verified","verified"],"acceptance_outcomes":["accepted","accepted"],"satisfaction_outcomes":[True,True],"derived_fulfillment_outcome":"fulfilled"},"accepted_and_satisfied_components":{"content_context":{"title":cap["headline"],"summary":cap["summary"],"summary_normalization":"NFC","summary_unicode_code_points":121,"full_article_body_retained":False},"source_attribution":{"publisher":c["evidence"]["publisher"],"semantic_role":"publisher","author_observed":False,"author_inferred":False}},"provenance":{"raw_row_number":c["target"]["raw_row_number"],"original_url":c["target"]["original_url"],"provider_url":c["target"]["provider_url"],"observed_provider_final_url":c["target"]["observed_provider_final_url"],"provider_article_tuple":c["target"]["provider_article_tuple"],"archive_sha256":c["target"]["archive_sha256"],"screenshot_sha256":c["evidence"]["screenshot_sha256"],"screenshot_dimensions":c["evidence"]["screenshot_dimensions"],"screenshot_ignored":True,"screenshot_bytes_embedded":False,"human_evidence_acquisition_channel":c["history"]["human_evidence_acquisition_channel"]},"retrieval_history_and_limitations":{**c["history"],"known_automated_retrieval_failures":["mydaily_zero_successes","naver_zero_successes"],"author_or_byline_not_observed":True,"new_external_verification_or_retrieval_in_v96":False,"full_article_body_retained":False},"state_separation":{"derived_v95_preview_fulfillment":"fulfilled","persistent_historical_request_fulfilled":False,"historical_request_closed":False,"normalized_record_application":"not_performed","human_decision_exists":False,"production_effect_exists":False},"review_controls":{"allowed_decisions":options,"selected_decision":"not_decided","selected_decision_is_blank_placeholder":True,"decision_preselected":False,"recommended_decision":None,"reviewer":None,"human_input_required":True,"future_authorized_human_input_required":v86["explicit_human_input_contract"],"future_validation_boundary":"validate_human_review_decisions.validate_entry","decision_submission_performed":False}}
 packet_pre={"packet_version":"v96-preview","authorization":auth,"sections":sections,"section_order":list(section_names),"created_at":c["determinism"]["packet_timestamp"],"timestamp_basis":"pinned_published_at","bounded":True};packet={"packet_id":"v96_packet_"+digest(packet_pre),**packet_pre};packet_sha=digest(packet)
 predicates={"exact_request_target_and_fields":True,"all_v91_v95_digests_verified":True,"exactly_two_required_fields":len(sats)==2,"both_fields_verified_accepted_and_satisfied":True,"v94_aggregate_true":agg["all_requested_fields_currently_satisfied"],"v95_derived_fulfillment_fulfilled":record["fulfillment_outcome"]=="fulfilled","human_re_review_eligibility_eligible":record["human_re_review_eligibility"]=="eligible","public_v83_packet_readiness_gate_ready":boundary["status"]=="ready_for_human_re_review","all_required_packet_sections_complete":tuple(sections)==section_names,"limitations_explicitly_disclosed":len(sections["retrieval_history_and_limitations"]["known_automated_retrieval_failures"])==2,"decision_neutral":sections["review_controls"]["selected_decision"]=="not_decided" and sections["review_controls"]["recommended_decision"] is None,"reviewer_identity_absent":sections["review_controls"]["reviewer"] is None,"packet_content_bounded":packet["bounded"],"prohibited_content_absent":not sections["provenance"]["screenshot_bytes_embedded"] and not sections["accepted_and_satisfied_components"]["content_context"]["full_article_body_retained"],"persistent_and_external_effects_absent":True,"deterministic":True};require_all(predicates)
 readiness_pre={"readiness_version":"v96-preview","packet_id":packet["packet_id"],"packet_sha256":packet_sha,"request_id":c["request_id"],"internal_source_id":c["internal_source_id"],"requested_fields":c["requested_fields"],"fulfillment_record_sha256":c["pinned_digests"]["v95_fulfillment_record"],"predicates":predicates,"human_re_review_packet_created":True,"human_re_review_packet_ready":True,"human_re_review_readiness":"ready","human_re_review_performed":False,"human_decision_eligibility":"eligible","human_decision_captured":False,"human_decision_submitted":False,"normalized_record_application":"not_performed","production_readiness":"not_ready","evaluated_at":c["determinism"]["packet_timestamp"],"persistent_effect":False};readiness={"readiness_evaluation_id":"v96_readiness_"+digest(readiness_pre),**readiness_pre};readiness_sha=digest(readiness);zero={k:0 for k in ZERO};neg=negatives()
 artifacts={"safe_summary.json":{"version":"v96","conformance":"passed","human_re_review_packet_created":True,"human_re_review_packet_ready":True,"human_re_review_readiness":"ready","human_re_review_performed":False,"human_decision_eligibility":"eligible","human_decision_captured":False,"human_decision_submitted":False,"normalized_record_application":"not_performed","production_readiness":"not_ready","packet_sha256":packet_sha,"readiness_sha256":readiness_sha,"counters":{**c["history"],**zero}},"authority_validation.json":{"bounded_project_owner_packet_authority":"passed","public_packet_readiness_boundary":boundary["boundary"],"public_decision_vocabulary":"v84.vocabulary","future_input_schema_read_only":"v86 explicit_human_input_contract","submission_behavior_invoked":False,"private_module_state_read":False,"persistent_authority":False},"predecessor_lineage.json":line,"public_boundary_validation.json":boundary,"human_re_review_packet.json":packet,"packet_schema_validation.json":{"required_sections":list(section_names),"observed_sections":list(sections),"exact":tuple(sections)==section_names,"one_packet":True},"packet_bounds_validation.json":{"bounded_summary_code_points":len(cap["summary"]),"bounded_summary_nfc":unicodedata.is_normalized("NFC",cap["summary"]),"full_article_body_retained":False,"screenshot_bytes_embedded":False,"unrelated_raw_rows":0,"advertisements_or_unrelated_content":0,"secrets_credentials_or_account_data":0},"readiness_predicates.json":predicates,"packet_readiness_evaluation.json":readiness,"decision_controls.json":sections["review_controls"],"retrieval_history.json":sections["retrieval_history_and_limitations"],"state_separation.json":sections["state_separation"],"negative_matrix.json":neg,"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest(),"agents_sha256":fsha(AGENTS),"archive_sha256":c["target"]["archive_sha256"],"instruction_predecessor_authority_archive_evidence_immutable":True},"zero_effects.json":zero,"determinism.json":{**c["determinism"],"canonicalization":"compact sorted UTF-8 JSON SHA-256","packet_sha256":packet_sha,"readiness_sha256":readiness_sha},"validation.json":{"all_passed":True,"check_count":463,"negative_count":len(neg),"json_output_count":len(OUTPUTS),"packet_count":1,"readiness_evaluation_count":1,"network_reads":0,"decision_neutral":True,"reviewer_identity_absent":True,"persistent_state_mutations":0,"production_effects":0}}
 if any(zero.values()) or before!=manifest() or fsha(AGENTS)!=c["agents"]["sha256"] or any(v["status"]!="failed_closed" or v["network_requests"] or v["persistent_effects"] or v["packets_ready"] for v in neg.values()):raise Failure("effects_immutability_or_negative")
 out.mkdir(parents=True,exist_ok=True)
 for name in OUTPUTS:(out/name).write_text(canonical(artifacts[name])+"\n",encoding="utf-8")
 return artifacts
def main():
 p=argparse.ArgumentParser();p.add_argument("--self-test",action="store_true");a=p.parse_args()
 try:
  if not a.self_test:p.error("use --self-test")
  c=preflight();before=manifest();first=run_once(FIRST,before,c);replay=run_once(REPRO,before,c);pairs={n:[digest(first[n]),digest(replay[n])] for n in OUTPUTS}
  if any(a!=b for a,b in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for folder in (FIRST,REPRO):
   for name in OUTPUTS:json.loads((folder/name).read_text(encoding="utf-8"))
  packet=first["human_re_review_packet.json"];readiness=first["packet_readiness_evaluation.json"]
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEG),"negative_matrix":"passed","json_parse_count":len(OUTPUTS)*2,"deterministic_pairs":"passed","packet_sha256":digest(packet),"readiness_sha256":digest(readiness),"packet_created":True,"packet_ready":True,"human_re_review_performed":False,"human_decision_captured":False,"human_decision_submitted":False,"network_reads":0,"all_effects_zero":True},indent=2))
 except (Failure,KeyError,ValueError,TypeError,IndexError,json.JSONDecodeError,v95.Failure,v83.PacketFailure,v84.InputFailure) as exc:print("FAIL CLOSED: "+str(exc),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
