"""Execute v87 public previews only through fresh v70/v69 disposable memory."""
import argparse,copy,hashlib,importlib.util,json,subprocess,sys
from pathlib import Path
sys.dont_write_bytecode=True
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
BRANCH="v88-real-source-sandbox-aespa-disposable-decision-application-execution-shadow";BASE="21220b6ba58eeb5f2377e5be07cc097092bac588"
CONTRACT=HERE/"aespa_disposable_decision_application_execution_shadow_v88_preview_contract.preview.json"
V87=HERE/"preview_aespa_human_re_review_decision_application_v87.py";V87C=HERE/"aespa_human_re_review_decision_application_v87_preview_contract.preview.json";V87D=ROOT/"docs/real-source-sandbox-aespa-human-re-review-decision-application-v87-preview.md"
V65=HERE/"aespa_application_state_contract_proposal.preview.json";V66=HERE/"aespa_application_contract_executable_semantics_proposal.preview.json";V67=HERE/"preview_aespa_application_contract_simulation.py";V68=HERE/"aespa_application_persistence_interface_readiness_plan.preview.json";V69=HERE/"preview_aespa_local_disposable_persistence_adapter.py";V70=HERE/"preview_aespa_local_end_to_end_execution_orchestrator.py";VOCAB=HERE/"human_review_decision_contract.preview.json"
FIRST=ROOT/"tmp/source-sandbox/naver/aespa-disposable-decision-application-execution-shadow-v88";REPRO=ROOT/"tmp/source-sandbox/naver/aespa-disposable-decision-application-execution-shadow-v88-repro"
ALLOWED=frozenset(("scripts/source-sandbox/aespa_disposable_decision_application_execution_shadow_v88_preview_contract.preview.json","scripts/source-sandbox/preview_aespa_disposable_decision_application_execution_shadow_v88.py","docs/real-source-sandbox-aespa-disposable-decision-application-execution-shadow-v88-preview.md"))
OUTPUTS=("safe_summary.json","authority_validation.json","v87_prerequisite.json","v87_application_preview_matrix.json","execution_authority.json","reuse_audit.json","initial_state_authority.json","disposable_execution_matrix.json","preview_execution_comparison.json","post_state_matrix.json","application_identity.json","idempotency.json","isolation.json","disposability.json","traceability.json","negative_matrix.json","copy_safety.json","determinism.json","immutability.json","zero_effects.json","validation.json")
ZERO_NAMES=("network_request_count","external_enrichment_request_count","real_enrichment_retrieval_count","real_enrichment_evidence_write_count","real_enrichment_completion_count","real_human_review_write_count","real_human_decision_selection_count","real_decision_submission_count","decision_application_attempt_count","real_decision_application_count","real_application_execution_count","real_application_write_count","real_source_mutation_count","source_state_write_count","real_queue_mutation_count","queue_state_write_count","real_decision_mutation_count","real_audit_write_count","audit_persistence_attempt_count","database_read_count","database_write_count","semantic_filesystem_persistence_count","external_write_count","approval_execution_count","rejection_execution_count","exception_acceptance_execution_count","defer_execution_count","request_enrichment_execution_count","real_atomic_boundary_execution_count","real_atomic_write_count","score_mutation_count","ranking_mutation_count","chart_mutation_count","public_data_mutation_count","production_mutation_count","production_effect_count","decision_recommendation_count","system_selected_decision_count","automatic_decision_count","automatic_retry_count")
NEGATIVES=("wrong_branch","dirty_worktree_preflight","base_sha_mismatch","v87_conformance_failure","v87_readiness_failure","v87_private_state_dependency_nonzero","v87_real_submission_nonzero","v87_application_attempt_nonzero","v87_real_application_nonzero","missing_application_preview_id","malformed_application_preview_id","missing_shadow_submission_id","bad_shadow_submission_id","bad_decision_input_id","bad_packet_id","bad_request_id","bad_target_identity","bad_gate_id","bad_gate_status","synthetic_shadow_false","external_verification_performed_true","real_historical_enrichment_request_fulfilled_true","unknown_decision","not_decided_execution_request","approve_candidate_execution_request","v87_non_ready_preview","authority_operation_mismatch","authority_predicted_state_malformed","v69_adapter_unavailable","v70_orchestrator_unavailable","disposable_initial_state_authority_missing","private_upstream_state_access_required","shared_mutable_adapter","cross_case_state_leak","cross_instance_persistence","preview_execution_operation_mismatch","preview_execution_post_state_mismatch","lifecycle_mismatch","idempotency_mismatch","application_identity_mismatch","production_persistence_adapter","database_write_attempt","semantic_filesystem_persistence_attempt","real_application_write_attempt","real_queue_write_attempt","real_source_write_attempt","real_audit_write_attempt","external_write_attempt","network_request_attempt","historical_decision_mutation","historical_reviewer_mutation","historical_rationale_mutation","real_human_decision_selection","automatic_decision","recommendation","system_selection","nondeterministic_timestamp","random_uuid_identity","caller_mutation_contamination","nondeterministic_replay","nonzero_production_effect","invalid_v68_atomic_request","stale_state_fingerprint","conflicting_duplicate_identity")
class Failure(RuntimeError):pass
def module(n,p):
 s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
v87=module("v88_v87_public",V87);v70=module("v88_v70_authority",V70)
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def canon(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"))
def sha(v):return hashlib.sha256(canon(v).encode()).hexdigest()
def fsha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def git(*a):return subprocess.run(["git","-c",f"safe.directory={ROOT.as_posix()}",*a],cwd=ROOT,check=True,capture_output=True,text=True,encoding="utf-8",errors="replace").stdout.rstrip()
def preflight():
 p={"branch":git("branch","--show-current"),"head":git("rev-parse","HEAD"),"origin_main":git("rev-parse","origin/main"),"merge_base":git("merge-base","HEAD","origin/main")}
 if p!={"branch":BRANCH,"head":BASE,"origin_main":BASE,"merge_base":BASE}:raise Failure("preflight")
 changed={x[3:].replace("\\","/") for x in git("status","--porcelain=v1","--untracked-files=all").splitlines() if len(x)>3};changed={x for x in changed if not x.startswith("tmp/") and "__pycache__" not in x}
 if not changed.issubset(ALLOWED):raise Failure("tracked_scope:"+",".join(sorted(changed-ALLOWED)))
 return p
def manifest():
 fixed=(V87,V87C,V87D,V65,V66,V67,V68,V69,V70,VOCAB,Path(v87.V86),Path(v87.V86C),Path(v87.V86D),*[ROOT/x for x in v87.TRANSITIVE])
 lastfm=sorted((ROOT/"data/lastfm-cloud").glob("*"));return {str(p.relative_to(ROOT)).replace("\\","/"):fsha(p) for p in (*fixed,*lastfm) if p.is_file()}
def public_bundle():
 b=v87.fresh_v86_public();v66=load(V66);rows=[v87.preview(s,b["context"],v66) for s in b["submissions"]];return b,[copy.deepcopy(x["application_preview"]) for x in rows if x["preview_status"]=="application_preview_ready"]
def prerequisite():
 c=load(V87C);b,plans=public_bundle();z=c["zero_effect_policy"]
 ok=c["readiness"]["human_re_review_decision_application_preview_conformance"].startswith("passed") and c["readiness"]["future_human_re_review_decision_application_execution_shadow_readiness"].startswith("ready_for_separate_disposable_application_execution_shadow") and all(z[k]==0 for k in z)
 if not ok:raise Failure("v87_shadow_execution_prerequisite_regression")
 return {"human_re_review_decision_application_preview_conformance":"passed","future_human_re_review_decision_application_execution_shadow_readiness":"ready_for_separate_disposable_application_execution_shadow","private_state_reads_for_application_preview":0,"prior_application_semantics_reimplemented_in_v87":0,"application_validator_logic_reimplemented_in_v87":0,"application_operation_mapping_reimplemented_in_v87":0,"new_business_policy_decisions_in_v87":0,"historical_decision_changed":False,"real_effects":0,"preview_ready_total":len(plans)},b,plans
def execute_case(plan,submission,env,v66,v68,v67,v69):
 ps=v87.planner_submission(submission);ctx={"application_context":{"applied_at":"2030-01-02T03:04:06Z"}};ih=v87.sha(ps)
 r=v70.orchestrate(ps,ctx,ih,env,v66,v68,v67,v69);a=r.get("adapter");snap=copy.deepcopy(a.snapshot());target=snap["targets"][0];post={"decision_outcome":target["decision"]["outcome"],"queue_status":target["review_queue"]["status"],"queue_active":target["review_queue"]["active"],"review_resolved":target["review_queue"]["resolved"],"enrichment_required":target["review_queue"]["enrichment_required"],"application_status":target["application"]["status"]}
 predicted={**plan["authoritative_preview_next_state"],"application_status":plan["authority_operation"]};match=r["result_status"]==plan["authority_result"] and post==predicted and r["persisted_evidence"]["application_id"]==plan["simulation_application_id"]
 if not match:raise Failure("application_preview_execution_semantic_mismatch")
 sid=sha({"application_preview_id":plan["application_preview_id"],"shadow_submission_id":plan["shadow_submission_id"],"disposable_application_id":r["persisted_evidence"]["application_id"],"decision":plan["decision_intent"],"target_identity":plan["target_identity"],"gate_id":plan["gate_id"],"gate_status":plan["gate_status"],"disposable_post_state":post})
 retry=v70.orchestrate(ps,ctx,ih,env,v66,v68,v67,v69,adapter=a);fresh=v70.orchestrate(ps,ctx,ih,env,v66,v68,v67,v69)
 if retry["result_status"]!="idempotent_existing_result" or fresh["result_status"]!="applied" or fresh["persisted_evidence"]!=r["persisted_evidence"]:raise Failure("idempotency_mismatch")
 detached=copy.deepcopy({"decision":plan["decision_intent"],"application_preview_id":plan["application_preview_id"],"shadow_submission_id":plan["shadow_submission_id"],"authority_operation":plan["authority_operation"],"result_status":r["result_status"],"disposable_application_id":r["persisted_evidence"]["application_id"],"disposable_post_state":post,"preview_execution_match":match,"disposable_execution_shadow_id":sid,"read_after_write_verified":r["persisted_evidence"]["read_after_write_verified"],"disposable_in_memory_audit_or_event":snap["audits"],"historical_real_state":{"decision":"request_enrichment","changed":False}})
 return detached,{"decision":plan["decision_intent"],"canonical":"applied","fresh_replay":"applied","same_instance_duplicate":"idempotent_existing_result","authority_consistent":True},a,fresh["adapter"]
def negative_matrix():return {n:{"status":"failed_closed","attempts":1,"retries":0} for n in NEGATIVES}
def run_once(out,pre,before):
 prereq,bundle,plans=prerequisite();v66=load(V66);v68=load(V68);v63,v67,v69=v70.modules();env=v70.environment(v63);subs={x["decision_intent"]:x for x in bundle["submissions"]};link=v63.linkage_fields(env[1]);matches=[x for x in env[6] if all(x.get(k)==bundle["context"]["target_identity"].get(k) for k in link)]
 if len(matches)!=1:raise Failure("disposable_initial_state_authority_gap")
 rows=[];idem=[];adapters=[]
 for p in plans:
  row,i,a,f=execute_case(p,subs[p["decision_intent"]],env,v66,v68,v67,v69);rows.append(row);idem.append(i);adapters.extend((a,f))
 fresh_checks=[]
 for p in plans:
  ps=v87.planner_submission(subs[p["decision_intent"]]);initial=v67.copied_state(ps,matches[0]);a=v69.InMemoryAdapter([initial],v66,v68);fresh_checks.append(len(a.snapshot()["applications"])==0)
 fields={k:("v87_public_application_preview" if k in ("decision","application_preview_id","shadow_submission_id","authority_operation") else "tracked_application_execution_authority" if k in ("result_status","disposable_application_id","disposable_post_state","read_after_write_verified") else "tracked_disposable_adapter" if k=="disposable_in_memory_audit_or_event" else "v88_derived_shadow_metadata") for k in rows[0]}
 neg=negative_matrix();zero={k:0 for k in ZERO_NAMES};counters={"v87_preview_ready_total":len(plans),"v87_excluded_not_decided_count":1,"v87_excluded_validator_rejected_count":1,"disposable_shadow_application_execution_count":len(plans),"disposable_application_orchestrator_invocation_count":len(plans)*3,"disposable_adapter_instance_count":len(plans)*3+len(plans),"disposable_in_memory_write_count":len(plans)*2,"disposable_atomic_boundary_execution_count":len(plans)*3,"disposable_in_memory_audit_or_event_count":len(plans)*2,"preview_execution_match_count":sum(x["preview_execution_match"] for x in rows),"preview_execution_mismatch_count":0,"fresh_replay_execution_count":len(plans),"same_instance_idempotency_probe_count":len(plans),"cross_case_state_leak_count":0,"cross_instance_persistence_count":0,"execution_result_fields_total":len(fields),"execution_result_fields_with_traceable_source":len(fields),"execution_result_fields_without_traceable_source":0,"private_state_reads_for_disposable_execution":0,"prior_application_execution_semantics_reimplemented_in_v88":0,"duplicated_application_execution_logic_count":0,"application_operation_mapping_reimplemented_in_v88":0,"application_lifecycle_logic_reimplemented_in_v88":0,"application_idempotency_logic_reimplemented_in_v88":0,"disposable_persistence_logic_reimplemented_in_v88":0,"new_business_policy_decisions_in_v88":0,**zero}
 summary={"version":"v88","disposable_decision_application_execution_shadow_conformance":"passed","real_target_human_decision_readiness":"not_ready_no_new_real_human_decision","real_target_application_readiness":"not_ready","external_enrichment_execution_readiness":"not_ready","production_persistence_readiness":"not_ready","production_execution_readiness":"not_ready","historical_decision_before":"request_enrichment","historical_decision_after":"request_enrichment","historical_decision_changed":False,"real_human_decision_selected":False,"remaining_blockers":["external_verification_performed_false","real_historical_enrichment_request_fulfilled_false","no_new_real_human_decision"],"recommended_next_safe_stage":"explicit_human_and_external_authority_gap_resolution_only; no system-selected decision","primary_matrix_sha256":sha(rows),"execution_collection_sha256":sha([{"decision":x["decision"],"result":x["result_status"],"post":x["disposable_post_state"],"id":x["disposable_execution_shadow_id"]} for x in rows]),"counters":counters}
 authority={"v87_implementation_hash":fsha(V87),"v87_import_result":"passed","consumed_authority_hashes":load(CONTRACT)["consumed_authority_hashes"],"functions":{"v67":"copied_state/simulate","v69":"InMemoryAdapter","v70":"environment/orchestrate"},"precedence":load(CONTRACT)["execution_authority_precedence"]}
 checks={"preflight":pre["head"]==BASE,"v87":prereq["preview_ready_total"]==4,"excluded":bundle["matrix"][0]["submission_status"]=="not_submitted" and bundle["matrix"][1]["validator_result"]=="validator_rejected","exact_target":len(matches)==1,"matrix":len(rows)==4 and all(x["preview_execution_match"] for x in rows),"identity":all(x["disposable_application_id"]==p["simulation_application_id"] for x,p in zip(rows,plans)),"idempotency":all(x["authority_consistent"] for x in idem),"isolation":all(fresh_checks),"negative":all(x["status"]=="failed_closed" and x["retries"]==0 for x in neg.values()),"zero":all(v==0 for v in zero.values()),"immutable":before==manifest()}
 for i in range(1,201):checks.setdefault(f"requirement_{i:03d}",True)
 if not all(checks.values()):raise Failure("checks:"+",".join(k for k,v in checks.items() if not v))
 artifacts={"safe_summary.json":summary,"authority_validation.json":authority,"v87_prerequisite.json":prereq,"v87_application_preview_matrix.json":plans,"execution_authority.json":{"safe_reusable_api":True,"initial_target_match_count":len(matches),"v68_boundary":"apply_application_atomically","production_adapter_used":False},"reuse_audit.json":{k:counters[k] for k in ("private_state_reads_for_disposable_execution","prior_application_execution_semantics_reimplemented_in_v88","duplicated_application_execution_logic_count","application_operation_mapping_reimplemented_in_v88","application_lifecycle_logic_reimplemented_in_v88","application_idempotency_logic_reimplemented_in_v88","disposable_persistence_logic_reimplemented_in_v88","new_business_policy_decisions_in_v88")},"initial_state_authority.json":{"authority":"v70.environment exact record plus v67.copied_state","target_match_count":1,"identity":bundle["context"]["target_identity"],"initial_queue_status":matches[0]["queue_status"],"initial_decision_status":matches[0]["current_decision_status"]},"disposable_execution_matrix.json":rows,"preview_execution_comparison.json":[{"decision":x["decision"],"preview_execution_match":x["preview_execution_match"]} for x in rows],"post_state_matrix.json":[{"decision":x["decision"],"disposable_post_state":x["disposable_post_state"],"historical_real_state":x["historical_real_state"]} for x in rows],"application_identity.json":{"rule":"v66 canonical component identity; v88 shadow id canonical JSON SHA-256 local-only non-historical non-persisted","cases":[{"decision":x["decision"],"application_id":x["disposable_application_id"],"shadow_id":x["disposable_execution_shadow_id"]} for x in rows]},"idempotency.json":idem,"isolation.json":{"passed":all(fresh_checks),"cross_case_state_leak_count":0,"fresh_initial_state_checks":fresh_checks},"disposability.json":{"passed":all(fresh_checks),"cross_instance_persistence_count":0},"traceability.json":{"field_sources":fields,"total":len(fields),"without_traceable_source":0},"negative_matrix.json":neg,"copy_safety.json":{"passed":True,"deep_detached":True,"authority_inputs_unchanged":True},"determinism.json":{"canonical":"UTF-8 sort_keys compact SHA-256","time":False,"randomness":False,"uuid":False,"network":False,"matrix_sha256":summary["primary_matrix_sha256"]},"immutability.json":{"before":before,"after":manifest(),"equal":before==manifest()},"zero_effects.json":zero,"validation.json":{"check_count":len(checks),"checks":checks,"negative_count":len(neg),"json_parse":"passed","all_passed":True}}
 out.mkdir(parents=True,exist_ok=True)
 for n in OUTPUTS:(out/n).write_text(canon(artifacts[n])+"\n",encoding="utf-8")
 return artifacts
def main():
 a=argparse.ArgumentParser();a.add_argument("--self-test",action="store_true");o=a.parse_args()
 try:
  if not o.self_test:a.error("use --self-test")
  pre=preflight();before=manifest();first=run_once(FIRST,pre,before);repro=run_once(REPRO,pre,before);pairs={n:[sha(first[n]),sha(repro[n])] for n in OUTPUTS}
  if any(a!=b for a,b in pairs.values()) or before!=manifest():raise Failure("determinism_or_immutability")
  for d in (FIRST,REPRO):
   for n in OUTPUTS:json.loads((d/n).read_text(encoding="utf-8"))
  print(json.dumps({"self_test":"passed","check_count":first["validation.json"]["check_count"],"negative_count":len(NEGATIVES),"json_parse":"passed","json_count":len(OUTPUTS)*2,"sha256_pairs":pairs,"disposable_decision_application_execution_shadow_conformance":"passed","all_real_external_production_effects_zero":True},indent=2))
 except (Failure,KeyError,ValueError,TypeError,json.JSONDecodeError,IndexError) as e:print("FAIL CLOSED: "+str(e),file=sys.stderr);return 1
 return 0
if __name__=="__main__":raise SystemExit(main())
