import test from 'node:test';
import assert from 'node:assert/strict';
import { assessAbsoluteLevel, assessRetailLevel, deriveRawRankDelta, validateMethodologyCombination } from '../lib/alternative-evidence/albumMethodology';
import { runAlbumSyntheticValidation } from '../lib/alternative-evidence/albumSyntheticValidation';
const input=(id:string, value:number|null=3, key='physicalRetailLevelProxy', role='proxy', semantic='rank', unit='rank')=>({featureInputId:id,featureInputFamilyId:null,featureKey:key,featureRole:role,sourceClass:'retailer-api',sourceEvidenceId:'e',sourceObservationId:null,contributionIdentity:{contributionIdentityId:id,sourceEvidenceId:'e',claimFamilyId:null,underlyingObservationId:null,scopeKey:'r'},provenance:{origin:'authorized-public-api',acquisitionProvider:'yes24',reportedProvider:'yes24',sourceUrl:null,evidenceDigest:'d',researchOnly:true},artistId:'a',artistIdentityState:'resolved',releaseId:'r',releaseIdentityState:'resolved',releaseFamilyId:null,editionId:null,skuId:null,semantic,value,unit,territory:null,format:null,providerPeriod:'2026-08-30',reportedPeriod:null,sourcePublishedAt:null,providerPublishedAt:null,observedAt:'2026-08-30T01:00:00Z',collectedAt:'2026-08-30T02:00:00Z',revisionObservedAt:null,knowledgeMode:'current-research',periodType:'day',availabilityState:value===null?'missing':'available',qualityState:'clear',eligibilityState:'feature-resolver-candidate',proxyFallbackState:role==='absolute'?'absolute-available':'proxy-available',comparabilityState:'comparable',crossSourceDuplicationState:'unknown',retailerId:'yes24',retailerProductId:'p',categoryFamily:'music',providerCategoryId:'music',categoryResolutionState:'resolved',chartType:'daily',movementType:null,aggregationScope:null,parentInputId:null,blockers:[]}) as never;
test('methodology is versioned, non-scoring, synthetic-only',()=>{const r=runAlbumSyntheticValidation([{scenarioId:'none',description:'none',inputs:[],snapshots:[],expectedOverall:'insufficient'}]);assert.equal(r.methodologyVersion,'album-methodology-v1');assert.equal(r.productionReadiness,'not-ready');assert.equal('finalScore' in r.scenarioResults[0].evaluation,false);});
test('absolute/rank/index/identity/proxy gates',()=>{assert.equal(assessAbsoluteLevel([input('d',3,'providerNativePeriodSales','absolute','period-sale','physical-units')]).state,'ready');assert.equal(assessAbsoluteLevel([input('r',3,'diagnosticRank','diagnostic')]).state,'unavailable');assert.equal(assessRetailLevel(input('u')).state,'provisional');});
test('raw rank movement and arithmetic guards',()=>{assert.equal(deriveRawRankDelta(input('a',20),input('b',8)).rawRankImprovement,12);assert.equal(deriveRawRankDelta(input('c',8),input('d',20)).rawRankImprovement,-12);assert.equal(deriveRawRankDelta(input('e',2),input('f',2)).rawRankImprovement,0);assert.equal(validateMethodologyCombination([input('x',3,'physicalPurchaseAbsoluteLevel','absolute','period-sale','physical-units'),input('y')]).valid,false);});
test('provider methodology matrix executes 34 deterministic scenarios',()=>{const scenarios=Array.from({length:34},(_,n)=>({scenarioId:`method-${n}`,description:'synthetic',inputs:[input(`scenario-${n}`,n+1,n%2?'diagnosticProviderIndex':'physicalRetailLevelProxy',n%2?'diagnostic':'proxy',n%2?'index':'rank',n%2?'provider-index':'rank')],snapshots:[],expectedOverall:n%2?'diagnostic-only':'proxy-only'}));const a=runAlbumSyntheticValidation(scenarios),b=runAlbumSyntheticValidation(scenarios);assert.equal(a.scenarioCount,34);assert.equal(a.failedScenarioCount,0);assert.deepEqual(a.scenarioResults.map(x=>x.evaluation.evaluationId),b.scenarioResults.map(x=>x.evaluation.evaluationId));});
