import test from 'node:test';
import assert from 'node:assert/strict';
import { sha256Canonical } from '../lib/shared/canonicalDigest';
import { fromDirectAlbumObservation, fromRetailObservation } from '../lib/alternative-evidence/canonicalAlbumFeatureInput';
import { buildDirectAlbumObservation, type DirectAlbumObservation } from '../lib/alternative-evidence/directAlbumProvider';
import { buildRetailObservation } from '../lib/alternative-evidence/retailObservation';
import { enrichAlbumFeatureInputIdentity } from '../lib/alternative-evidence/identityFoundation';
import { fromCanonicalAlbumFeatureInput, deriveCumulativeDeltas, selectAsKnownAt, selectCurrentResearchHead, assessWindow, makeTemporalWindow, compareTemporalSnapshots, validateTemporalSnapshotSet } from '../lib/alternative-evidence/albumTemporalSnapshot';

const evidence = (id: string, provider = 'synthetic-provider') => ({ evidenceId: id, origin: 'direct-licensed-provider', sourceId: provider, sourceUrl: null, acquisitionProvider: 'fixture', reportedProvider: provider, observedAt: '2026-01-01T00:00:00.000Z', collectedAt: '2026-01-01T00:00:00.000Z', sourcePublishedAt: null, evidenceDigest: sha256Canonical({ id }), researchOnly: true, contractVersion: 'alternative-evidence-v1' });
const direct = (overrides: Partial<DirectAlbumObservation> = {}) => buildDirectAlbumObservation({ contractVersion: 'direct-album-observation-v1', providerId: 'synthetic-provider', providerObservationId: 'temporal-depth', providerArtistId: 'provider-artist', providerReleaseId: 'provider-release', providerEditionId: null, providerSkuId: null, fandexArtistId: 'fandex-artist', fandexReleaseId: 'fandex-release', fandexReleaseFamilyId: 'fandex-family', territory: 'Korea', format: 'CD', providerPeriod: '2026-01-01', providerPublishedAt: '2026-01-01T01:00:00.000Z', observedAt: '2026-01-02T00:00:00.000Z', collectedAt: '2026-01-02T01:00:00.000Z', revisionId: null, revisionObservedAt: null, supersedesObservationId: null, knowledgeMode: 'as-known-at-collection', scopeRole: 'standalone', parentObservationId: null, syntheticFixture: true, semantic: 'period-sale', value: 100, unit: 'physical-units', ...overrides });
const snapshot = (o: DirectAlbumObservation) => fromCanonicalAlbumFeatureInput(fromDirectAlbumObservation(o, evidence(o.observationId) as never)[0]);
const retailSnapshot = (rank: number | null, period: string, missingState: 'observed' | 'not-ranked' = 'observed') => { const o = buildRetailObservation({ contractVersion: 'retail-observation-v1', retailerId: 'synthetic-retailer', retailerProductId: 'item-1', productIdentity: { retailerId: 'synthetic-retailer', retailerProductId: 'item-1', identityState: 'candidate' }, fandexArtistId: 'fandex-artist', fandexReleaseId: 'fandex-release', fandexReleaseFamilyId: 'fandex-family', retailerArtistText: 'Synthetic Artist', retailerTitle: 'Blue', categoryFamily: 'music', providerCategoryId: 'music', categoryResolutionState: 'resolved', chartType: 'daily', semantic: 'retail-rank', rank, movement: null, providerIndex: null, providerIndexName: null, providerPeriod: period, providerPeriodState: 'resolved', providerPublishedAt: `${period}T01:00:00.000Z`, observedAt: `${period}T02:00:00.000Z`, collectedAt: `${period}T03:00:00.000Z`, sourceType: 'synthetic-fixture', missingState, syntheticFixture: true }); return fromCanonicalAlbumFeatureInput(fromRetailObservation(o, { ...evidence(`retail-${period}`, 'synthetic-retailer'), origin: 'authorized-public-api' } as never)[0]); };

test('temporal depth runs 16 concrete scenarios through canonical and identity layers', () => {
  const scenarios = [
    ['native-period', () => assert.equal(snapshot(direct()).seriesKind, 'native-period')],
    ['timestamp-separation', () => { const s = snapshot(direct()); assert.notEqual(s.providerPeriod, s.collectedAt); assert.notEqual(s.observedAt, s.collectedAt); }],
    ['identity-retained', () => { const i = fromDirectAlbumObservation(direct({ fandexReleaseId: null }), evidence('identity-blocked') as never)[0]; const e = enrichAlbumFeatureInputIdentity(i, { releaseState: 'unresolved' }); assert.equal(fromCanonicalAlbumFeatureInput(e).releaseId, null); }],
    ['cumulative-first', () => assert.equal(deriveCumulativeDeltas([snapshot(direct({ semantic: 'cumulative-sale', value: 100, providerPeriod: '2026-01-01' }))])[0].delta, null)],
    ['cumulative-positive', () => { const d = deriveCumulativeDeltas([snapshot(direct({ semantic: 'cumulative-sale', value: 100, providerPeriod: '2026-01-01' })), snapshot(direct({ observationId: 'cum-2', semantic: 'cumulative-sale', value: 180, providerPeriod: '2026-01-02' }))]); assert.equal(d[1].delta, 80); }],
    ['cumulative-negative', () => { const d = deriveCumulativeDeltas([snapshot(direct({ semantic: 'cumulative-sale', value: 200, providerPeriod: '2026-01-01' })), snapshot(direct({ observationId: 'cum-3', semantic: 'cumulative-sale', value: 190, providerPeriod: '2026-01-02' }))]); assert.equal(d[1].state, 'negative-delta'); assert.equal(d[1].delta, -10); }],
    ['recollection-conflict', () => { const a = snapshot(direct({ providerPeriod: '2026-01-05', value: 10 })); const b = snapshot(direct({ observationId: 'recollect', providerPeriod: '2026-01-05', value: 11 })); assert.ok(validateTemporalSnapshotSet([a, b]).issues.includes('same-period-conflict')); }],
    ['revision-lineage', () => { const a = snapshot(direct({ observationId: 'original', value: 10 })); const b = snapshot(direct({ observationId: 'revision', value: 12, revisionId: 'r1', revisionObservedAt: '2026-01-10T00:00:00.000Z' })); assert.equal(b.revisionState, 'revised'); assert.notEqual(a.snapshotId, b.snapshotId); }],
    ['as-known-cutoff', () => { const a = snapshot(direct({ collectedAt: '2026-01-02T00:00:00.000Z' })); const b = snapshot(direct({ observationId: 'future', collectedAt: '2026-02-01T00:00:00.000Z' })); assert.equal(selectAsKnownAt([a, b], '2026-01-15').length, 1); }],
    ['current-research-head', () => { const a = snapshot(direct({ providerPeriod: '2026-01-01', value: 10 })); const b = snapshot(direct({ observationId: 'head-2', providerPeriod: '2026-01-01', value: 11 })); assert.equal(selectCurrentResearchHead([a, b]).state, 'conflicting'); }],
    ['retail-rank-series', () => assert.equal(retailSnapshot(20, '2026-01-01').seriesKind, 'snapshot-rank')],
    ['not-ranked-numeric-free', () => { const s = retailSnapshot(null, '2026-01-02', 'not-ranked'); assert.equal(s.availabilityState, 'not-ranked'); assert.equal(s.value, null); }],
    ['retail-gap', () => { const a = retailSnapshot(20, '2026-01-01'); const b = retailSnapshot(8, '2026-01-03'); assert.equal(compareTemporalSnapshots(a, b), 'comparable'); }],
    ['window-completeness', () => { const a = retailSnapshot(20, '2026-01-01'); const w = assessWindow([a], makeTemporalWindow('2026-01-01', '2026-01-07', 'day', 7)); assert.equal(w.completeness, 'partial'); }],
    ['first-week-distinction', () => { const a = snapshot(direct({ semantic: 'first-week-sale', providerPeriod: 'first-week', value: 100 })); const b = snapshot(direct({ observationId: 'calendar', semantic: 'period-sale', providerPeriod: '2026-01-01', value: 100 })); assert.equal(compareTemporalSnapshots(a, b), 'not-comparable'); }],
    ['native-cumulative-separation', () => { const a = snapshot(direct({ semantic: 'period-sale', providerPeriod: '2026-01-01' })); const b = snapshot(direct({ observationId: 'cum-4', semantic: 'cumulative-sale', providerPeriod: '2026-01-02', value: 180 })); assert.ok(validateTemporalSnapshotSet([a, b]).valid); assert.notEqual(a.seriesKind, b.seriesKind); }],
  ] as const;
  assert.equal(scenarios.length, 16);
  for (const [id, run] of scenarios) assert.doesNotThrow(run, id);
});
