import test from 'node:test';
import assert from 'node:assert/strict';
import { ALBUM_SYNTHETIC_SCENARIO_CATALOG, ALBUM_SYNTHETIC_CATALOG_INVARIANT_COUNT } from './fixtures/albumSyntheticScenarioCatalog';
import { runAlbumSyntheticValidation } from '../lib/alternative-evidence/albumSyntheticValidation';
import { envelopeRecord, planPersistenceAppend } from '../lib/alternative-evidence/persistenceContracts';

export const ALBUM_INTEGRATED_SYNTHETIC_VALIDATION_VERSION='album-integrated-synthetic-gate-v1';
test('broad catalog preserves 72 scenarios and 144 invariants',()=>{assert.equal(ALBUM_SYNTHETIC_SCENARIO_CATALOG.length,72);assert.equal(ALBUM_SYNTHETIC_CATALOG_INVARIANT_COUNT,144);assert.equal(new Set(ALBUM_SYNTHETIC_SCENARIO_CATALOG.map(x=>x.scenarioId)).size,72);assert.equal(ALBUM_SYNTHETIC_SCENARIO_CATALOG.filter(x=>x.depth==='declaration-only').length,50);assert.equal(ALBUM_SYNTHETIC_SCENARIO_CATALOG.filter(x=>x.depth==='contract-composed').length,14);assert.equal(ALBUM_SYNTHETIC_SCENARIO_CATALOG.filter(x=>x.depth==='end-to-end-domain').length,8);});
test('master forbidden matrix is explicit and deterministic',()=>{const values=ALBUM_SYNTHETIC_SCENARIO_CATALOG.flatMap(x=>x.forbiddenOutcomes);assert.ok(values.includes('rank-not-units'));assert.ok(values.includes('certification-not-exact'));assert.ok(values.includes('synthetic-not-production'));assert.equal(values.length,72);});
test('full-spine planning preserves methodology/persistence safety',()=>{const evaluation=runAlbumSyntheticValidation([{scenarioId:'full-direct',description:'full spine synthetic',inputs:[],snapshots:[],expectedOverall:'insufficient'}]).scenarioResults[0].evaluation;const record=envelopeRecord({recordType:'MethodologyEvaluationRecord',recordVersion:'v1',persistenceScope:'synthetic-validation',payload:evaluation,methodologyVersion:evaluation.methodologyVersion,syntheticOnly:true});const plan=planPersistenceAppend([], [record], {scope:'synthetic-validation',authorization:{acquisition:'unknown',automation:'unknown',rawStorage:'unknown',normalizedStorage:'unknown',retention:'unknown',commercialUse:'unknown',derivedPublication:'unknown',rawRedistribution:'unknown'},technicalEligibility:'unknown',syntheticOnly:true});assert.equal(plan.actions[0].action,'append');assert.equal(evaluation.productionReady,false);assert.equal(evaluation.liveReadiness,'not-established');});
