import test from 'node:test';
import assert from 'node:assert/strict';
import { createAlbumResearchClaim } from '../lib/alternative-evidence/albumResearch';
import { sha256Canonical } from '../lib/shared/canonicalDigest';
import { fromAlbumResearchClaim, fromDirectAlbumObservation, fromRetailObservation } from '../lib/alternative-evidence/canonicalAlbumFeatureInput';
import { buildDirectAlbumObservation, type DirectAlbumObservation } from '../lib/alternative-evidence/directAlbumProvider';
import { buildRetailObservation } from '../lib/alternative-evidence/retailObservation';
import { buildIdentityMappingId, createArtistCandidate, enrichAlbumFeatureInputIdentity, resolveRetailProductCandidates, validateArtistScope, type IdentityMappingRecord, type RetailProductIdentity } from '../lib/alternative-evidence/identityFoundation';

const evidence = (id: string, origin: 'authorized-public-api' | 'direct-licensed-provider' = 'authorized-public-api') => ({ evidenceId: id, origin, sourceId: 'synthetic-source', sourceUrl: null, acquisitionProvider: 'fixture', reportedProvider: origin === 'authorized-public-api' ? 'synthetic-retailer' : 'synthetic-provider', observedAt: '2026-01-01T00:00:00.000Z', collectedAt: '2026-01-01T00:00:00.000Z', sourcePublishedAt: null, evidenceDigest: sha256Canonical({ id }), researchOnly: true, contractVersion: 'alternative-evidence-v1' } as never);
const direct = (overrides: Partial<DirectAlbumObservation> = {}) => buildDirectAlbumObservation({ contractVersion: 'direct-album-observation-v1', providerId: 'synthetic-provider', providerObservationId: 'identity-depth', providerArtistId: 'provider-artist', providerReleaseId: 'provider-release', providerEditionId: null, providerSkuId: null, fandexArtistId: null, fandexReleaseId: null, fandexReleaseFamilyId: null, territory: 'Korea', format: 'CD', providerPeriod: '2026-01-01/2026-01-07', providerPublishedAt: '2026-01-01T00:00:00.000Z', observedAt: '2026-01-01T00:00:00.000Z', collectedAt: '2026-01-01T00:00:00.000Z', revisionId: null, revisionObservedAt: null, supersedesObservationId: null, knowledgeMode: 'as-known-at-collection', scopeRole: 'standalone', parentObservationId: null, syntheticFixture: true, semantic: 'period-sale', value: 1000, unit: 'physical-units', ...overrides });
const retail = () => buildRetailObservation({ contractVersion: 'retail-observation-v1', retailerId: 'synthetic-retailer', retailerProductId: 'item-1', productIdentity: { retailerId: 'synthetic-retailer', retailerProductId: 'item-1', identityState: 'candidate' }, fandexArtistId: null, fandexReleaseId: null, fandexReleaseFamilyId: null, retailerArtistText: 'Synthetic Artist', retailerTitle: 'Blue', categoryFamily: 'music', providerCategoryId: null, categoryResolutionState: 'unresolved', chartType: 'daily', semantic: 'retail-rank', rank: 3, movement: null, providerIndex: null, providerIndexName: null, providerPeriod: '2026-01-01', providerPeriodState: 'resolved', providerPublishedAt: '2026-01-01T00:00:00.000Z', observedAt: '2026-01-01T00:00:00.000Z', collectedAt: '2026-01-01T00:00:00.000Z', sourceType: 'synthetic-fixture', missingState: 'observed', syntheticFixture: true });
const newsClaim = (reviewed: boolean) => createAlbumResearchClaim({ evidence: evidence('news-identity', 'authorized-public-api'), origin: 'news-reported-provider-value', reportedProvider: 'hanteo-chart', artist: { fandexId: reviewed ? 'fandex-artist-1' : null, candidate: { label: 'Synthetic Artist', providerNativeId: null, source: 'extracted-text' }, state: reviewed ? 'resolved' : 'candidate', reviewed, blockers: [] }, release: { fandexId: reviewed ? 'fandex-release-1' : null, candidate: { label: 'Blue', providerNativeId: null, source: 'extracted-text' }, state: reviewed ? 'resolved' : 'candidate', reviewed, blockers: [] }, releaseFamilyCandidate: null, semantic: 'first-week-sale', semanticState: 'clear', definitionState: 'verified', value: 120000, valueKind: 'exact', unit: 'physical-units', territory: 'Korea', temporal: { providerPeriod: null, reportedPeriod: 'first-week', sourcePublishedAt: '2026-01-03T00:00:00.000Z', observedAt: '2026-01-03T00:00:00.000Z', collectedAt: '2026-01-03T00:00:00.000Z', revisionObservedAt: null, knowledgeMode: 'as-known-at-collection' }, extraction: { ordinal: 0, start: 0, end: 8, text: '초동 12만', textDigest: sha256Canonical('초동 12만') } });

test('retail product remains unresolved through canonical identity enrichment', () => { const input = fromRetailObservation(retail(), evidence('retail-identity'))[0]; const enriched = enrichAlbumFeatureInputIdentity(input, { artistState: 'unresolved', releaseState: 'unresolved' }); assert.equal(enriched.retailerProductId, 'item-1'); assert.equal(enriched.releaseId, null); assert.equal(enriched.eligibilityState, 'blocked'); assert.ok(enriched.blockers.includes('release-unresolved')); });
test('provider release identity is not a FANDEX release identity', () => { const input = fromDirectAlbumObservation(direct(), evidence('direct-identity', 'direct-licensed-provider'))[0]; assert.equal(input.releaseId, null); assert.equal(input.provenance.reportedProvider, 'synthetic-provider'); });
test('news claim traverses canonical identity boundary without changing provenance', () => { const input = fromAlbumResearchClaim(newsClaim(false))[0]; const enriched = enrichAlbumFeatureInputIdentity(input, { artistState: 'unresolved', releaseState: 'unresolved' }); assert.equal(enriched.sourceClass, 'news-reported-provider'); assert.equal(enriched.provenance.reportedProvider, 'hanteo-chart'); assert.equal(enriched.eligibilityState, 'blocked'); });
test('reviewed synthetic mapping resolves identity while preserving news provenance', () => { const input = fromAlbumResearchClaim(newsClaim(true))[0]; const enriched = enrichAlbumFeatureInputIdentity(input, { artistId: 'fandex-artist-1', artistState: 'resolved', releaseId: 'fandex-release-1', releaseState: 'resolved' }); assert.equal(enriched.artistId, 'fandex-artist-1'); assert.equal(enriched.releaseId, 'fandex-release-1'); assert.equal(enriched.provenance.reportedProvider, 'hanteo-chart'); });
test('title-only and artist-plus-title candidates do not auto-resolve', () => { const titleOnly = createArtistCandidate({ sourceId: 'fixture', rawArtistText: null }); assert.equal(titleOnly.resolutionState, 'unresolved'); const product: RetailProductIdentity = { retailerId: 'synthetic-retailer', retailerProductId: 'item-1', rawTitle: 'Blue', rawArtistText: 'Synthetic Artist', publisher: null, publishDate: null, isbn10: null, isbn13: null, goodsType: null, goodsSortNm: null, candidateReleaseIds: ['fandex-release-1'], candidateReleaseFamilyIds: [], candidateEditionIds: [], candidateSkuScope: 'unknown', resolutionState: 'candidate', reviewState: 'unreviewed' }; const result = resolveRetailProductCandidates(product, {}); assert.equal(result.resolutionState, 'candidate'); assert.ok(result.blockers.includes('review-required')); });
test('group/member scope mismatch remains blocked', () => { assert.deepEqual(validateArtistScope('member', 'group'), ['artist-ambiguous', 'review-required']); });
test('edition and release identities remain separate candidate namespaces', () => { const product: RetailProductIdentity = { retailerId: 'synthetic-retailer', retailerProductId: 'sku-e1', rawTitle: 'Blue Standard', rawArtistText: 'Synthetic Artist', publisher: null, publishDate: null, isbn10: null, isbn13: null, goodsType: null, goodsSortNm: null, candidateReleaseIds: ['release-1'], candidateReleaseFamilyIds: ['family-1'], candidateEditionIds: ['edition-1'], candidateSkuScope: 'edition-child', resolutionState: 'candidate', reviewState: 'unreviewed' }; const result = resolveRetailProductCandidates(product, {}); assert.deepEqual(result.candidateIds, ['release-1']); assert.notEqual(product.candidateEditionIds[0], result.candidateIds[0]); });
test('conflicting mappings are preserved and mapping IDs are deterministic', () => { const base: Omit<IdentityMappingRecord, 'mappingId' | 'contractVersion'> = { sourceType: 'provider-release', sourceProvider: 'synthetic-provider', sourceEntityId: 'provider-release', canonicalEntityType: 'release', candidateCanonicalId: 'fandex-release-a', resolutionState: 'resolved', reviewState: 'conflicting', evidenceRefs: ['e1'], supersedesMappingId: null }; const first = buildIdentityMappingId(base); const second = buildIdentityMappingId({ ...base, candidateCanonicalId: 'fandex-release-b', evidenceRefs: ['e2'] }); assert.equal(first, buildIdentityMappingId(base)); assert.notEqual(first, second); assert.equal(base.reviewState, 'conflicting'); });
test('identity enrichment preserves contribution identity and raw source feature ID', () => { const input = fromDirectAlbumObservation(direct(), evidence('contribution-identity', 'direct-licensed-provider'))[0]; const enriched = enrichAlbumFeatureInputIdentity(input, { artistState: 'unresolved', releaseState: 'unresolved' }); assert.equal(enriched.featureInputId, input.featureInputId); assert.equal(enriched.contributionIdentity.contributionIdentityId, input.contributionIdentity.contributionIdentityId); });

