import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeIdentityText, isResolved, createArtistCandidate, resolveRetailProductCandidates, enrichAlbumFeatureInputIdentity } from '../lib/alternative-evidence/identityFoundation';

test('normalization is conservative and deterministic',()=>{assert.equal(normalizeIdentityText('  IU  '),'iu'); assert.equal(normalizeIdentityText('Girls’ Generation'),'girls\' generation');});
test('resolved requires id and reviewed state',()=>{assert.equal(isResolved('resolved','a','human-reviewed'),true); assert.equal(isResolved('resolved','a','machine-candidate'),false); assert.equal(isResolved('resolved',null,'human-reviewed'),false);});
test('artist text remains candidate',()=>{const a=createArtistCandidate({sourceId:'yes24',rawArtistText:'Artist'});assert.equal(a.resolutionState,'unresolved');const b=createArtistCandidate({sourceId:'yes24',rawArtistText:'IU',candidateFandexArtistIds:['a']});assert.equal(b.resolutionState,'candidate');});
test('retail product mapping never auto-resolves',()=>{const p={retailerId:'yes24',retailerProductId:'i',rawTitle:'Album',rawArtistText:'Artist',publisher:null,publishDate:null,isbn10:null,isbn13:null,goodsType:null,goodsSortNm:null,candidateReleaseIds:['r'],candidateReleaseFamilyIds:[],candidateEditionIds:[],candidateSkuScope:'unknown',resolutionState:'unresolved',reviewState:'unreviewed'} as never;const out=resolveRetailProductCandidates(p,{});assert.equal(out.resolutionState,'candidate');assert.ok(out.blockers.includes('review-required'));});
test('feature identity enrichment preserves evidence and blocks unreviewed identities',()=>{const input={artistId:null,artistIdentityState:'unresolved',releaseId:null,releaseIdentityState:'unresolved',blockers:[],eligibilityState:'feature-resolver-candidate'} as never;const out=enrichAlbumFeatureInputIdentity(input,{artistId:'a',artistState:'candidate',releaseId:'r',releaseState:'candidate'});assert.equal(out.artistId,'a');assert.equal(out.eligibilityState,'blocked');assert.ok(out.blockers.includes('release-unresolved'));});
