import test from 'node:test';
import assert from 'node:assert/strict';
import { fromDirectAlbumObservation, fromRetailObservation, classifyAlbumFeatureComparability } from '../lib/alternative-evidence/canonicalAlbumFeatureInput';
const d=(s:string,u:string)=>({observationId:'o',providerId:'p',providerObservationId:null,providerArtistId:null,providerReleaseId:null,providerEditionId:null,providerSkuId:null,fandexArtistId:null,fandexReleaseId:null,fandexReleaseFamilyId:null,semantic:s,value:100,unit:u,territory:null,format:null,providerPeriod:null,providerPublishedAt:null,observedAt:'2025-01-01',collectedAt:'2025-01-01',revisionId:null,revisionObservedAt:null,supersedesObservationId:null,knowledgeMode:'current-research',scopeRole:'standalone',parentObservationId:null,evidenceDigest:'d',syntheticFixture:true,contractVersion:'direct-album-observation-v1'} as never);
const e=(o:string)=>({evidenceId:'e',origin:o,sourceId:'s',sourceUrl:null,acquisitionProvider:'fixture',reportedProvider:null,observedAt:'2025-01-01',collectedAt:'2025-01-01',sourcePublishedAt:null,evidenceDigest:'d',researchOnly:true,contractVersion:'alternative-evidence-v1'} as never);
const r=(s:string,n:number|null)=>({observationId:'r',retailerId:'yes24',retailerProductId:'i',productIdentity:null,fandexArtistId:null,fandexReleaseId:null,fandexReleaseFamilyId:null,retailerArtistText:null,retailerTitle:null,categoryFamily:'music',providerCategoryId:null,categoryResolutionState:'unresolved',chartType:'daily',semantic:s,rank:n,movement:null,providerIndex:null,providerIndexName:null,providerPeriod:null,providerPeriodState:'unresolved',providerPublishedAt:null,observedAt:'2025-01-01',collectedAt:'2025-01-01',sourceType:'synthetic-fixture',missingState:n===null?'not-ranked':'observed',evidenceDigest:'d',syntheticFixture:true,contractVersion:'retail-observation-v1'} as never);
test('direct semantics and provenance',()=>{assert.equal(fromDirectAlbumObservation(d('period-sale','physical-units'),e('direct-licensed-provider'))[0].featureKey,'providerNativePeriodSales');assert.throws(()=>fromDirectAlbumObservation(d('rank','rank'),e('news-reported-provider-value')));});
test('retail proxy and missing',()=>{const x=fromRetailObservation(r('retail-rank',3),e('authorized-public-api'))[0];assert.equal(x.featureKey,'physicalRetailLevelProxy');assert.equal(x.unit,'rank');const m=fromRetailObservation(r('retail-rank',null),e('authorized-public-api'))[0];assert.notEqual(m.availabilityState,'available');});
test('deterministic and non-comparable',()=>{const a=fromRetailObservation(r('retail-rank',3),e('authorized-public-api'))[0];const b=fromDirectAlbumObservation(d('period-sale','physical-units'),e('direct-licensed-provider'))[0];assert.equal(a.featureInputId,fromRetailObservation(r('retail-rank',3),e('authorized-public-api'))[0].featureInputId);assert.equal(classifyAlbumFeatureComparability(a,b),'not-comparable');});
