import assert from 'node:assert/strict';
import test from 'node:test';
import { evaluateNaverNewsRecurringActivationReadiness, buildNaverNewsRecurringExpectedSlots, type NaverNewsRecurringPlatformCapabilities } from '../lib/server/ingestion/naverNewsRecurringActivationReadiness';
import { NAVER_NEWS_RECURRING_DEPLOYMENT_ENV, NAVER_NEWS_RECURRING_ENABLED_ENV, NAVER_NEWS_RECURRING_QUERY_ENV, NAVER_NEWS_RECURRING_DISPLAY_ENV, NAVER_NEWS_SCHEDULER_SECRET_ENV } from '../lib/server/ingestion/naverNewsRecurringSchedulerContracts';
import { NAVER_NEWS_MANUAL_MONITORING_POLICY, createNaverNewsRecurringMonitoringPolicy, evaluateNaverNewsRecurringMonitoringSeverity, type NaverNewsRecurringMonitoringObservation } from '../lib/server/ingestion/naverNewsMonitoringPolicy';
import { NAVER_NEWS_MONITORING_SCHEDULER_ACTIVATION, NAVER_NEWS_MONITORING_SCHEDULER_EXPECTATION } from '../lib/server/ingestion/naverNewsMonitoringContracts';

const valid = (): Record<string, string> => ({
  [NAVER_NEWS_RECURRING_ENABLED_ENV]: 'approved-v128-recurring-foundation', [NAVER_NEWS_RECURRING_DEPLOYMENT_ENV]: 'production', [NAVER_NEWS_SCHEDULER_SECRET_ENV]: 'synthetic-secret', [NAVER_NEWS_RECURRING_QUERY_ENV]: '아이유', [NAVER_NEWS_RECURRING_DISPLAY_ENV]: '5',
  FANDEX_NAVER_NEWS_API_ENDPOINT: 'https://openapi.naver.com/v1/search/news.json', FANDEX_NAVER_NEWS_CLIENT_ID: 'synthetic-client-id', FANDEX_NAVER_NEWS_CLIENT_SECRET: 'synthetic-client-secret', FANDEX_RUNTIME_DATABASE_URL: 'postgresql://fandex_runtime:synthetic@synthetic-pooler.example/neondb',
});
const platform = (): NaverNewsRecurringPlatformCapabilities => ({ requestMethod: 'post', authentication: 'bearer', hourlySchedule: 'verified', duplicateDelivery: 'possible', retryBehavior: 'possible', timeoutBehavior: 'verified' });
const evaluate = (overrides: Partial<Parameters<typeof evaluateNaverNewsRecurringActivationReadiness>[0]> = {}) => evaluateNaverNewsRecurringActivationReadiness({ environment: valid(), platform: platform(), previewIsolation: 'verified', monitoringPolicyReady: true, ...overrides });

test('platform unknown/incompatible blocks readiness', () => { const r = evaluate({ platform: { ...platform(), requestMethod: 'unknown', authentication: 'unknown', hourlySchedule: 'unverified' } }); assert.equal(r.ready, false); assert.ok(r.blockers.includes('platform_request_method_unverified')); assert.ok(r.blockers.includes('platform_authentication_unverified')); });
test('exact runtime validators are enforced without leaking values', () => {
  assert.equal(evaluate().ready, true);
  const mutations: Array<(env: Record<string, string>) => void> = [e => e.FANDEX_RUNTIME_DATABASE_URL = 'postgresql://fandex_runtime:synthetic@synthetic-pooler.example/wrongdb', e => e.FANDEX_RUNTIME_DATABASE_URL = 'postgresql://other_runtime:synthetic@synthetic-pooler.example/neondb', e => e.FANDEX_RUNTIME_DATABASE_URL = 'postgresql://fandex_runtime:synthetic@synthetic.example/neondb', e => e.FANDEX_RUNTIME_DATABASE_URL = 'postgresql://fandex_runtime@synthetic-pooler.example/neondb', e => e.FANDEX_RUNTIME_DATABASE_URL = ' postgresql://fandex_runtime:synthetic@synthetic-pooler.example/neondb', e => e.FANDEX_NAVER_NEWS_API_ENDPOINT = 'https://api.example.test/v1/search', e => e.FANDEX_NAVER_NEWS_API_ENDPOINT = 'http://openapi.naver.com/v1/search/news.json', e => e.FANDEX_NAVER_NEWS_API_ENDPOINT = 'https://openapi.naver.com/v1/search/news.json?x=1', e => e.FANDEX_NAVER_NEWS_CLIENT_ID = ' ', e => e.FANDEX_NAVER_NEWS_CLIENT_SECRET = `x${String.fromCharCode(1)}`, e => e.FANDEX_NAVER_NEWS_CLIENT_ID = 'x'.repeat(1025)];
  for (const mutate of mutations) { const env = valid(); mutate(env); assert.equal(evaluate({ environment: env }).ready, false); }
  const text = JSON.stringify(evaluate()); for (const secret of ['synthetic-secret', 'postgresql://fandex_runtime:synthetic@synthetic-pooler.example/neondb', 'synthetic-client-secret']) assert.equal(text.includes(secret), false);
});
test('manual approvals are not recurring prerequisites and slots reuse v125', () => { const env = valid(); const r = evaluate({ environment: env }); assert.equal(r.ready, true); const slots = buildNaverNewsRecurringExpectedSlots({ observedAt: '2026-08-30T12:34:56.000Z', query: ' 아이유 ', display: 5 }); assert.equal(slots.currentSlotStart, '2026-08-30T12:00:00.000Z'); assert.equal(slots.previousSlotStart, '2026-08-30T11:00:00.000Z'); assert.match(slots.currentCollectionKey, /^sched-v125-naver-news-20260830t120000z-[0-9a-f]{12}$/); });
test('manual monitoring default remains unchanged; recurring policy is explicit', () => { assert.deepEqual(NAVER_NEWS_MANUAL_MONITORING_POLICY, { activation: 'manual-only', expectation: 'on_demand' }); assert.equal(NAVER_NEWS_MONITORING_SCHEDULER_ACTIVATION, 'manual-only'); assert.equal(NAVER_NEWS_MONITORING_SCHEDULER_EXPECTATION, 'on_demand'); assert.deepEqual(createNaverNewsRecurringMonitoringPolicy(10, 60), { activation: 'recurring', expectation: 'hourly', graceMinutes: 10, freshnessMinutes: 60 }); });

const observation = (overrides: Partial<NaverNewsRecurringMonitoringObservation> = {}): NaverNewsRecurringMonitoringObservation => ({ hasJobs: true, observedAt: '2026-08-30T12:05:00.000Z', currentSlotStart: '2026-08-30T12:00:00.000Z', currentSlotOutcome: 'not_run', previousSlotStart: '2026-08-30T11:00:00.000Z', previousSlotOutcome: 'succeeded', lastSucceededAt: '2026-08-30T11:30:00.000Z', expiredRunning: false, retryableFailed: false, deadLetter: false, malformedSchedulerKey: false, danglingNormalizedReference: false, consistencyMismatch: false, ...overrides });
test('severity applies grace and freshness using observed time', () => { const p = createNaverNewsRecurringMonitoringPolicy(10, 60); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation()), 'healthy'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ observedAt: '2026-08-30T12:11:00.000Z' })), 'attention'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ previousSlotOutcome: 'not_run' })), 'attention'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ observedAt: '2026-08-30T12:00:00.000Z', currentSlotOutcome: 'succeeded', lastSucceededAt: '2026-08-30T11:30:00.000Z' })), 'healthy'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ observedAt: '2026-08-30T12:00:00.000Z', currentSlotOutcome: 'succeeded', lastSucceededAt: '2026-08-30T10:59:00.000Z' })), 'attention'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ observedAt: '2026-08-30T12:00:00.000Z', currentSlotOutcome: 'succeeded', lastSucceededAt: '2026-08-30T11:00:00.000Z' })), 'healthy'); });
test('severity critical signals and no-data', () => { const p = createNaverNewsRecurringMonitoringPolicy(10, 60); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ hasJobs: false })), 'no_data'); for (const key of ['deadLetter', 'malformedSchedulerKey', 'danglingNormalizedReference', 'consistencyMismatch'] as const) assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ [key]: true })), 'critical'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ retryableFailed: true })), 'attention'); assert.equal(evaluateNaverNewsRecurringMonitoringSeverity(p, observation({ expiredRunning: true })), 'attention'); });
test('impossible temporal states fail closed', () => { const p = createNaverNewsRecurringMonitoringPolicy(10, 60); for (const o of [observation({ observedAt: 'invalid' }), observation({ lastSucceededAt: '2026-08-30T13:00:00.000Z' }), observation({ currentSlotStart: '2026-08-30T13:10:00.000Z' })]) assert.throws(() => evaluateNaverNewsRecurringMonitoringSeverity(p, o), /naver_news_monitoring_policy_invalid/); });
test('policy bounds are enforced', () => { assert.throws(() => createNaverNewsRecurringMonitoringPolicy(0, 60)); assert.throws(() => createNaverNewsRecurringMonitoringPolicy(10, 10_081)); });
