import { sha256Canonical } from '../shared/canonicalDigest';
import type { CanonicalAlbumFeatureInput } from './canonicalAlbumFeatureInput';

export const ALBUM_TEMPORAL_SNAPSHOT_CONTRACT_VERSION='album-temporal-snapshot-v1';
export type TemporalPeriodType='instant'|'realtime'|'day'|'week'|'month'|'first-day'|'first-week'|'cumulative-to-date'|'provider-native-period'|'unknown';
export type TemporalResolutionState='resolved'|'relative'|'unresolved';
export type SeriesKind='native-period'|'cumulative'|'snapshot-rank'|'provider-index'|'reported-event'|'threshold'|'diagnostic'|'unknown';
export type TemporalAvailability='available'|'missing'|'not-observed'|'not-ranked'|'unresolved'|'blocked'|'conflicting';
export type TemporalCompleteness='complete'|'partial'|'insufficient-history'|'missing'|'not-applicable'|'unknown';
export type TemporalRevisionState='original'|'revised'|'conflicting'|'unknown';
export type KnowledgeMode='as-known-at-collection'|'current-research';
export type TemporalComparabilityState='comparable'|'conditionally-comparable'|'not-comparable'|'unknown';
export type TemporalPeriod=Readonly<{type:TemporalPeriodType;start:string|null;end:string|null;label:string|null;resolutionState:TemporalResolutionState}>;
export type AlbumTemporalSnapshot=Readonly<{contractVersion:typeof ALBUM_TEMPORAL_SNAPSHOT_CONTRACT_VERSION;snapshotId:string;seriesId:string;featureInputId:string;featureInputFamilyId:string|null;contributionIdentityId:string;featureKey:string;sourceClass:string;artistId:string|null;releaseId:string|null;releaseFamilyId:string|null;semantic:string;value:number|null;unit:string|null;periodType:TemporalPeriodType;providerPeriod:string|null;providerPeriodStart:string|null;providerPeriodEnd:string|null;reportedPeriod:string|null;providerPublishedAt:string|null;sourcePublishedAt:string|null;observedAt:string|null;collectedAt:string|null;revisionObservedAt:string|null;knowledgeMode:KnowledgeMode;seriesKind:SeriesKind;availabilityState:TemporalAvailability;completenessState:TemporalCompleteness;revisionState:TemporalRevisionState;evidenceDigest:string;supersedesSnapshotId:string|null;blockers:readonly string[]}>;
export type TemporalWindow=Readonly<{start:string;end:string;expectedResolution:'day'|'week'|'month'|'unknown';expectedObservationCount:number|null}>;
export type WindowAssessment=Readonly<{window:TemporalWindow;expectedCount:number|null;observedCount:number;missingCount:number;completeness:TemporalCompleteness;coverageRatio:number|null;snapshots:readonly AlbumTemporalSnapshot[]}>;

const parsePeriod=(input:CanonicalAlbumFeatureInput):TemporalPeriod=>{const p=input.providerPeriod; if(input.periodType==='first-week')return {type:'first-week',start:null,end:null,label:p??input.reportedPeriod,resolutionState:'relative'}; if(!p)return {type:input.periodType==='instant/realtime'?'realtime':'unknown',start:null,end:null,label:null,resolutionState:'unresolved'}; if(/^\d{4}-\d{2}-\d{2}$/.test(p))return {type:input.periodType==='month'?'month':input.periodType==='week'?'week':'day',start:p,end:p,label:p,resolutionState:'resolved'}; return {type:'provider-native-period',start:null,end:null,label:p,resolutionState:'relative'};};
const seriesKind=(input:CanonicalAlbumFeatureInput):SeriesKind=>input.semantic==='cumulative-sale'?'cumulative':input.semantic==='rank'?'snapshot-rank':input.semantic==='index'?'provider-index':input.featureKey==='diagnosticRank'?'snapshot-rank':input.featureKey==='diagnosticProviderIndex'?'provider-index':input.featureRole==='context'?'reported-event':input.periodType==='first-week'||input.periodType==='first-day'?'reported-event':input.featureRole==='diagnostic'?'diagnostic':'native-period';
export function buildAlbumTemporalSeriesId(input:CanonicalAlbumFeatureInput):string{return sha256Canonical({sourceClass:input.sourceClass,provider:input.provenance.reportedProvider,retailer:input.retailerId,featureKey:input.featureKey,artist:input.artistId,release:input.releaseId??input.releaseFamilyId,semantic:input.semantic,unit:input.unit,territory:input.territory,format:input.format,periodType:input.periodType,category:input.providerCategoryId,chart:input.chartType});}
export function buildAlbumTemporalSnapshotId(seriesId:string,input:CanonicalAlbumFeatureInput):string{return sha256Canonical({contractVersion:ALBUM_TEMPORAL_SNAPSHOT_CONTRACT_VERSION,seriesId,featureInputId:input.featureInputId,providerPeriod:input.providerPeriod,observedAt:input.observedAt,revisionObservedAt:input.revisionObservedAt,value:input.value,unit:input.unit});}
export function fromCanonicalAlbumFeatureInput(input:CanonicalAlbumFeatureInput):AlbumTemporalSnapshot{const period=parsePeriod(input);const kind=seriesKind(input);const seriesId=buildAlbumTemporalSeriesId(input);const available=input.availabilityState==='available'&&input.value!==null;const blockers=[...input.blockers];if(input.periodType==='first-week'&&period.resolutionState!=='relative')blockers.push('first-week-period-unresolved');return Object.freeze({contractVersion:ALBUM_TEMPORAL_SNAPSHOT_CONTRACT_VERSION,snapshotId:buildAlbumTemporalSnapshotId(seriesId,input),seriesId,featureInputId:input.featureInputId,featureInputFamilyId:input.featureInputFamilyId,contributionIdentityId:input.contributionIdentity.contributionIdentityId,featureKey:input.featureKey,sourceClass:input.sourceClass,artistId:input.artistId,releaseId:input.releaseId,releaseFamilyId:input.releaseFamilyId,semantic:input.semantic,value:input.value,unit:input.unit,periodType:period.type,providerPeriod:input.providerPeriod,providerPeriodStart:period.start,providerPeriodEnd:period.end,reportedPeriod:input.reportedPeriod,providerPublishedAt:input.providerPublishedAt,sourcePublishedAt:input.sourcePublishedAt,observedAt:input.observedAt,collectedAt:input.collectedAt,revisionObservedAt:input.revisionObservedAt,knowledgeMode:input.knowledgeMode==='as-known-at-collection'?'as-known-at-collection':'current-research',seriesKind:kind,availabilityState:available?'available':input.availabilityState as TemporalAvailability,completenessState:available?'complete':'missing',revisionState:input.revisionObservedAt?'revised':'original',evidenceDigest:input.provenance.evidenceDigest,supersedesSnapshotId:null,blockers});}
export type CumulativeDelta=Readonly<{previousSnapshotId:string|null;currentSnapshotId:string;delta:number|null;state:'available'|'first-observation'|'negative-delta'|'not-comparable'|'missing';blockers:readonly string[]}>;
export function deriveCumulativeDeltas(snapshots:readonly AlbumTemporalSnapshot[]):readonly CumulativeDelta[]{const ordered=[...snapshots].sort((a,b)=>(a.providerPeriod??a.collectedAt??'').localeCompare(b.providerPeriod??b.collectedAt??''));return ordered.map((current,i)=>{if(current.seriesKind!=='cumulative'||current.value===null)return {previousSnapshotId:i?ordered[i-1].snapshotId:null,currentSnapshotId:current.snapshotId,delta:null,state:'missing',blockers:['cumulative-value-missing']};if(i===0)return {previousSnapshotId:null,currentSnapshotId:current.snapshotId,delta:null,state:'first-observation',blockers:['no-comparable-previous-observation']};const previous=ordered[i-1];if(previous.seriesId!==current.seriesId||previous.unit!==current.unit||previous.value===null)return {previousSnapshotId:previous.snapshotId,currentSnapshotId:current.snapshotId,delta:null,state:'not-comparable',blockers:['cumulative-scope-not-comparable']};const delta=current.value-previous.value;return delta<0?{previousSnapshotId:previous.snapshotId,currentSnapshotId:current.snapshotId,delta,state:'negative-delta',blockers:['negative-delta-revision-review']}:{previousSnapshotId:previous.snapshotId,currentSnapshotId:current.snapshotId,delta,state:'available',blockers:[]};});}
export function selectAsKnownAt(snapshots:readonly AlbumTemporalSnapshot[],cutoff:string):readonly AlbumTemporalSnapshot[]{return snapshots.filter(s=>(s.collectedAt??'')<=cutoff&&(s.revisionObservedAt===null||s.revisionObservedAt<=cutoff));}
export function selectCurrentResearchHead(snapshots:readonly AlbumTemporalSnapshot[]):Readonly<{snapshots:readonly AlbumTemporalSnapshot[];state:'resolved'|'conflicting'|'empty'}>{const active=snapshots.filter(s=>!snapshots.some(other=>other.supersedesSnapshotId===s.snapshotId));const values=new Set(active.map(s=>`${s.providerPeriod}|${s.value}|${s.unit}`));return {snapshots:active,state:active.length===0?'empty':values.size>1?'conflicting':'resolved'};}
export function assessWindow(snapshots:readonly AlbumTemporalSnapshot[],window:TemporalWindow):WindowAssessment{const inside=snapshots.filter(s=>(s.providerPeriod??'')>=window.start&&(s.providerPeriod??'')<=window.end);const expected=window.expectedObservationCount;const missing=expected===null?0:Math.max(0,expected-inside.length);const completeness=expected===null?(inside.length?'unknown':'missing'):inside.length===0?'missing':missing?'partial':'complete';return {window,expectedCount:expected,observedCount:inside.length,missingCount:missing,completeness,coverageRatio:expected===null?null:inside.length/expected,snapshots:inside};}
export function makeTemporalWindow(start:string,end:string,resolution:'day'|'week'|'month'|'unknown',expectedObservationCount:number|null):TemporalWindow{return {start,end,expectedResolution:resolution,expectedObservationCount};}
export function compareTemporalSnapshots(a:AlbumTemporalSnapshot,b:AlbumTemporalSnapshot):TemporalComparabilityState{if(a.seriesId!==b.seriesId||a.semantic!==b.semantic||a.unit!==b.unit)return 'not-comparable';if(a.periodType==='first-week'||b.periodType==='first-week')return a.periodType===b.periodType?'conditionally-comparable':'not-comparable';if(a.seriesKind!==b.seriesKind)return 'not-comparable';return a.periodType===b.periodType?'comparable':'conditionally-comparable';}
export function validateTemporalSnapshotSet(snapshots:readonly AlbumTemporalSnapshot[]):Readonly<{valid:boolean;issues:readonly string[]}>{const issues:string[]=[];for(let i=0;i<snapshots.length;i++)for(let j=i+1;j<snapshots.length;j++){const a=snapshots[i],b=snapshots[j];if(a.seriesId===b.seriesId&&a.providerPeriod===b.providerPeriod&&a.value!==b.value)issues.push('same-period-conflict');if(a.seriesKind==='cumulative'&&b.seriesKind==='native-period'&&a.seriesId===b.seriesId)issues.push('cumulative-native-period-mix');if(a.contributionIdentityId===b.contributionIdentityId)issues.push('repeated-contribution-recollection');}return {valid:issues.length===0,issues:[...new Set(issues)]};}
export interface AlbumTemporalResolver{selectAsKnownAt(snapshots:readonly AlbumTemporalSnapshot[],cutoff:string):readonly AlbumTemporalSnapshot[];assessWindow(snapshots:readonly AlbumTemporalSnapshot[],window:TemporalWindow):WindowAssessment;}
