import { sha256Canonical } from '../shared/canonicalDigest';
import type { CanonicalAlbumFeatureInput } from './canonicalAlbumFeatureInput';
import type { AlbumTemporalSnapshot, WindowAssessment } from './albumTemporalSnapshot';
import { ALBUM_METHODOLOGY_VERSION, assessAbsoluteLevel, assessRetailLevel, assessRetailMomentum, assessRetailBreadth, assessReportedSalesContext, assessCertificationContext, validateMethodologyCombination, type ComponentResult, type MethodologyState } from './albumMethodology';
export const SYNTHETIC_VALIDATION_CONTRACT_VERSION='album-synthetic-validation-v1' as const;
export type OverallEvidenceState='absolute-available'|'proxy-only'|'context-only'|'diagnostic-only'|'mixed-nonabsolute'|'insufficient'|'blocked'|'conflicting'|'synthetic-only';
export type AlbumMethodologyEvaluation=Readonly<{evaluationId:string;methodologyVersion:typeof ALBUM_METHODOLOGY_VERSION;evaluationMode:'synthetic-validation';evidenceMode:'synthetic';overallEvidenceState:OverallEvidenceState;absoluteLevel:ComponentResult;retailLevel:ComponentResult;retailMomentum:ComponentResult;retailBreadth:ComponentResult;reportedSalesContext:ComponentResult;certificationContext:ComponentResult;diagnostics:ComponentResult;contributionSummary:Readonly<{sourceEvidenceCount:number;uniqueContributionCount:number}>;blockers:readonly string[];warnings:readonly string[];trace:readonly string[];syntheticOnly:true;liveReadiness:'not-established';productionReady:false}>;
export type AlbumMethodologyScenario=Readonly<{scenarioId:string;description:string;inputs:readonly CanonicalAlbumFeatureInput[];snapshots:readonly AlbumTemporalSnapshot[];momentumWindow?:WindowAssessment|null;previousMomentumWindow?:WindowAssessment|null;expectedOverall?:OverallEvidenceState|string;expectedBlockers?:readonly string[];forbiddenOutcomes?:readonly string[]}>;
export type AlbumMethodologyScenarioResult=Readonly<{scenarioId:string;passed:boolean;evaluation:AlbumMethodologyEvaluation;failures:readonly string[]}>;
export type AlbumSyntheticValidationReport=Readonly<{methodologyVersion:typeof ALBUM_METHODOLOGY_VERSION;scenarioCount:number;passedScenarioCount:number;failedScenarioCount:number;invariantCount:number;passedInvariantCount:number;failedInvariantCount:number;scenarioResults:readonly AlbumMethodologyScenarioResult[];architectureReadiness:'methodology-evaluable';liveReadiness:'not-established';productionReadiness:'not-ready';syntheticOnly:true}>;
const empty=(component:string,state:MethodologyState):ComponentResult=>({component,state,eligibleInputIds:[],excludedInputIds:[],conditionalInputIds:[],decisionIds:[],rawStatistics:{},blockers:[],reasonCodes:[],methodologyVersion:ALBUM_METHODOLOGY_VERSION});
export function evaluateAlbumMethodologyScenario(s:AlbumMethodologyScenario):AlbumMethodologyEvaluation{const i=s.inputs;const abs=assessAbsoluteLevel(i);const retail=i.find(x=>x.featureKey==='physicalRetailLevelProxy');const level=retail?assessRetailLevel(retail):empty('retailLevel','insufficient-data');const momentum=assessRetailMomentum(s.momentumWindow??null,s.previousMomentumWindow??null);const breadth=assessRetailBreadth(i.filter(x=>x.retailerId!==null));const news=assessReportedSalesContext(i);const cert=i.find(x=>x.sourceClass==='public-page-observation');const certification=assessCertificationContext(cert??null);const diagnostics=i.some(x=>x.featureRole==='diagnostic')?empty('diagnostics','diagnostic-only'):empty('diagnostics','insufficient-data');const unique=new Set(i.map(x=>x.contributionIdentity.contributionIdentityId));const combo=validateMethodologyCombination(i);const blockers=[...new Set([...abs.blockers,...level.blockers,...momentum.blockers,...breadth.blockers,...combo.issues])];const overall:OverallEvidenceState=abs.state==='ready'?'synthetic-only':level.state==='provisional'?'proxy-only':news.state==='ready'?'context-only':diagnostics.state==='diagnostic-only'?'diagnostic-only':combo.valid?'insufficient':'conflicting';const evaluationId=sha256Canonical({contractVersion:SYNTHETIC_VALIDATION_CONTRACT_VERSION,scenarioId:s.scenarioId,inputIds:i.map(x=>x.featureInputId),snapshotIds:s.snapshots.map(x=>x.snapshotId)});return Object.freeze({evaluationId,methodologyVersion:ALBUM_METHODOLOGY_VERSION,evaluationMode:'synthetic-validation',evidenceMode:'synthetic',overallEvidenceState:overall,absoluteLevel:abs,retailLevel:level,retailMomentum:momentum,retailBreadth:breadth,reportedSalesContext:news,certificationContext:certification,diagnostics,contributionSummary:{sourceEvidenceCount:i.length,uniqueContributionCount:unique.size},blockers,warnings:[],trace:i.flatMap(x=>[x.featureInputId,...s.snapshots.filter(y=>y.featureInputId===x.featureInputId).map(y=>y.snapshotId)]),syntheticOnly:true,liveReadiness:'not-established',productionReady:false});}
export function runAlbumSyntheticValidation(scenarios:readonly AlbumMethodologyScenario[]):AlbumSyntheticValidationReport{const results=scenarios.map(s=>{const evaluation=evaluateAlbumMethodologyScenario(s);const failures:string[]=[];if(s.expectedOverall&&evaluation.overallEvidenceState!==s.expectedOverall)failures.push('unexpected-overall-state');for(const b of s.expectedBlockers??[])if(!evaluation.blockers.includes(b))failures.push(`missing-blocker:${b}`);if(evaluation.productionReady)failures.push('synthetic-marked-production-ready');return {scenarioId:s.scenarioId,passed:failures.length===0,evaluation,failures};});const passed=results.filter(x=>x.passed).length;return {methodologyVersion:ALBUM_METHODOLOGY_VERSION,scenarioCount:results.length,passedScenarioCount:passed,failedScenarioCount:results.length-passed,invariantCount:results.length*2,passedInvariantCount:passed*2,failedInvariantCount:(results.length-passed)*2,scenarioResults:results,architectureReadiness:'methodology-evaluable',liveReadiness:'not-established',productionReadiness:'not-ready',syntheticOnly:true};}
export function validateSyntheticCombination(inputs:readonly CanonicalAlbumFeatureInput[]){return validateMethodologyCombination(inputs);}
