import { sha256Canonical } from '../shared/canonicalDigest';
import type { CanonicalAlbumFeatureInput } from './canonicalAlbumFeatureInput';
import type { WindowAssessment } from './albumTemporalSnapshot';

export const ALBUM_METHODOLOGY_VERSION='album-methodology-v1' as const;
export type MethodologyState='ready'|'provisional'|'insufficient-data'|'insufficient-history'|'insufficient-universe'|'insufficient-sources'|'identity-blocked'|'temporally-incomparable'|'conflicting'|'rights-blocked'|'diagnostic-only'|'unavailable'|'unknown';
export type MethodologyDecision='include'|'exclude'|'conditional'|'diagnostic-only'|'context-only';
export type MethodologyReason=string;
export type ComponentResult=Readonly<{component:string;state:MethodologyState;eligibleInputIds:readonly string[];excludedInputIds:readonly string[];conditionalInputIds:readonly string[];decisionIds:readonly string[];rawStatistics:Readonly<Record<string,number|string|null>>;blockers:readonly string[];reasonCodes:readonly string[];methodologyVersion:typeof ALBUM_METHODOLOGY_VERSION}>;
export type AlbumMethodologyDefinition=Readonly<{methodologyVersion:typeof ALBUM_METHODOLOGY_VERSION;construct:'physical completed-purchase-class sales reaction';primaryObjective:'physical purchase reaction';normalizationMethod:'unresolved';productionState:'not-production-approved';components:readonly string[]}>;
export const ALBUM_METHODOLOGY_DEFINITION:AlbumMethodologyDefinition=Object.freeze({methodologyVersion:ALBUM_METHODOLOGY_VERSION,construct:'physical completed-purchase-class sales reaction',primaryObjective:'physical purchase reaction',normalizationMethod:'unresolved',productionState:'not-production-approved',components:['absoluteLevel','retailLevel','retailMomentum','retailBreadth','reportedSalesContext','certificationContext','diagnostics']});
export type AlbumMethodologyDecision=Readonly<{decisionId:string;component:string;featureInputId:string|null;snapshotId:string|null;decision:MethodologyDecision;reasonCodes:readonly string[];methodologyVersion:typeof ALBUM_METHODOLOGY_VERSION}>;
export function buildMethodologyDecisionId(input:Omit<AlbumMethodologyDecision,'decisionId'|'methodologyVersion'>):string{return sha256Canonical({methodologyVersion:ALBUM_METHODOLOGY_VERSION,...input});}
const result=(component:string,state:MethodologyState,eligible:string[],excluded:string[],conditional:string[],blockers:string[],raw:Record<string,number|string|null>={},reasons:string[]=blockers):ComponentResult=>({component,state,eligibleInputIds:eligible,excludedInputIds:excluded,conditionalInputIds:conditional,decisionIds:[],rawStatistics:raw,blockers:[...new Set(blockers)],reasonCodes:[...new Set(reasons)],methodologyVersion:ALBUM_METHODOLOGY_VERSION});
export function assessAbsoluteLevel(inputs:readonly CanonicalAlbumFeatureInput[]):ComponentResult {const e:string[]=[],x:string[]=[],c:string[]=[],b:string[]=[];for(const i of inputs){const bad=i.featureRole!=='absolute'||i.value===null||i.unit!=='physical-units';if(bad){x.push(i.featureInputId);if(i.featureKey==='diagnosticRank'||i.semantic==='rank')b.push('excluded-rank-from-absolute');else if(i.featureKey==='diagnosticProviderIndex'||i.semantic==='index')b.push('excluded-provider-index-not-units');else if(i.semantic==='shipment')b.push('shipment-not-completed-purchase');else if(i.semantic==='preorder')b.push('preorder-not-completed-purchase');else if(i.semantic==='chart-certified-unit')b.push('certification-not-exact');else if(i.sourceClass==='retailer-api')b.push('retailer-panel-coverage-unresolved');continue;}if(i.artistIdentityState!=='resolved'||i.releaseIdentityState!=='resolved'){c.push(i.featureInputId);b.push('identity-unresolved');}else e.push(i.featureInputId);}return result('absoluteLevel',e.length?'ready':c.length?'identity-blocked':'unavailable',e,x,c,b);}
export function assessRetailLevel(input:CanonicalAlbumFeatureInput):ComponentResult {if(input.featureKey!=='physicalRetailLevelProxy'||input.value===null)return result('retailLevel','insufficient-data',[],[input.featureInputId],[],['retail-rank-missing']);if(input.categoryResolutionState!=='resolved'||input.providerCategoryId===null)return result('retailLevel','insufficient-universe',[],[input.featureInputId],[],['rank-universe-unknown']);return result('retailLevel','provisional',[input.featureInputId],[],[],['normalization-pending'],{normalizationMethod:'unresolved',rank:input.value});}
export function deriveRawRankDelta(previous:CanonicalAlbumFeatureInput,current:CanonicalAlbumFeatureInput){if(previous.retailerId!==current.retailerId||previous.chartType!==current.chartType||previous.providerCategoryId!==current.providerCategoryId||previous.releaseId!==current.releaseId)return {state:'not-comparable' as const,rawRankImprovement:null,blockers:['rank-delta-dimensions-mismatch']};if(previous.value===null||current.value===null)return {state:'categorical' as const,rawRankImprovement:null,blockers:['not-ranked-categorical-event']};return {state:'ready' as const,rawRankImprovement:previous.value-current.value,blockers:[]};}
export function assessRetailMomentum(window:WindowAssessment|null,previous:WindowAssessment|null):ComponentResult {if(!window||!previous)return result('retailMomentum','insufficient-history',[],[],[],['comparable-window-missing']);if(window.completeness!=='complete'||previous.completeness!=='complete')return result('retailMomentum','insufficient-history',[],[],[],['incomplete-window']);return result('retailMomentum','provisional',window.snapshots.map(s=>s.snapshotId),[],[],['raw-statistics-only'],{observedCount:window.observedCount,previousObservedCount:previous.observedCount});}
export function assessRetailBreadth(inputs:readonly CanonicalAlbumFeatureInput[]):ComponentResult {const groups=new Set(inputs.map(i=>i.retailerId).filter(Boolean));if(groups.size<2)return result('retailBreadth','insufficient-sources',[],inputs.map(i=>i.featureInputId),[],['insufficient-independent-retailers'],{retailerGroups:groups.size});return result('retailBreadth','provisional',inputs.map(i=>i.featureInputId),[],[],['independence-review-required'],{retailerGroups:groups.size});}
export function assessReportedSalesContext(inputs:readonly CanonicalAlbumFeatureInput[]):ComponentResult {const e=inputs.filter(i=>(i.featureKey==='reportedFirstWeekSales'||i.featureKey==='reportedCumulativeSales')&&i.value!==null);return result('reportedSalesContext',e.length?'ready':'insufficient-data',e.map(i=>i.featureInputId),inputs.filter(i=>!e.includes(i)).map(i=>i.featureInputId),[],[],{});}
export function assessCertificationContext(input:CanonicalAlbumFeatureInput|null):ComponentResult{return input?result('certificationContext','ready',[],[input.featureInputId],[],['certification-threshold-not-exact']):result('certificationContext','insufficient-data',[],[],[],[]);}
export function featureReadiness(input:CanonicalAlbumFeatureInput){const identity=input.artistIdentityState==='resolved'&&input.releaseIdentityState==='resolved'?'ready':'identity-blocked';const technical=input.value===null?'insufficient-data':'ready';const temporal=input.providerPeriod||input.reportedPeriod?'ready':'temporally-incomparable';return {technicalState:technical,identityState:identity,temporalState:temporal,comparabilityState:input.comparabilityState==='not-comparable'?'temporally-incomparable':'ready',coverageState:input.categoryResolutionState==='resolved'?'ready':'insufficient-universe',authorizationState:'unknown' as const,overallMethodologyState:identity==='ready'&&technical==='ready'?'provisional':'identity-blocked',blockers:identity==='ready'?[]:['identity-unresolved']};}
export function validateMethodologyCombination(inputs:readonly CanonicalAlbumFeatureInput[]){const issues:string[]=[];const keys=new Set(inputs.map(i=>i.featureKey));if(keys.has('diagnosticRank')&&keys.has('physicalPurchaseAbsoluteLevel'))issues.push('retail-rank-direct-units-not-additive');if(inputs.some(i=>i.provenance.reportedProvider==='circle-chart')&&inputs.some(i=>i.provenance.reportedProvider==='hanteo-chart'))issues.push('circle-hanteo-raw-sum-forbidden');if(inputs.some(i=>i.featureKey==='physicalRetailLevelProxy')&&inputs.some(i=>i.featureRole==='absolute'))issues.push('retail-proxy-direct-not-additive');return {valid:issues.length===0,issues:[...new Set(issues)]};}
