import { sha256Canonical } from '../shared/canonicalDigest';
import type { AlternativeEvidence, AlternativeEvidenceOrigin, AlbumResearchClaim } from './contracts';
import type { DirectAlbumObservation, DirectAlbumObservationSemantic } from './directAlbumProvider';
import type { RetailObservation } from './retailObservation';

export const CANONICAL_ALBUM_FEATURE_INPUT_CONTRACT_VERSION = 'canonical-album-feature-input-v1';
export type AlbumFeatureKey = 'physicalPurchaseAbsoluteLevel'|'physicalRetailLevelProxy'|'physicalRetailMomentumEvidence'|'retailBreadthEvidence'|'reportedFirstWeekSales'|'reportedCumulativeSales'|'providerNativePeriodSales'|'diagnosticRank'|'diagnosticProviderIndex'|'preorderDiagnostic'|'shipmentDiagnostic'|'unknownAlbumEvidence';
export type AlbumFeatureRole = 'absolute'|'proxy'|'context'|'diagnostic'|'leading-indicator'|'unsupported'|'unknown';
export type AlbumAvailabilityState = 'available'|'missing'|'not-observed'|'not-ranked'|'not-applicable'|'unresolved'|'blocked'|'conflicting';
export type AlbumFeatureSourceClass = 'direct-provider'|'retailer-api'|'news-reported-provider'|'news-reported-agency'|'official-announcement'|'public-page-observation'|'synthetic-fixture'|'unknown';
export type AlbumFeatureEligibility = 'research-only'|'shadow-candidate'|'feature-resolver-candidate'|'blocked'|'diagnostic-only';
export type AlbumProxyFallbackState = 'absolute-available'|'proxy-available'|'context-only'|'diagnostic-only'|'missing'|'blocked';
export type AlbumComparabilityState = 'comparable'|'conditionally-comparable'|'not-comparable'|'unknown';
export type AlbumDuplicationState = 'independent'|'same-underlying-observation'|'possible-duplicate'|'syndicated'|'derived-from'|'unknown';
export type AlbumPeriodType = 'instant/realtime'|'day'|'week'|'first-day'|'first-week'|'month'|'cumulative-to-date'|'provider-native-period'|'unknown';
export type AlbumContributionRelationship = AlbumDuplicationState;
export type AlbumFeatureQualityState = 'clear'|'partial'|'unknown'|'conflicting';

export type AlbumContributionIdentity = Readonly<{ contributionIdentityId:string; sourceEvidenceId:string; claimFamilyId:string|null; underlyingObservationId:string|null; scopeKey:string }>;
export type AlbumFeatureProvenance = Readonly<{ origin:AlternativeEvidenceOrigin; acquisitionProvider:string; reportedProvider:string|null; sourceUrl:string|null; evidenceDigest:string; researchOnly:true }>;
export type CanonicalAlbumFeatureInput = Readonly<{
  contractVersion: typeof CANONICAL_ALBUM_FEATURE_INPUT_CONTRACT_VERSION; featureInputId:string; featureInputFamilyId:string|null;
  featureKey:AlbumFeatureKey; featureRole:AlbumFeatureRole; sourceClass:AlbumFeatureSourceClass; sourceEvidenceId:string; sourceObservationId:string|null;
  contributionIdentity:AlbumContributionIdentity; provenance:AlbumFeatureProvenance;
  artistId:string|null; artistIdentityState:string; releaseId:string|null; releaseIdentityState:string; releaseFamilyId:string|null; editionId:string|null; skuId:string|null;
  semantic:string; value:number|null; unit:string|null; territory:string|null; format:string|null;
  providerPeriod:string|null; reportedPeriod:string|null; sourcePublishedAt:string|null; providerPublishedAt:string|null; observedAt:string|null; collectedAt:string|null; revisionObservedAt:string|null; knowledgeMode:string;
  periodType:AlbumPeriodType; availabilityState:AlbumAvailabilityState; qualityState:AlbumFeatureQualityState; eligibilityState:AlbumFeatureEligibility; proxyFallbackState:AlbumProxyFallbackState; comparabilityState:AlbumComparabilityState; crossSourceDuplicationState:AlbumDuplicationState;
  retailerId:string|null; retailerProductId:string|null; categoryFamily:string|null; providerCategoryId:string|null; categoryResolutionState:string|null; chartType:string|null; movementType:'provider-reported-movement'|'snapshot-computed-rank-change'|null; aggregationScope:string|null; parentInputId:string|null; blockers:readonly string[];
}>;

const sourceClassForOrigin = (o:AlternativeEvidenceOrigin):AlbumFeatureSourceClass => o==='news-reported-provider-value'?'news-reported-provider':o==='news-reported-agency-value'?'news-reported-agency':o==='official-artist-or-agency-announcement'?'official-announcement':o==='authorized-public-api'?'retailer-api':o==='retailer-public-observation'?'public-page-observation':o==='direct-licensed-provider'?'direct-provider':o==='existing-local-dataset'?'unknown':'unknown';
const periodType = (p:string|null, semantic:string):AlbumPeriodType => semantic==='first-day-sale'?'first-day':semantic==='first-week-sale'?'first-week':semantic==='cumulative-sale'?'cumulative-to-date':p?.includes('month')?'month':p?.includes('day')?'day':p?'provider-native-period':'unknown';
const semanticUnitValid = (s:string,u:string|null) => (s==='rank'&&u==='rank')||(s==='index'&&u==='provider-index')||(['consumer-retail-sale','retailer-panel-sale','period-sale','first-day-sale','first-week-sale','cumulative-sale','preorder','shipment'].includes(s)&&u==='physical-units')||s==='unknown';
const roleFor = (key:AlbumFeatureKey):AlbumFeatureRole => key==='physicalPurchaseAbsoluteLevel'||key==='providerNativePeriodSales'?'absolute':key==='physicalRetailLevelProxy'||key==='physicalRetailMomentumEvidence'||key==='retailBreadthEvidence'?'proxy':key==='reportedFirstWeekSales'||key==='reportedCumulativeSales'?'context':key==='preorderDiagnostic'?'leading-indicator':key==='diagnosticRank'||key==='diagnosticProviderIndex'||key==='shipmentDiagnostic'?'diagnostic':'unsupported';

function make(input: Omit<CanonicalAlbumFeatureInput,'featureInputId'|'featureInputFamilyId'|'contributionIdentity'> & { claimFamilyId?:string|null; underlyingObservationId?:string|null; scopeKey?:string }): CanonicalAlbumFeatureInput {
  const base = { sourceEvidenceId:input.sourceEvidenceId, sourceObservationId:input.sourceObservationId, featureKey:input.featureKey, semantic:input.semantic, value:input.value, unit:input.unit, territory:input.territory, providerPeriod:input.providerPeriod, reportedPeriod:input.reportedPeriod, scopeKey:input.scopeKey??input.releaseId??'unknown', contractVersion:CANONICAL_ALBUM_FEATURE_INPUT_CONTRACT_VERSION };
  const id=sha256Canonical(base); const contributionIdentityId=sha256Canonical({ ...base, claimFamilyId:input.claimFamilyId??null, underlyingObservationId:input.underlyingObservationId??null });
  const featureFamilyId=sha256Canonical({ featureKey:input.featureKey, semantic:input.semantic, value:input.value, unit:input.unit, territory:input.territory, providerPeriod:input.providerPeriod, scopeKey:input.scopeKey??input.releaseId??'unknown' });
  return Object.freeze({ ...input, featureInputId:id, featureInputFamilyId:featureFamilyId, contributionIdentity:Object.freeze({ contributionIdentityId, sourceEvidenceId:input.sourceEvidenceId, claimFamilyId:input.claimFamilyId??null, underlyingObservationId:input.underlyingObservationId??null, scopeKey:input.scopeKey??input.releaseId??'unknown' }) });
}

export function buildAlbumFeatureInputId(input: Pick<CanonicalAlbumFeatureInput,'sourceEvidenceId'|'sourceObservationId'|'featureKey'|'semantic'|'value'|'unit'|'territory'|'providerPeriod'|'releaseId'>):string { return sha256Canonical(input); }

export function fromDirectAlbumObservation(observation:DirectAlbumObservation, evidence:AlternativeEvidence):readonly CanonicalAlbumFeatureInput[] {
  if (!['direct-licensed-provider','authorized-public-api'].includes(evidence.origin)) throw new Error('direct-feature-provenance-mismatch');
  let key:AlbumFeatureKey; let eligibility:AlbumFeatureEligibility='feature-resolver-candidate'; const blockers:string[]=[];
  switch(observation.semantic as DirectAlbumObservationSemantic){ case 'first-week-sale':key='reportedFirstWeekSales';break; case 'cumulative-sale':key='reportedCumulativeSales';break; case 'rank':key='diagnosticRank';eligibility='diagnostic-only';break; case 'index':key='diagnosticProviderIndex';eligibility='diagnostic-only';break; case 'preorder':key='preorderDiagnostic';eligibility='diagnostic-only';break; case 'shipment':key='shipmentDiagnostic';eligibility='diagnostic-only';break; case 'first-day-sale':key='unknownAlbumEvidence';eligibility='blocked';blockers.push('first-day-not-first-week');break; case 'period-sale': case 'consumer-retail-sale': case 'retailer-panel-sale':key='providerNativePeriodSales';break; default:key='unknownAlbumEvidence';eligibility='blocked';blockers.push('unsupported-semantic'); }
  const absolute=key==='providerNativePeriodSales' && ['physical-units'].includes(observation.unit) && observation.value!==null;
  if(key==='providerNativePeriodSales'&&!absolute){ eligibility='blocked'; blockers.push('absolute-semantic-or-unit-unresolved'); }
  const availability=observation.value===null?'missing':semanticUnitValid(observation.semantic,observation.unit)?'available':'blocked';
  if(availability==='blocked') blockers.push('semantic-unit-mismatch');
  return [make({contractVersion:CANONICAL_ALBUM_FEATURE_INPUT_CONTRACT_VERSION,featureKey:key,featureRole:roleFor(key),sourceClass:'direct-provider',sourceEvidenceId:evidence.evidenceId,sourceObservationId:observation.observationId,provenance:{origin:evidence.origin,acquisitionProvider:evidence.acquisitionProvider,reportedProvider:evidence.reportedProvider,sourceUrl:evidence.sourceUrl,evidenceDigest:evidence.evidenceDigest,researchOnly:true},artistId:observation.fandexArtistId,artistIdentityState:observation.fandexArtistId?'resolved':'unresolved',releaseId:observation.fandexReleaseId,releaseIdentityState:observation.fandexReleaseId?'resolved':'unresolved',releaseFamilyId:observation.fandexReleaseFamilyId,editionId:observation.providerEditionId,skuId:observation.providerSkuId,semantic:observation.semantic,value:observation.value,unit:observation.unit,territory:observation.territory,format:observation.format,providerPeriod:observation.providerPeriod,reportedPeriod:null,sourcePublishedAt:null,providerPublishedAt:observation.providerPublishedAt,observedAt:observation.observedAt,collectedAt:observation.collectedAt,revisionObservedAt:observation.revisionObservedAt,knowledgeMode:observation.knowledgeMode,periodType:periodType(observation.providerPeriod,observation.semantic),availabilityState:availability,qualityState:'unknown',eligibilityState:eligibility,proxyFallbackState:key==='providerNativePeriodSales'?'absolute-available':roleFor(key)==='diagnostic'?'diagnostic-only':'context-only',comparabilityState:'unknown',crossSourceDuplicationState:'unknown',retailerId:null,retailerProductId:null,categoryFamily:null,providerCategoryId:null,categoryResolutionState:null,chartType:null,movementType:null,aggregationScope:observation.scopeRole,parentInputId:observation.parentObservationId,blockers})];
}

export function fromRetailObservation(observation:RetailObservation, evidence:AlternativeEvidence, options:Readonly<{rankFeatureKey?:'physicalRetailLevelProxy'|'diagnosticRank'; includeBreadth?:boolean}>={}):readonly CanonicalAlbumFeatureInput[] {
  if(evidence.origin!=='authorized-public-api') throw new Error('retail-feature-provenance-mismatch');
  const out:CanonicalAlbumFeatureInput[]=[]; const base=(key:AlbumFeatureKey,semantic:string,value:number|null,unit:string|null,movementType:'provider-reported-movement'|'snapshot-computed-rank-change'|null, blockers:string[]=[]):CanonicalAlbumFeatureInput=>make({contractVersion:CANONICAL_ALBUM_FEATURE_INPUT_CONTRACT_VERSION,featureKey:key,featureRole:roleFor(key),sourceClass:observation.syntheticFixture?'synthetic-fixture':'retailer-api',sourceEvidenceId:evidence.evidenceId,sourceObservationId:observation.observationId,provenance:{origin:evidence.origin,acquisitionProvider:evidence.acquisitionProvider,reportedProvider:evidence.reportedProvider,sourceUrl:evidence.sourceUrl,evidenceDigest:evidence.evidenceDigest,researchOnly:true},artistId:observation.fandexArtistId,artistIdentityState:observation.fandexArtistId?'resolved':'unresolved',releaseId:observation.fandexReleaseId,releaseIdentityState:observation.fandexReleaseId?'resolved':'unresolved',releaseFamilyId:observation.fandexReleaseFamilyId,editionId:null,skuId:observation.retailerProductId,semantic,value,unit,territory:null,format:null,providerPeriod:observation.providerPeriod,reportedPeriod:null,sourcePublishedAt:null,providerPublishedAt:observation.providerPublishedAt,observedAt:observation.observedAt,collectedAt:observation.collectedAt,revisionObservedAt:null,knowledgeMode:'current-research',periodType:observation.chartType==='realtime'?'instant/realtime':observation.chartType==='daily'?'day':observation.chartType==='monthly'?'month':'unknown',availabilityState:value===null?(observation.missingState==='not-ranked'?'not-ranked':'missing'):'available',qualityState:'unknown',eligibilityState:key==='diagnosticRank'||key==='diagnosticProviderIndex'?'diagnostic-only':'feature-resolver-candidate',proxyFallbackState:key==='diagnosticRank'||key==='diagnosticProviderIndex'?'diagnostic-only':'proxy-available',comparabilityState:observation.categoryResolutionState==='resolved'?'conditionally-comparable':'unknown',crossSourceDuplicationState:'unknown',retailerId:observation.retailerId,retailerProductId:observation.retailerProductId,categoryFamily:observation.categoryFamily,providerCategoryId:observation.providerCategoryId,categoryResolutionState:observation.categoryResolutionState,chartType:observation.chartType,movementType,aggregationScope:null,parentInputId:null,blockers});
  if(observation.semantic==='retail-rank') out.push(base(options.rankFeatureKey??'physicalRetailLevelProxy','rank',observation.rank,'rank',null));
  if(observation.movement!==null) out.push(base('physicalRetailMomentumEvidence','retail-rank',observation.movement,'rank','provider-reported-movement',['provider-reported-movement-not-snapshot-delta']));
  if(observation.semantic==='retail-provider-index') out.push(base('diagnosticProviderIndex','index',observation.providerIndex,'provider-index',null));
  if(options.includeBreadth) out.push(base('retailBreadthEvidence',observation.semantic,1,'observation-count',null,['breadth-insufficient-independent-retailers']));
  return out;
}

export function fromAlbumResearchClaim(claim:AlbumResearchClaim):readonly CanonicalAlbumFeatureInput[] {
  const map:Record<string,AlbumFeatureKey>={ 'first-week-sale':'reportedFirstWeekSales','cumulative-sale':'reportedCumulativeSales','rank':'diagnosticRank','index':'diagnosticProviderIndex','preorder':'preorderDiagnostic','shipment':'shipmentDiagnostic','period-sale':'providerNativePeriodSales','consumer-retail-sale':'providerNativePeriodSales','retailer-panel-sale':'providerNativePeriodSales' }; const key=map[claim.semantic]??'unknownAlbumEvidence'; const blockers:string[]=[...claim.blockers]; if(key==='providerNativePeriodSales') blockers.push('news-reported-not-direct-provider-period');
  const availability=claim.value===null?'unresolved':claim.unit===null?'unresolved':'available'; const role=roleFor(key); const sourceClass=sourceClassForOrigin(claim.origin); const eligibility=claim.shadowEligibility==='shadow-feature-eligible'?'shadow-candidate':claim.shadowEligibility==='normalized-research-ready'?'research-only':role==='diagnostic'?'diagnostic-only':'research-only';
  return [make({contractVersion:CANONICAL_ALBUM_FEATURE_INPUT_CONTRACT_VERSION,featureKey:key,featureRole:role,sourceClass,sourceEvidenceId:claim.sourceEvidenceId,sourceObservationId:null,provenance:{origin:claim.origin,acquisitionProvider:claim.acquisitionProvider,reportedProvider:claim.reportedProvider,sourceUrl:null,evidenceDigest:claim.evidenceDigest,researchOnly:true},artistId:claim.artistId,artistIdentityState:claim.artistIdentityState,releaseId:claim.releaseId,releaseIdentityState:claim.releaseIdentityState,releaseFamilyId:null,editionId:null,skuId:null,semantic:claim.semantic,value:claim.value,unit:claim.unit,territory:claim.territory,format:null,providerPeriod:claim.providerPeriod,reportedPeriod:claim.reportedPeriod,sourcePublishedAt:claim.sourcePublishedAt,providerPublishedAt:null,observedAt:claim.observedAt,collectedAt:claim.collectedAt,revisionObservedAt:claim.revisionObservedAt,knowledgeMode:claim.knowledgeMode,periodType:periodType(claim.providerPeriod??claim.reportedPeriod,claim.semantic),availabilityState:availability,qualityState:claim.quality.semanticClarity==='conflicting'?'conflicting':claim.semanticState==='clear'?'clear':'partial',eligibilityState:eligibility,proxyFallbackState:role==='diagnostic'?'diagnostic-only':role==='context'?'context-only':'blocked',comparabilityState:'unknown',crossSourceDuplicationState:'unknown',retailerId:null,retailerProductId:null,categoryFamily:null,providerCategoryId:null,categoryResolutionState:null,chartType:null,movementType:null,aggregationScope:null,parentInputId:null,blockers})];
}

export function classifyAlbumFeatureComparability(a:CanonicalAlbumFeatureInput,b:CanonicalAlbumFeatureInput):AlbumComparabilityState { if(a.featureKey!==b.featureKey||a.unit!==b.unit||a.periodType!==b.periodType) return 'not-comparable'; if(a.sourceClass!==b.sourceClass) return 'conditionally-comparable'; if(a.categoryResolutionState!=='resolved'||b.categoryResolutionState!=='resolved') return 'conditionally-comparable'; return 'comparable'; }
export type AlbumFeatureValidation = Readonly<{ valid:boolean; issues:readonly string[] }>;
export function validateAlbumFeatureInputSet(inputs:readonly CanonicalAlbumFeatureInput[]):AlbumFeatureValidation { const issues:string[]=[]; for(let i=0;i<inputs.length;i++) for(let j=i+1;j<inputs.length;j++){const a=inputs[i],b=inputs[j]; if(a.contributionIdentity.contributionIdentityId===b.contributionIdentity.contributionIdentityId) issues.push('duplicate-contribution-identity'); if(a.sourceClass==='direct-provider'&&b.sourceClass==='direct-provider'&&a.featureKey===b.featureKey&&a.providerPeriod===b.providerPeriod&&a.provenance.reportedProvider!==b.provenance.reportedProvider) issues.push('raw-provider-sum-forbidden'); if((a.featureRole==='absolute'&&b.featureRole==='proxy')||(a.featureRole==='proxy'&&b.featureRole==='absolute')) issues.push('absolute-proxy-not-additive'); if((a.semantic==='first-week-sale'&&b.semantic==='cumulative-sale')||(a.semantic==='cumulative-sale'&&b.semantic==='first-week-sale')) issues.push('first-week-cumulative-not-additive'); if(a.territory==='Global'&&b.territory==='Korea'&&a.featureKey===b.featureKey) issues.push('territory-overlap-review-required'); if(a.aggregationScope==='release-total'&&b.aggregationScope==='child-sku'&&a.parentInputId===b.parentInputId) issues.push('parent-child-double-count-forbidden'); } return {valid:issues.length===0,issues:[...new Set(issues)]}; }
export interface AlbumFeatureInputResolver { groupByFamily(inputs:readonly CanonicalAlbumFeatureInput[]):ReadonlyMap<string,readonly CanonicalAlbumFeatureInput[]>; validate(inputs:readonly CanonicalAlbumFeatureInput[]):AlbumFeatureValidation; }
