import type { DirectAlbumProviderDescriptor, DirectAlbumProviderCapabilities } from './directAlbumProvider';
import { CIRCLE_PROVIDER_DESCRIPTOR, HANTEO_PROVIDER_DESCRIPTOR } from './directAlbumProvider';
import { createDefaultOffOnboarding, type SourceAuthorizationDimensions, type SourceOnboardingRecord } from './onboarding';

export const DIRECT_PROVIDER_EVIDENCE_CONTRACT_VERSION='direct-provider-evidence-v1';
export type ProviderEvidencePacket=Readonly<{providerId:string;providerName:string;officialProductName:string|null;officialEvidenceUrls:readonly string[];acquisitionClass:'public-page-only'|'unknown'|'blocked';productActiveState:'active'|'deprecated'|'unknown';semanticEvidence:string;identityEvidence:string;temporalEvidence:string;revisionEvidence:string;requestEvidence:string;authorizationEvidence:string;capabilityUpgrades:Readonly<Record<string,string>>;certificationCapabilities?:Readonly<{supportsCumulativeCertification:boolean;supportsThresholdCertification:boolean}>;certificationThresholds?:Readonly<{platinum:Readonly<{relation:'>=';value:number}>;million:Readonly<{relation:'>=';value:number}>}>;unresolvedCapabilities:readonly string[];blockers:readonly string[]}>;
export const CIRCLE_PROVIDER_EVIDENCE:ProviderEvidencePacket=Object.freeze({providerId:'circle-chart',providerName:'Circle Chart',officialProductName:'Circle Chart Album Chart / Album certification',officialEvidenceUrls:['https://circlechart.kr/page_cert/chart.circle?serviceKey=default'],acquisitionClass:'public-page-only',productActiveState:'active',semanticEvidence:'Official certification thresholds provide cumulative certification context, not a documented unit feed.',identityEvidence:'Stable provider identity and edition/SKU contract unknown.',temporalEvidence:'Certification is cumulative; native period cadence unknown.',revisionEvidence:'Correction behavior unknown.',requestEvidence:'No official API/request schema verified.',authorizationEvidence:'Public visibility does not establish automated collection or storage permission.',capabilityUpgrades:{},certificationCapabilities:{supportsCumulativeCertification:true,supportsThresholdCertification:true},certificationThresholds:{platinum:{relation:'>=' as const,value:250000},million:{relation:'>=' as const,value:1000000}},unresolvedCapabilities:['supportsCumulativeSales','supportsNativePeriodSales','supportsFirstWeekSales','supportsHistoricalQueries','supportsRevisions','supportsArtistIdentity','supportsReleaseIdentity','supportsEditionIdentity','supportsSkuIdentity','supportsFormatIdentity','supportsTerritorySegmentation'],blockers:['no-verified-official-api-contract','storage-and-publication-rights-review-required']});
export const HANTEO_PROVIDER_EVIDENCE:ProviderEvidencePacket=Object.freeze({providerId:'hanteo-chart',providerName:'Hanteo Chart',officialProductName:'Hanteo Physical Album Chart / Album Daily and Weekly charts',officialEvidenceUrls:['https://www.hanteochart.com/en/about'],acquisitionClass:'public-page-only',productActiveState:'active',semanticEvidence:'Official chart context is aggregated physical-sales evidence, not a verified direct consumer-universe feed.',identityEvidence:'Stable provider identity/API contract unknown.',temporalEvidence:'Daily/weekly chart periods documented; first-week and historical query contract unknown.',revisionEvidence:'Correction behavior unknown.',requestEvidence:'API landing metadata exists; schema/auth/pagination/rate limits unknown.',authorizationEvidence:'Public chart access does not establish automated collection or redistribution permission.',capabilityUpgrades:{},unresolvedCapabilities:['supportsNativePeriodSales','supportsFirstWeekSales','supportsCumulativeSales','supportsHistoricalQueries','supportsRevisions','supportsArtistIdentity','supportsReleaseIdentity','supportsEditionIdentity','supportsSkuIdentity','supportsFormatIdentity','supportsTerritorySegmentation'],blockers:['api-schema-not-verified','storage-and-publication-rights-review-required']});
const unknownCapabilities=():DirectAlbumProviderCapabilities=>Object.freeze({supportsNativePeriodSales:{state:'unknown',evidenceIds:[]},supportsFirstWeekSales:{state:'unknown',evidenceIds:[]},supportsCumulativeSales:{state:'unknown',evidenceIds:[]},supportsHistoricalQueries:{state:'unknown',evidenceIds:[]},supportsRevisions:{state:'unknown',evidenceIds:[]},supportsArtistIdentity:{state:'unknown',evidenceIds:[]},supportsReleaseIdentity:{state:'unknown',evidenceIds:[]},supportsEditionIdentity:{state:'unknown',evidenceIds:[]},supportsSkuIdentity:{state:'unknown',evidenceIds:[]},supportsFormatIdentity:{state:'unknown',evidenceIds:[]},supportsTerritorySegmentation:{state:'unknown',evidenceIds:[]}});
export function buildEvidenceLinkedDescriptor(base:DirectAlbumProviderDescriptor,packet:ProviderEvidencePacket):DirectAlbumProviderDescriptor{const auth:SourceAuthorizationDimensions={acquisitionState:'review-required',automationState:'review-required',rawStorageState:'review-required',normalizedStorageState:'review-required',retentionState:'unknown',commercialUseState:'contract-required',derivedPublicationState:'review-required',rawRedistributionState:'blocked'};const onboarding:SourceOnboardingRecord=createDefaultOffOnboarding({sourceId:base.providerId,sourceName:base.providerName,stage:'official-docs-verified',technicalReadiness:'contract-ready',authorization:auth,evidenceIds:packet.officialEvidenceUrls,blockers:packet.blockers});return Object.freeze({...base,onboarding,capabilities:unknownCapabilities()});}
export const CIRCLE_EVIDENCE_DESCRIPTOR=buildEvidenceLinkedDescriptor(CIRCLE_PROVIDER_DESCRIPTOR,CIRCLE_PROVIDER_EVIDENCE);
export const HANTEO_EVIDENCE_DESCRIPTOR=buildEvidenceLinkedDescriptor(HANTEO_PROVIDER_DESCRIPTOR,HANTEO_PROVIDER_EVIDENCE);
export const DIRECT_PROVIDER_EVIDENCE_PACKETS=Object.freeze({circle:CIRCLE_PROVIDER_EVIDENCE,hanteo:HANTEO_PROVIDER_EVIDENCE});
