import { sha256Canonical } from '../shared/canonicalDigest';
import type { CanonicalAlbumFeatureInput } from './canonicalAlbumFeatureInput';

export const IDENTITY_CONTRACT_VERSION = 'album-identity-foundation-v1';
export type IdentityResolutionState = 'unresolved'|'candidate'|'ambiguous'|'review-required'|'resolved'|'conflicting'|'rejected';
export type IdentityReviewState = 'unreviewed'|'machine-candidate'|'human-reviewed'|'provider-verified'|'conflicting'|'rejected';
export type ArtistType = 'solo'|'group'|'member'|'subunit'|'duo'|'band'|'project'|'collaboration'|'virtual'|'unknown';
export type ReleaseType = 'single'|'single-album'|'ep'|'mini-album'|'album'|'full-album'|'repackage'|'compilation'|'live-album'|'ost'|'soundtrack'|'unknown';
export type FormatCandidate = 'physical-cd'|'vinyl'|'cassette'|'platform-album'|'nfc'|'qr'|'digital'|'bundle'|'unknown';
export type ProductRelationship = 'same-release'|'same-family'|'edition-child'|'sku-child'|'bundle'|'set'|'platform-album'|'unknown';
export type IdentityQualityState = 'clear'|'partial'|'unknown'|'conflicting';
export type IdentityBlocker = 'artist-unresolved'|'artist-ambiguous'|'release-unresolved'|'release-ambiguous'|'release-family-unresolved'|'edition-unresolved'|'sku-relation-unknown'|'format-unknown'|'territory-unknown'|'provider-id-missing'|'name-collision'|'review-required'|'conflicting-mapping';

export type FandexArtistIdentity = Readonly<{ fandexArtistId:string|null; canonicalName:string|null; normalizedName:string|null; aliases:readonly string[]; artistType:ArtistType; groupId:string|null; memberOf:readonly string[]; subunitOf:string|null; collaborationParticipants:readonly string[]; providerMappings:readonly IdentityMappingRecord[]; reviewState:IdentityReviewState; resolutionState:IdentityResolutionState }>;
export type ExternalArtistIdentity = Readonly<{ sourceId:string; providerArtistId:string|null; rawArtistText:string|null; normalizedArtistText:string|null; locale:string|null; aliases:readonly string[]; candidateFandexArtistIds:readonly string[]; resolutionState:IdentityResolutionState; reviewState:IdentityReviewState }>;
export type ReleaseFamilyIdentity = Readonly<{ fandexReleaseFamilyId:string|null; canonicalTitle:string|null; artistIds:readonly string[]; reviewState:IdentityReviewState; resolutionState:IdentityResolutionState }>;
export type FandexReleaseIdentity = Readonly<{ fandexReleaseId:string|null; fandexReleaseFamilyId:string|null; canonicalTitle:string|null; artistIds:readonly string[]; releaseDate:string|null; releaseType:ReleaseType; label:string|null; territory:string|null; formatFamily:FormatCandidate|'unknown'; reviewState:IdentityReviewState; resolutionState:IdentityResolutionState }>;
export type EditionIdentity = Readonly<{ providerEditionId:string|null; editionText:string|null; candidateCanonicalEditionId:string|null; resolutionState:IdentityResolutionState; reviewState:IdentityReviewState }>;
export type RetailProductIdentity = Readonly<{ retailerId:string; retailerProductId:string|null; rawTitle:string|null; rawArtistText:string|null; publisher:string|null; publishDate:string|null; isbn10:string|null; isbn13:string|null; goodsType:string|null; goodsSortNm:string|null; candidateReleaseIds:readonly string[]; candidateReleaseFamilyIds:readonly string[]; candidateEditionIds:readonly string[]; candidateSkuScope:ProductRelationship|'unknown'; resolutionState:IdentityResolutionState; reviewState:IdentityReviewState }>;
export type IdentityMappingRecord = Readonly<{ mappingId:string; sourceType:string; sourceProvider:string|null; sourceEntityId:string|null; canonicalEntityType:'artist'|'release'|'release-family'|'edition'|'retail-product'; candidateCanonicalId:string|null; resolutionState:IdentityResolutionState; reviewState:IdentityReviewState; evidenceRefs:readonly string[]; supersedesMappingId:string|null; contractVersion:typeof IDENTITY_CONTRACT_VERSION }>;

export function normalizeIdentityText(value:string|null):string|null { if(value===null)return null; return value.normalize('NFKC').trim().replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[()\[\]{}]/g,' ').replace(/\s+/g,' ').toLocaleLowerCase(); }
export function isResolved(state:IdentityResolutionState, id:string|null, review:IdentityReviewState):boolean { return state==='resolved' && id!==null && (review==='human-reviewed'||review==='provider-verified'); }
export function createArtistCandidate(input:Readonly<{sourceId:string;providerArtistId?:string|null;rawArtistText:string|null;candidateFandexArtistIds?:readonly string[]}>):ExternalArtistIdentity { return Object.freeze({sourceId:input.sourceId,providerArtistId:input.providerArtistId??null,rawArtistText:input.rawArtistText,normalizedArtistText:normalizeIdentityText(input.rawArtistText),locale:null,aliases:[],candidateFandexArtistIds:input.candidateFandexArtistIds??[],resolutionState:input.candidateFandexArtistIds?.length===1?'candidate':'unresolved',reviewState:input.candidateFandexArtistIds?.length?'machine-candidate':'unreviewed'}); }
export function buildIdentityMappingId(input:Omit<IdentityMappingRecord,'mappingId'|'contractVersion'>):string { return sha256Canonical({contractVersion:IDENTITY_CONTRACT_VERSION,...input}); }
export type IdentityReferenceCatalog = Readonly<{ findArtistByCanonicalId?(id:string):FandexArtistIdentity|null; findArtistCandidatesByProviderId?(provider:string,id:string):readonly string[]; findArtistCandidatesByAlias?(normalized:string):readonly string[]; findReleaseByCanonicalId?(id:string):FandexReleaseIdentity|null; findReleaseCandidatesByProviderId?(provider:string,id:string):readonly string[]; findRetailProductMapping?(retailer:string,id:string):readonly string[] }>;
export type CandidateResolution = Readonly<{ candidateIds:readonly string[]; resolutionState:IdentityResolutionState; reviewState:IdentityReviewState; blockers:readonly IdentityBlocker[] }>;
export function resolveRetailProductCandidates(product:RetailProductIdentity,catalog:IdentityReferenceCatalog):CandidateResolution { const ids=catalog.findRetailProductMapping?.(product.retailerId,product.retailerProductId??'')??product.candidateReleaseIds; if(ids.length===1)return {candidateIds:ids,resolutionState:'candidate',reviewState:'machine-candidate',blockers:['review-required']}; if(ids.length>1)return {candidateIds:ids,resolutionState:'ambiguous',reviewState:'unreviewed',blockers:['release-ambiguous','review-required']}; return {candidateIds:[],resolutionState:'unresolved',reviewState:'unreviewed',blockers:['release-unresolved']}; }
export function validateArtistScope(type:ArtistType, expected:ArtistType):readonly IdentityBlocker[] { if(type!==expected)return ['artist-ambiguous','review-required']; return []; }
export function enrichAlbumFeatureInputIdentity(input:CanonicalAlbumFeatureInput, identity:Readonly<{artistId?:string|null;artistState?:IdentityResolutionState;releaseId?:string|null;releaseState?:IdentityResolutionState;releaseFamilyId?:string|null;editionId?:string|null;skuId?:string|null}>):CanonicalAlbumFeatureInput { const blockers=[...input.blockers]; const artistId=identity.artistId??input.artistId; const releaseId=identity.releaseId??input.releaseId; const artistState=identity.artistState??input.artistIdentityState as IdentityResolutionState; const releaseState=identity.releaseState??input.releaseIdentityState as IdentityResolutionState; if(!isResolved(artistState,artistId,'human-reviewed')&&!isResolved(artistState,artistId,'provider-verified')) blockers.push('artist-unresolved'); if(!isResolved(releaseState,releaseId,'human-reviewed')&&!isResolved(releaseState,releaseId,'provider-verified')) blockers.push('release-unresolved'); const blocked=blockers.length>0; return Object.freeze({...input,artistId,artistIdentityState:artistState,releaseId,releaseIdentityState:releaseState,releaseFamilyId:identity.releaseFamilyId??input.releaseFamilyId,editionId:identity.editionId??input.editionId,skuId:identity.skuId??input.skuId,eligibilityState:blocked?'blocked':input.eligibilityState,blockers:[...new Set(blockers)]}); }
