import { sha256Canonical } from '../shared/canonicalDigest';
import type { AlternativeEvidence } from './contracts';
import type { CanonicalAlbumFeatureInput } from './canonicalAlbumFeatureInput';
import type { AlbumTemporalSnapshot } from './albumTemporalSnapshot';
import type { IdentityMappingRecord } from './identityFoundation';
import type { AlbumMethodologyEvaluation } from './albumSyntheticValidation';
export const PERSISTENCE_CONTRACT_VERSION='album-persistence-contract-v1' as const;
export type PersistenceScope='synthetic-validation'|'research'|'shadow'|'production';
export type PersistenceAction='append'|'duplicate-noop'|'conflict-preserve'|'revision-append'|'blocked'|'invalid';
export type PersistenceEligibility='eligible'|'conditionally-eligible'|'blocked'|'research-only'|'synthetic-only'|'unknown';
export type PersistenceRecordState='original'|'revised'|'conflicting'|'rejected';
export type AuthorizationSnapshot=Readonly<Record<'acquisition'|'automation'|'rawStorage'|'normalizedStorage'|'retention'|'commercialUse'|'derivedPublication'|'rawRedistribution',string>>;
export type PersistenceRecordEnvelope<T>=Readonly<{recordId:string;recordType:string;recordVersion:string;persistenceScope:PersistenceScope;payloadDigest:string;sourceEntityId:string|null;sourceRecordId:string|null;createdFromRecordIds:readonly string[];contributionIdentityId:string|null;knowledgeMode:string;effectivePeriod:string|null;observedAt:string|null;collectedAt:string|null;revisionObservedAt:string|null;methodologyVersion:string|null;syntheticOnly:boolean;authorizationSnapshot:AuthorizationSnapshot;supersedesRecordId:string|null;recordState:PersistenceRecordState;payload:T}>;
export type PersistenceRecord=PersistenceRecordEnvelope<unknown>;
export type PersistenceDecisionContext=Readonly<{scope:PersistenceScope;authorization:AuthorizationSnapshot;technicalEligibility:PersistenceEligibility;syntheticOnly:boolean}>;
export type PersistenceAppendPlan=Readonly<{contractVersion:typeof PERSISTENCE_CONTRACT_VERSION;scope:PersistenceScope;atomicity:'per-record-results';candidateCount:number;appendCount:number;duplicateNoopCount:number;conflictCount:number;revisionCount:number;blockedCount:number;invalidCount:number;actions:{recordId:string;action:PersistenceAction;reason:string|null}[];planDigest:string;effects:Readonly<{databaseReads:0;databaseWrites:0;externalCalls:0}>}>;
export const defaultAuthorizationSnapshot=():AuthorizationSnapshot=>({acquisition:'unknown',automation:'unknown',rawStorage:'unknown',normalizedStorage:'unknown',retention:'unknown',commercialUse:'unknown',derivedPublication:'unknown',rawRedistribution:'unknown'});
export function buildPersistenceRecordId(recordType:string,payloadDigest:string,scope:PersistenceScope){return sha256Canonical({contractVersion:PERSISTENCE_CONTRACT_VERSION,recordType,payloadDigest,scope});}
export function envelopeRecord<T>(input:Readonly<{recordType:string;recordVersion:string;persistenceScope:PersistenceScope;payload:T;sourceEntityId?:string|null;sourceRecordId?:string|null;createdFromRecordIds?:readonly string[];contributionIdentityId?:string|null;knowledgeMode?:string;effectivePeriod?:string|null;observedAt?:string|null;collectedAt?:string|null;revisionObservedAt?:string|null;methodologyVersion?:string|null;syntheticOnly:boolean;authorizationSnapshot?:AuthorizationSnapshot;supersedesRecordId?:string|null;recordState?:PersistenceRecordState}>):PersistenceRecordEnvelope<T>{const payloadDigest=sha256Canonical(input.payload);return Object.freeze({recordId:buildPersistenceRecordId(input.recordType,payloadDigest,input.persistenceScope),recordType:input.recordType,recordVersion:input.recordVersion,persistenceScope:input.persistenceScope,payloadDigest,sourceEntityId:input.sourceEntityId??null,sourceRecordId:input.sourceRecordId??null,createdFromRecordIds:Object.freeze([...(input.createdFromRecordIds??[])]),contributionIdentityId:input.contributionIdentityId??null,knowledgeMode:input.knowledgeMode??'unknown',effectivePeriod:input.effectivePeriod??null,observedAt:input.observedAt??null,collectedAt:input.collectedAt??null,revisionObservedAt:input.revisionObservedAt??null,methodologyVersion:input.methodologyVersion??null,syntheticOnly:input.syntheticOnly,authorizationSnapshot:input.authorizationSnapshot??defaultAuthorizationSnapshot(),supersedesRecordId:input.supersedesRecordId??null,recordState:input.recordState??'original',payload:input.payload});}
export type PersistenceRecordPayloads=Readonly<{evidence:AlternativeEvidence;featureInput:CanonicalAlbumFeatureInput;identityMapping:IdentityMappingRecord;temporalSnapshot:AlbumTemporalSnapshot;methodologyEvaluation:AlbumMethodologyEvaluation;methodologyDecision:unknown;validationReport:unknown}>;
export function persistenceEligibility(c:PersistenceDecisionContext):PersistenceEligibility{if(c.scope==='production')return'blocked';if(c.syntheticOnly)return c.scope==='synthetic-validation'?'synthetic-only':'blocked';if(c.scope==='research')return'research-only';return c.technicalEligibility==='eligible'&&c.authorization.rawStorage==='allowed'?'eligible':'blocked';}
export function planPersistenceAppend(existing:readonly PersistenceRecord[],candidates:readonly PersistenceRecord[],context:PersistenceDecisionContext):PersistenceAppendPlan{const ids=new Set(existing.map(x=>x.recordId)),actions:PersistenceAppendPlan['actions']=[];let append=0,duplicateNoop=0,conflict=0,revision=0,blocked=0,invalid=0;const eligible=persistenceEligibility(context);for(const r of candidates){let action:PersistenceAction='append',reason:string|null=null;if(r.persistenceScope!==context.scope||eligible==='blocked'){action='blocked';reason='persistence-scope-or-authorization-blocked';blocked++;}else if(!r.syntheticOnly&&context.scope==='synthetic-validation'){action='invalid';reason='live-record-in-synthetic-scope';invalid++;}else if(ids.has(r.recordId)){action='duplicate-noop';duplicateNoop++;}else if(r.supersedesRecordId){action='revision-append';revision++;append++;}else if(existing.some(e=>e.sourceRecordId===r.sourceRecordId&&e.payloadDigest!==r.payloadDigest)){action='conflict-preserve';conflict++;append++;}else append++;actions.push({recordId:r.recordId,action,reason});}return {contractVersion:PERSISTENCE_CONTRACT_VERSION,scope:context.scope,atomicity:'per-record-results',candidateCount:candidates.length,appendCount:append,duplicateNoopCount:duplicateNoop,conflictCount:conflict,revisionCount:revision,blockedCount:blocked,invalidCount:invalid,actions,planDigest:sha256Canonical(actions),effects:{databaseReads:0,databaseWrites:0,externalCalls:0}};}
export function queryAsKnownAt(records:readonly PersistenceRecord[],cutoff:string){return records.filter(r=>(r.collectedAt??'')<=cutoff&&(r.revisionObservedAt===null||r.revisionObservedAt<=cutoff));}
export function queryCurrentResearch(records:readonly PersistenceRecord[]){const heads=records.filter(r=>!records.some(o=>o.supersedesRecordId===r.recordId));const scopes=new Set(heads.map(r=>`${r.sourceRecordId}|${r.effectivePeriod}|${r.payloadDigest}`));return {records:heads,state:heads.length===0?'empty':scopes.size>1?'conflicting':'resolved'} as const;}
export interface AlbumResearchPersistenceStore{findByRecordId(recordId:string):Promise<PersistenceRecord|null>;queryAsKnownAt(cutoff:string):Promise<readonly PersistenceRecord[]>;queryCurrentResearch():Promise<ReturnType<typeof queryCurrentResearch>>;planAppend(records:readonly PersistenceRecord[],context:PersistenceDecisionContext):Promise<PersistenceAppendPlan>}
export type AlbumShadowPersistenceStore=AlbumResearchPersistenceStore;
