import { sha256Canonical } from '../shared/canonicalDigest';
import { ALTERNATIVE_EVIDENCE_CONTRACT_VERSION, type AlternativeEvidence } from './contracts';
import {
  bridgeRetailObservation, buildRetailObservation, RETAIL_OBSERVATION_CONTRACT_VERSION,
  type RetailChartType, type RetailFeatureEvidence, type RetailObservation,
  type RetailProviderDescriptor, type RetailProductIdentity, validateRetailObservation,
  YES24_RETAIL_DESCRIPTOR,
} from './retailObservation';

export const YES24_RETAIL_ADAPTER_CONTRACT_VERSION = 'yes24-retail-adapter-v1' as const;
export type Yes24RetailRequestType = 'bestseller-realtime'|'bestseller-daily'|'bestseller-monthly';
export type Yes24CategoryResolutionState = 'resolved'|'unresolved'|'unknown';
export type Yes24RetailRequestPlan = Readonly<{contractVersion:typeof YES24_RETAIL_ADAPTER_CONTRACT_VERSION;retailerId:'yes24';requestType:Yes24RetailRequestType;categoryFamily:'music';providerCategoryId:string|null;categoryResolutionState:Yes24CategoryResolutionState;date:string|null;page:number|null;pageSize:number|null;detail:'N'|'Y';endpoint:null;networkAllowed:false;rateLimitAccountingScope:'unknown'|'review-required';planDigest:string}>;
export function buildYes24RetailRequestPlan(input:Readonly<{requestType:Yes24RetailRequestType;providerCategoryId?:string|null;categoryResolutionState?:Yes24CategoryResolutionState;date?:string|null;page?:number|null;pageSize?:number|null;detail?:'N'|'Y'}>):Yes24RetailRequestPlan {
  const date=input.date??null; if(date!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error('yes24_date_format_invalid');
  const page=input.page??null,pageSize=input.pageSize??null;
  if(page!==null&&(!Number.isInteger(page)||page<1)) throw new Error('yes24_page_invalid');
  if(pageSize!==null&&(!Number.isInteger(pageSize)||pageSize<1||pageSize>100)) throw new Error('yes24_page_size_invalid');
  if(input.requestType==='bestseller-realtime'&&(page!==null||pageSize!==null)) throw new Error('yes24_realtime_pagination_not_documented');
  const shape={contractVersion:YES24_RETAIL_ADAPTER_CONTRACT_VERSION,retailerId:'yes24' as const,requestType:input.requestType,categoryFamily:'music' as const,providerCategoryId:input.providerCategoryId??null,categoryResolutionState:input.categoryResolutionState??'unresolved' as Yes24CategoryResolutionState,date,page,pageSize,detail:input.detail??'N' as const,endpoint:null,networkAllowed:false as const,rateLimitAccountingScope:'unknown' as const};
  return Object.freeze({...shape,planDigest:sha256Canonical(shape)});
}
export type Yes24RetailResponseItem = Readonly<{sortOrder?:number|null;itemId:number;title:string;author?:string|null;goodsType?:string|null;goodsSortNm?:string|null;publisher?:string|null;isbn10?:string|null;isbn13?:string|null;publishDate?:string|null;itemStatus?:string|null;link?:string|null;upDown?:number|null;salePoint?:number|null}>;
export type Yes24RetailDecodedResponse = Readonly<{meta:{pubDate:string;version:string;apiTitle?:string|null;apiLink?:string|null;logoUrl?:string|null;query?:string|null};items:readonly Yes24RetailResponseItem[];currentPage:number|null;pageSize:number|null;totalCount:number|null}>;
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const optString=(r:Record<string,unknown>,k:string)=>{const v=r[k];if(v===undefined)return undefined;if(v!==null&&typeof v!=='string')throw new Error(`yes24_${k}_type_invalid`);return v as string|null};
const optInt=(r:Record<string,unknown>,k:string,nonNegative=false)=>{const v=r[k];if(v===undefined)return undefined;if(v!==null&&(!Number.isInteger(v)||!Number.isFinite(v)))throw new Error(`yes24_${k}_type_invalid`);if(nonNegative&&typeof v==='number'&&v<0)throw new Error(`yes24_${k}_negative`);return v as number|null};
export function decodeYes24RetailResponse(input:unknown):Yes24RetailDecodedResponse {
  if(!record(input)||input.success!==true||!record(input.data)||!record(input.data.meta)||!Array.isArray(input.data.items)) throw new Error('yes24_response_shape_invalid');
  const meta=input.data.meta; if(typeof meta.pubDate!=='string'||Number.isNaN(Date.parse(meta.pubDate))) throw new Error('yes24_pub_date_invalid'); if(typeof meta.version!=='string'||!meta.version.trim()) throw new Error('yes24_version_invalid');
  const items=input.data.items.map((raw,index)=>{if(!record(raw))throw new Error(`yes24_item_${index}_invalid`);const id=raw.itemId;if(typeof id!=='number'||!Number.isInteger(id)||id<=0)throw new Error(`yes24_item_${index}_item_id_invalid`);if(typeof raw.title!=='string'||!raw.title.trim())throw new Error(`yes24_item_${index}_title_invalid`);const sortOrder=optInt(raw,'sortOrder');if(sortOrder!==undefined&&sortOrder!==null&&sortOrder<=0)throw new Error(`yes24_item_${index}_rank_invalid`);return Object.freeze({sortOrder,itemId:id,title:raw.title,author:optString(raw,'author'),goodsType:optString(raw,'goodsType'),goodsSortNm:optString(raw,'goodsSortNm'),publisher:optString(raw,'publisher'),isbn10:optString(raw,'isbn10'),isbn13:optString(raw,'isbn13'),publishDate:optString(raw,'publishDate'),itemStatus:optString(raw,'itemStatus'),link:optString(raw,'link'),upDown:optInt(raw,'upDown'),salePoint:optInt(raw,'salePoint',true)});});
  return Object.freeze({meta:Object.freeze({pubDate:meta.pubDate as string,version:meta.version as string,apiTitle:optString(meta,'apiTitle'),apiLink:optString(meta,'apiLink'),logoUrl:optString(meta,'logoUrl'),query:optString(meta,'query')}),items:Object.freeze(items),currentPage:optInt(input.data,'currentPage')??null,pageSize:optInt(input.data,'pageSize',true)??null,totalCount:optInt(input.data,'totalCount',true)??null});
}
const chart=(t:Yes24RetailRequestType):RetailChartType=>t==='bestseller-realtime'?'realtime':t==='bestseller-daily'?'daily':'monthly';
export function normalizeYes24RetailResponse(response:Yes24RetailDecodedResponse,plan:Yes24RetailRequestPlan,input:Readonly<{observedAt:string;collectedAt:string;syntheticFixture?:boolean}>):readonly RetailObservation[]{const out:RetailObservation[]=[];const period=plan.requestType==='bestseller-realtime'?null:plan.date;for(const item of response.items){const productIdentity:RetailProductIdentity={retailerId:'yes24',retailerProductId:String(item.itemId),identityState:'candidate'};const base={contractVersion:RETAIL_OBSERVATION_CONTRACT_VERSION as typeof RETAIL_OBSERVATION_CONTRACT_VERSION,retailerId:'yes24' as const,retailerProductId:String(item.itemId),productIdentity,fandexArtistId:null,fandexReleaseId:null,fandexReleaseFamilyId:null,retailerArtistText:item.author??null,retailerTitle:item.title,categoryFamily:'music' as const,providerCategoryId:plan.providerCategoryId,categoryResolutionState:plan.categoryResolutionState,chartType:chart(plan.requestType),movement:item.upDown??null,providerPeriod:period,providerPeriodState:period===null?'unresolved' as const:'resolved' as const,providerPublishedAt:response.meta.pubDate,observedAt:input.observedAt,collectedAt:input.collectedAt,sourceType:input.syntheticFixture?'synthetic-fixture' as const:'yes24-official-api' as const,missingState:'observed' as const,syntheticFixture:input.syntheticFixture??false};if(item.sortOrder!==undefined&&item.sortOrder!==null)out.push(buildRetailObservation({...base,semantic:'retail-rank',rank:item.sortOrder,providerIndex:null,providerIndexName:null}));if(item.salePoint!==undefined&&item.salePoint!==null)out.push(buildRetailObservation({...base,semantic:'retail-provider-index',rank:null,providerIndex:item.salePoint,providerIndexName:'YES24 salePoint'}));if((item.sortOrder==null)&&(item.salePoint==null))out.push(buildRetailObservation({...base,semantic:'retail-product-observation',rank:null,providerIndex:null,providerIndexName:null,missingState:'not-ranked'}));}return Object.freeze(out);}
export function buildYes24ObservationEvidence(observation:RetailObservation):AlternativeEvidence{return Object.freeze({evidenceId:`yes24:${observation.observationId}`,origin:'authorized-public-api',sourceId:'yes24',sourceUrl:null,acquisitionProvider:'yes24-open-api',reportedProvider:'yes24',observedAt:observation.observedAt,collectedAt:observation.collectedAt,sourcePublishedAt:observation.providerPublishedAt,evidenceDigest:observation.evidenceDigest,researchOnly:true,contractVersion:ALTERNATIVE_EVIDENCE_CONTRACT_VERSION});}
export function bridgeYes24Observation(observation:RetailObservation):RetailFeatureEvidence{return bridgeRetailObservation(observation,buildYes24ObservationEvidence(observation));}
export class Yes24LiveGateError extends Error{readonly code='yes24-live-calls-disabled' as const;constructor(){super('yes24_live_calls_disabled');this.name='Yes24LiveGateError';}}
export interface RetailTransport{execute(plan:Yes24RetailRequestPlan):Promise<unknown>}
export type Yes24RetailAdapter=Readonly<{descriptor:RetailProviderDescriptor;buildRequestPlan:typeof buildYes24RetailRequestPlan;decodeResponse:typeof decodeYes24RetailResponse;normalizeResponse:typeof normalizeYes24RetailResponse;bridgeObservation:typeof bridgeYes24Observation;executeLive:(transport:RetailTransport,plan:Yes24RetailRequestPlan)=>Promise<never>}>;
export const YES24_RETAIL_ADAPTER:Yes24RetailAdapter=Object.freeze({descriptor:YES24_RETAIL_DESCRIPTOR,buildRequestPlan:buildYes24RetailRequestPlan,decodeResponse:decodeYes24RetailResponse,normalizeResponse:normalizeYes24RetailResponse,bridgeObservation:bridgeYes24Observation,executeLive:async(transport,plan):Promise<never>=>{void transport;void plan;throw new Yes24LiveGateError();}});
export function validateYes24NormalizedObservations(observations:readonly RetailObservation[]){const issues=observations.flatMap(o=>validateRetailObservation(o).issues);return Object.freeze({valid:issues.length===0,issues:Object.freeze([...new Set(issues)].sort())});}
