from datetime import datetime
from pathlib import Path


VERSION = "create_fandex_v71_runbook_v1"

RUNBOOK = Path("FANDEX_V7_1_RUNBOOK.txt")
SUMMARY = Path("FANDEX_V7_1_OPERATING_SUMMARY.txt")


def main():
    now = datetime.now().isoformat(timespec="seconds")

    runbook_lines = []
    runbook_lines.append("FANDEX v7.1 Python-only Runbook")
    runbook_lines.append("=" * 70)
    runbook_lines.append(f"createdAt: {now}")
    runbook_lines.append(f"version: {VERSION}")
    runbook_lines.append("")
    runbook_lines.append("1. 현재 안정화 상태")
    runbook_lines.append("-" * 70)
    runbook_lines.append("상태명: FANDEX Python-only v7.1 stale decay stable")
    runbook_lines.append("복구 백업: backup\\20260722_222818")
    runbook_lines.append("백업 파일 수: 136")
    runbook_lines.append("검증 상태: fandex_verify_backup_v1.py 통과")
    runbook_lines.append("웹사이트 public/data: 미접촉")
    runbook_lines.append("")
    runbook_lines.append("2. 현재 공식 ranking")
    runbook_lines.append("-" * 70)
    runbook_lines.append("1위 에이티즈 | FANDEX 474.86 | 네이버 318.77 | YouTube 50.34 | 음원 105.75")
    runbook_lines.append("2위 아이유 | FANDEX 473.26 | 네이버 399.65 | YouTube 49.61 | 음원 24.0")
    runbook_lines.append("3위 에스파 | FANDEX 409.11 | 네이버 279.11 | YouTube 78.7 | 음원 51.3")
    runbook_lines.append("4위 보이넥스트도어 | FANDEX 346.95 | 네이버 302.34 | YouTube 35.01 | 음원 9.6")
    runbook_lines.append("")
    runbook_lines.append("3. v7.1 핵심 구조")
    runbook_lines.append("-" * 70)
    runbook_lines.append("FANDEX master v7 = Naver v3 latest + YouTube v3 latest + Music chart latest")
    runbook_lines.append("Music chart latest는 stale decay 적용 후 master에 반영")
    runbook_lines.append("")
    runbook_lines.append("daily runner 순서:")
    runbook_lines.append("1) Bugs chart 자동 수집")
    runbook_lines.append("2) Bugs 수집 결과 seed 반영")
    runbook_lines.append("3) YouTube v3 점수 생성")
    runbook_lines.append("4) Music chart v1 원점수 생성")
    runbook_lines.append("5) Music chart seed 신선도 감사")
    runbook_lines.append("6) Music chart stale decay 공식 반영")
    runbook_lines.append("7) FANDEX master v7 생성")
    runbook_lines.append("8) Python status report 생성")
    runbook_lines.append("")
    runbook_lines.append("4. stale decay 정책")
    runbook_lines.append("-" * 70)
    runbook_lines.append("auto_collected row: 100% 반영")
    runbook_lines.append("manual_web_checked 0~3일: 100% 반영")
    runbook_lines.append("manual_web_checked 4~7일: 70% 반영")
    runbook_lines.append("manual_web_checked 8~14일: 40% 반영")
    runbook_lines.append("manual_web_checked 15~30일: 20% 반영")
    runbook_lines.append("manual_web_checked 30일 초과: 0점")
    runbook_lines.append("")
    runbook_lines.append("목적:")
    runbook_lines.append("- 오래된 수동 차트 seed가 공식 점수에 과도하게 남는 문제 방지")
    runbook_lines.append("- 단, 차트 수집 실패/MISS 때문에 점수가 갑자기 0점으로 날아가는 문제 완충")
    runbook_lines.append("")
    runbook_lines.append("5. 평소 일일 운영")
    runbook_lines.append("-" * 70)
    runbook_lines.append("cd %USERPROFILE%\\Desktop\\naver_data_collector")
    runbook_lines.append("run_fandex_daily_python_only.bat")
    runbook_lines.append("")
    runbook_lines.append("6. Python 내부 전체 갱신")
    runbook_lines.append("-" * 70)
    runbook_lines.append("cd %USERPROFILE%\\Desktop\\naver_data_collector")
    runbook_lines.append("py fandex_daily_python_only_v2.py")
    runbook_lines.append("")
    runbook_lines.append("7. YouTube API 재수집 포함")
    runbook_lines.append("-" * 70)
    runbook_lines.append("cd %USERPROFILE%\\Desktop\\naver_data_collector")
    runbook_lines.append("set YOUTUBE_API_KEY=실제_API_KEY")
    runbook_lines.append("py fandex_daily_python_only_v2.py --refresh-youtube")
    runbook_lines.append("")
    runbook_lines.append("주의: API key는 채팅이나 문서에 붙이지 말 것.")
    runbook_lines.append("")
    runbook_lines.append("8. Bugs 갱신 없이 실행")
    runbook_lines.append("-" * 70)
    runbook_lines.append("cd %USERPROFILE%\\Desktop\\naver_data_collector")
    runbook_lines.append("py fandex_daily_python_only_v2.py --skip-bugs")
    runbook_lines.append("")
    runbook_lines.append("9. 상태 확인")
    runbook_lines.append("-" * 70)
    runbook_lines.append("py fandex_python_status_report_v1.py")
    runbook_lines.append("powershell -NoProfile -Command \"Get-Content .\\fandex_python_status_report_latest.txt -Encoding UTF8\"")
    runbook_lines.append("")
    runbook_lines.append("10. Health check")
    runbook_lines.append("-" * 70)
    runbook_lines.append("py fandex_python_health_check_v1.py")
    runbook_lines.append("")
    runbook_lines.append("정상 기준:")
    runbook_lines.append("OK: Python-only v7.1 stale decay 운영 상태 정상")
    runbook_lines.append("")
    runbook_lines.append("11. 백업")
    runbook_lines.append("-" * 70)
    runbook_lines.append("py fandex_backup_core_files_v1.py --apply")
    runbook_lines.append("py fandex_verify_backup_v1.py")
    runbook_lines.append("")
    runbook_lines.append("정상 기준:")
    runbook_lines.append("OK: 백업 manifest와 실제 파일이 일치합니다.")
    runbook_lines.append("")
    runbook_lines.append("12. 복구")
    runbook_lines.append("-" * 70)
    runbook_lines.append("복구 dry-run:")
    runbook_lines.append("py fandex_restore_core_files_v1.py backup\\20260722_222818")
    runbook_lines.append("")
    runbook_lines.append("실제 복구:")
    runbook_lines.append("py fandex_restore_core_files_v1.py backup\\20260722_222818 --apply")
    runbook_lines.append("")
    runbook_lines.append("13. 실행 금지 명령")
    runbook_lines.append("-" * 70)
    runbook_lines.append("Codex 작업 중에는 아래 명령 실행 금지:")
    runbook_lines.append("py fandex_export_to_site_v1.py")
    runbook_lines.append("py fandex_publish_all_v5.py")
    runbook_lines.append("py fandex_publish_all_v5.py --refresh-youtube")
    runbook_lines.append("")
    runbook_lines.append("14. 다음 개발 후보")
    runbook_lines.append("-" * 70)
    runbook_lines.append("A. v7.1 문서와 기존 FANDEX_PYTHON_ONLY_RUNBOOK.txt 병합")
    runbook_lines.append("B. artist 4명에서 10명으로 확장")
    runbook_lines.append("C. Melon/Genie fallback collector 매칭 개선")
    runbook_lines.append("D. Last.fm / iTunes / MusicBrainz 데이터를 점수 후보로 승격")
    runbook_lines.append("E. Codex 웹사이트 public/data 반영 단계로 이동")

    summary_lines = []
    summary_lines.append("FANDEX v7.1 Operating Summary")
    summary_lines.append("=" * 70)
    summary_lines.append(f"createdAt: {now}")
    summary_lines.append("")
    summary_lines.append("현재 운영 명령")
    summary_lines.append("-" * 70)
    summary_lines.append("run_fandex_daily_python_only.bat")
    summary_lines.append("")
    summary_lines.append("현재 공식 순위")
    summary_lines.append("-" * 70)
    summary_lines.append("1위 에이티즈 474.86")
    summary_lines.append("2위 아이유 473.26")
    summary_lines.append("3위 에스파 409.11")
    summary_lines.append("4위 보이넥스트도어 346.95")
    summary_lines.append("")
    summary_lines.append("핵심 정책")
    summary_lines.append("-" * 70)
    summary_lines.append("오래된 manual_web_checked 음원 seed는 stale decay 적용")
    summary_lines.append("8~14일 old row는 40%만 반영")
    summary_lines.append("")
    summary_lines.append("복구 포인트")
    summary_lines.append("-" * 70)
    summary_lines.append("backup\\20260722_222818")
    summary_lines.append("")
    summary_lines.append("금지")
    summary_lines.append("-" * 70)
    summary_lines.append("Codex 작업 중 public/data export 금지")

    RUNBOOK.write_text("\n".join(runbook_lines), encoding="utf-8")
    SUMMARY.write_text("\n".join(summary_lines), encoding="utf-8")

    print()
    print("FANDEX v7.1 runbook 생성 완료")
    print("=" * 70)
    print(f"runbook: {RUNBOOK}")
    print(f"summary: {SUMMARY}")
    print()
    print("확인:")
    print("notepad FANDEX_V7_1_RUNBOOK.txt")
    print("notepad FANDEX_V7_1_OPERATING_SUMMARY.txt")


if __name__ == "__main__":
    main()