from datetime import datetime
from pathlib import Path


NOTE_FILE = Path("FANDEX_V7_1_STABLE_NOTE.txt")


def main():
    now = datetime.now().isoformat(timespec="seconds")

    lines = []
    lines.append("FANDEX v7.1 Stable Note")
    lines.append("=" * 70)
    lines.append(f"createdAt: {now}")
    lines.append("")
    lines.append("안정화 이름")
    lines.append("-" * 70)
    lines.append("FANDEX Python-only v7.1 stale decay stable")
    lines.append("")
    lines.append("복구 가능한 백업")
    lines.append("-" * 70)
    lines.append("backup\\20260722_222818")
    lines.append("")
    lines.append("검증 상태")
    lines.append("-" * 70)
    lines.append("fandex_verify_backup_v1.py 검증 통과")
    lines.append("backup manifest와 실제 파일 수 일치")
    lines.append("백업 파일 수: 136")
    lines.append("")
    lines.append("현재 공식 ranking")
    lines.append("-" * 70)
    lines.append("1위 에이티즈 | FANDEX 474.86 | 네이버 318.77 | YouTube 50.34 | 음원 105.75")
    lines.append("2위 아이유 | FANDEX 473.26 | 네이버 399.65 | YouTube 49.61 | 음원 24.0")
    lines.append("3위 에스파 | FANDEX 409.11 | 네이버 279.11 | YouTube 78.7 | 음원 51.3")
    lines.append("4위 보이넥스트도어 | FANDEX 346.95 | 네이버 302.34 | YouTube 35.01 | 음원 9.6")
    lines.append("")
    lines.append("v7.1 핵심 변경")
    lines.append("-" * 70)
    lines.append("- daily runner v2 적용")
    lines.append("- music chart seed freshness audit 추가")
    lines.append("- stale manual seed decay 공식 반영")
    lines.append("- master v7 생성 전에 stale decay apply 실행")
    lines.append("- status report 명령 안내 v2로 수정")
    lines.append("- health check가 v7.1 핵심 파일 확인")
    lines.append("- website public/data 미접촉")
    lines.append("")
    lines.append("일일 운영 명령")
    lines.append("-" * 70)
    lines.append("run_fandex_daily_python_only.bat")
    lines.append("")
    lines.append("Python 내부 전체 갱신")
    lines.append("-" * 70)
    lines.append("py fandex_daily_python_only_v2.py")
    lines.append("")
    lines.append("YouTube 재수집 포함")
    lines.append("-" * 70)
    lines.append("set YOUTUBE_API_KEY=실제_API_KEY")
    lines.append("py fandex_daily_python_only_v2.py --refresh-youtube")
    lines.append("")
    lines.append("복구 dry-run")
    lines.append("-" * 70)
    lines.append("py fandex_restore_core_files_v1.py backup\\20260722_222818")
    lines.append("")
    lines.append("실제 복구")
    lines.append("-" * 70)
    lines.append("py fandex_restore_core_files_v1.py backup\\20260722_222818 --apply")
    lines.append("")
    lines.append("실행 금지")
    lines.append("-" * 70)
    lines.append("Codex 작업 중에는 아래 명령 실행 금지:")
    lines.append("py fandex_export_to_site_v1.py")
    lines.append("py fandex_publish_all_v5.py")
    lines.append("py fandex_publish_all_v5.py --refresh-youtube")

    NOTE_FILE.write_text("\n".join(lines), encoding="utf-8")

    print()
    print("FANDEX v7.1 stable note 생성 완료")
    print("=" * 70)
    print(f"파일: {NOTE_FILE}")
    print()
    print("확인:")
    print("notepad FANDEX_V7_1_STABLE_NOTE.txt")


if __name__ == "__main__":
    main()